### ISSUE TITLE
dependency on psutil

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/UMI-tools#10]
Lastest changes make the code dependent on `psutil`, which is not part of the standard library. At a minimum, this should be noted in the README, but since it is only used to output the memory used, perhaps we should reconsider if it is necessary.

**Comment by TomSmithCGAT** [comment]
Apologies, Ian. This function was a hang over from some memory profiling and wasn't actually being used anymore. Function and imports have been removed.
aaa7dfa
e0ade5d
