### ISSUE TITLE
Headers for Sam output

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/UMI-tools#103]
The option ` --out-sam` enables sam ouput. Previously, we did not include `h` in the output mode which defaulted to no header for sam output. From pysam 0.11 onwards, the default behaviour is now to include the header which does seem more sensible (https://github.com/pysam-developers/pysama/releases). 

This is causing all our tests to fail. I can resolve this by switching the header option off again for sam output but I think we should really include the header in the sam output and rebuild the test files. The header is apparently optional, however, I can't see an option to open a headerless sam with samtools (?) so our sam output is currently unusable.

This update would not be backwards compatible but I doubt this option is being used as nobody has raised the issue that the sam output does not contain a header and is not valid input for samtools. What do you think @IanSudbery?

**Comment by IanSudbery** [comment]
I agree

**Comment by TomSmithCGAT** [comment]
Fixed in {TS}-rebuild_tests
