### ISSUE TITLE
Unmatched pair output attempting to use tids (TypeError: an integer is required)

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/UMI-tools#105]
In paired mode we have switched to using reference_names for fetching rather than tids. However, the code that outputs any unmatched reads at the end still trys fetch reads using the tid. This leads to the following error:

```
   File "pysam/libcalignmentfile.pyx", line 761, in pysam.libcalignmentfile.AlignmentFile.parse_region (pysam/libcalignmentfile.c:10345)
TypeError: an integer is required
```

The fact we've not seen this before may be related to an update in pysam version.

The unmatched read finding code is being completely overhauled in the next release and this problem should disappear then.

**Comment by TomSmithCGAT** [comment]
Is there any reason the getting_mates branch hasn't been merged into master? Are we just waiting until we're ready for the next release?

**Comment by IanSudbery** [comment]
I was under the impression you wanted to change the way mate matching
worked with group?
See conversation here:
https://github.com/CGATOxford/UMI-tools/commit/c96dd45d652eeb144d17b6b1f2fcaa166c4f4ba5

**Comment by TomSmithCGAT** [comment]
Ah yes, thanks. Forgot all about that. I'll have a look at getting this done today then we can wrap all this up into a single update.

**Comment by TomSmithCGAT** [comment]
@IanSudbery. Could you take a look at 2a49d4edc5510fca6f1143104338d92fbeefd1d7

The changes:

- Modified the group command so it just writes out the read2s immediately. Hence _group_ no longer uses the TwoPassWriter for paired end reads as we can do it all with one pass through the BAM. 
- Documented the options for get_bundles as there are quite a few options (too many?) and I've started to forget what they're all for!
- Simplified the setting of the tag up the --per-gene method handling (finalised in 556d4e2)

**Comment by IanSudbery** [comment]
Hi Tom, 

Looks good if thats the way you want to go with group.

**Comment by TomSmithCGAT** [comment]
Great.!

I've put in a couple of Pull requests for the {TS}-debug_per-gene and {TS}-debug_per_gene branches (I accidentally created two very similarly named branches to debug different per-gene methods).
The will be some conflicts between these branches and the 'getting_mates' branch so I'll wait for these pull requests to be accepted and resolve the conflicts locally before the 'getting_mates' pull request. Then I think we're ready to release 0.5.0 with fully functional per-gene deduplication!
