### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/UMI-tools#107]
Self explanatory.

There is some advice I keep offering over and over to people getting in contact. Particularly with regards to speed issues.

**Comment by TomSmithCGAT** [comment]
Good idea. Possibly some of the quick start guide would be better here too (I'm thinking bespoke UMI extraction etc)?

**Comment by TomSmithCGAT** [comment]
I think we've covered most the issues in the two guides. Do we still want a separate FAQ?

**Comment by IanSudbery** [comment]
Eventaully yes, I think we could do with questions about optimising run time etc. But lets leave this for the website rather than 0.5

**Comment by TomSmithCGAT** [comment]
UMI-tools `readthedocs` is now live! 

https://umi-tools.readthedocs.io/en/latest/index.html
