### ISSUE TITLE
Deducing read position

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/UMI-tools#11]
There is a section of the code that tries to deduce the position of the read, taking into account any soft_clipping. It looks like this:

```python
           if read.is_reverse:
                pos = read.aend
                if read.cigar[-1][0] == 4:
                    pos = pos + read.cigar[-1][1]
                start = read.pos

                if ('N' in read.cigarstring or
                    (read.cigar[0][0] == 4 and
                     read.cigar[0][1] > soft_clip_threshold)):
                    is_spliced = True
            else:
                pos = read.pos
                if read.cigar[0][0] == 4:
                    pos = pos - read.cigar[0][1]
                start = pos

                if ('N' in read.cigarstring or
                    (read.cigar[-1][0] == 4 and
                     read.cigar[-1][1] > soft_clip_threshold)):
                    is_spliced = True

```

Note that if the read is reversed, then it takes aend, finds how many bases are add for softclipping.... and then forgets all that and uses read.pos. 

Where if the read is not reversed then it does use the clipping. 

Any ideas why this might be? It goes right back to the initial commit. I'm sure there is a reason for it, but I can't for the life of me figure out what it might be.

**Comment by IanSudbery** [comment]
I think I figured this one out: start isn't actually used for indexing reads, pos is. Start is just used for figureing out if to dump the buffer or not.

**Comment by TomSmithCGAT** [comment]
Just about to say that. Although is there any reason for using start rather than for this purpose?

**Comment by IanSudbery** [comment]
Yes, its to do with making sure that when the buffer empties there is no chance of missing spliced reds.
