### ISSUE TITLE
umi_tools cellbarcode

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/UMI-tools#111]
* This tool would take a BAM with a cell barcode and add a tag for cells which all came from the same cell

* Compute the tags using any of the UMI methods or the knee method

EDIT: From the discussion below these are the functionalities we need to add with UMI-tools _extract_. I suggest we do these sequentially (I'm adding this here to make the checklist visible in the issue description) :

- [x]  Extract cell barcodes. This should allow extraction from any encoding pattern. 
- [x]  Identify the 'true" cell barcodes by 'knee' method or network-based method.
- [x]  Error correct cell barcodes 

EDIT END.

**Comment by TomSmithCGAT** [comment]
Text above from @IanSudbery's project note. 

I think there's an argument for performing the cell barcode grouping prior to alignment since all we need is the counts per cell barcode. The steps would be:

1. Parse the input fastqs and extract the cell barcode. Count reads per cell barcode
2. Identify the number of "true" cell barcodes (knee method or network-based method) -> barcode whitelist
3. Re-parse the input fastq, extract the UMI and cell barcode and write out all reads in the whitelist. We could also error-correct cell barcodes here. If knee method, correct barcodes within 1 edit distance of a single "true" barcode. If network-based method, correct all barcodes within the same group.

**Comment by IanSudbery** [comment]
I suppose I was thinking that the pipeline would be:

1. Parse input fastqs and extract both cell bc and UMIs, add to read name
2. Align.
3. Process aligned file to convert the cell barcode stored in the name to a cell barcode tag, doing any grouping or correcting. 

I hadn't twigged that statistics on the barcodes could be output by extract and the grouping done at that point meaning we would only need two passes over the file - one to extract and group and one to label. My original pipeline would have had one to extract, one pass to do the group and correcting and one pass to label, where the final two passes would be done in a single tool call. 

Your way probably makes more sense.

**Comment by TomSmithCGAT** [comment]
Ok so there are functionalities we need to add with UMI-tools _extract_. I suggest we do these sequentially:

- [ ]  Extract cell barcodes. This should allow extraction from any encoding pattern. 
- [ ]  Identify the 'true" cell barcodes by 'knee' method or network-based method.
- [ ]  Error correct cell barcodes

**Comment by TomSmithCGAT** [comment]
Hi @IanSudbery. I've re-written _extract_ so that it now works from a regex rather than a pattern of N/Xs. See b35e9c8ff6b6893972809cf6ceddd44b61949227. 

This approach gives is much more flexible than over simply extending the N/X approach. We can now handle:
- Almost any conceivable umi encoding
- Different length barcodes (see the indrop example in tests.yaml)
- Encodings dependent on e.g poly T tail (see the indrop example in tests.yaml)

The downside of this approach is that it's slightly less intuitive for users to see how to describe their umi +/- cell pattern.

I've added the following:
- Cell barcode extraction and filtering However, functions to generate a whitelist using the "knee" method or network-based methods haven't been included yet. Currently there's just a dummy function which returns all cell barcodes observed.
- Option to supply a cell barcode whitelist. However, this doesn't yet correct errors.
- UMI masking (e.g low quality bases > "N")
- New tests for scrb-seq and indrop barcode encoding 

Documentation leaves a lot to be desired!

A few thoughts:
- Do we want to continue supporting the old `--bc-pattern`, `--3-prime` etc options? We could do this with a function that read these old functions in and converted them to the correct regex and make clear these functions are deprecated and liable to be removed from future versions. What do you think?
- The indrop test gives an example of how to extract a variable length cell barcode. However, this is dependent upon a perfect 22bp match in the middle of the read. Ideally we would allow errors in this portion of the match.  I've used the regex module previously which allows you to specify an error tolerance in the match so I'll try this again unless there is a way to do this with re?
- The regexes can become a bit cumbersome to include on the command line. We could allow the user to supply a flatfile with the regex(es).

**Comment by TomSmithCGAT** [comment]
I've changed over to the regex module to allow "fuzzy" matches (f35f304f3ab652b7dd63aec3363daca5b8b8be65).

This enables the user to specify much more complex matches, inc substitions (as show in the indrop_fuzzy test) and insertions and deletions (see https://pypi.python.org/pypi/regex/ ; 'Approximate “fuzzy” matching'). This could be useful in the non-barcode portion of the match but we should make clear to users that we cannot support indels in the cell barcode or UMI. For proper defensive programming, we could also check that the user hasn't supplied a regex with fuzzy matches for the cell barcode or umi. I can't see any way to check for this directly from the compiled regex but we could write a function to parse the regex string.

See below for the run time over 1M indrop reads  (plus cProfile overhead)  
- regex exact: 
(?P<cell_1>.{8,12})(?P<discard_2>GAGTGATTGCTTGTGACGCCTT)(?P<cell_3>.{8})(?P<umi_1>.{6})T{3}.*
- regex fuzzy: 
(?P<cell_1>.{8,12})(?P<discard_2>GAGTGATTGCTTGTGACGCCTT){s<=2}(?P<cell_3>.{8})(?P<umi_1>.{6})T{3}.*

| module | regex | matched reads |  time (s)|
|:-----------|---------|--------------------|-----------|
|re | exact | 555310|489 |
|regex | exact |555310 | 487|
|regex | fuzzy|570168 | 518|

Using regex doesn't increase the runtime significantly and allows 2.6% more reads to match the regex in this case. Note that the run time is currently much longer than I would like. Currently 100M paired end indrop reads would take 14 hours to process with _extract_. This run time also doesn't include identifying the 'true' cell barcodes.

I thought we might be able to utilise regex fuzzy matching matches to support different length UMIs and indel-aware UMI networks where we're ignoring the alignment coordinates (`--per-gene` only). E.g:

true sequence:
[ -- umi -- ] [ -- RNA -- ]
AATTCGA CTAT..........

umi1 = AATTCGA
umi2 = AATTCAC (G deleted, T from RNA erroneously appended to UMI)
Reads align one base apart but on the same gene.

```python
umi1 = regex.compile("(AATTCGA){e<=1}")
umi2 = "AATTCAC"
m = regex.match(umi1, umi2)
print(m.fuzzy_counts) # (sub, ins., del.)
```
```
(0, 0, 1)
```

I compared the run time for our edit_distance function and using regex allowing an error (substitution, insertion or deletion). It looks like the regex match is only 3-times slower when the regex is compiled. However, we would need to re-compile a new regex every time umi1 changes when comparing umi1<->umi2 and the run time when not pre-compiling is ~30x longer for regex. So we might be able to detect indels with a caveat that run times for deep sequenced sample may be very long!

```python
print(timeit.timeit('edit_distance(umi1, umi2)', number=1000000,
                    setup='from umi_tools._dedup_umi import edit_distance; umi1 = b"AATAGGA"; umi2 = b"AATTGGA"'))
print(timeit.timeit('umi1.match(umi2)', number=1000000,
                    setup='import regex; umi1 = regex.compile("^(AATAGGA)${e<=2}"); umi2 = "AATTGGA"'))
print(timeit.timeit('regex.match(umi1, umi2)', number=1000000,
                    setup='import regex; umi1 = umi1="^(AATAGGA)${e<=2}"; umi2 = "AATTGGA"'))
```
```
0.06958824495086446
0.24157764099072665
1.8664034839603119
```

**Comment by IanSudbery** [comment]
> •         Do we want to continue supporting the old --bc-pattern,
--3-prime etc options? We could do this with a function that read these old
functions in and converted them to the correct regex and make clear these
functions are deprecated and liable to be removed from future versions.
What do you think?



Definitely, at least in the short term. In the long term I think that if we
do remove the –bc-pattern option, we need to supply a simplified option to
just extract the first x bases. I think that demanding our users supply
regexs for a simple task (and I guess most common use?) is too much –
particularly as they are especially complicated regexes.



> •          The regexes can become a bit cumbersome to include on the
command line. We could allow the user to supply a flatfile with the
regex(es).



It might be good to allow this, but we definitely shouldn’t mandate it. I
hate configuration files.



>•           The indrop test gives an example of how to extract a variable
length cell barcode. However, this is dependent upon a perfect 22bp match
in the middle of the read. Ideally we would allow errors in this portion of
the match. I've used the regex module previously which allows you to
specify an error tolerance in the match so I'll try this again unless there
is a way to do this with re?



I know of no way to do this with re. We’ll have to balance the cost of an
additional dependency with gain from the error tolerant matching.





*From:* Tom Smith [mailto:notifications@github.com]
*Sent:* 11 May 2017 17:49
*To:* CGATOxford/UMI-tools <UMI-tools@noreply.github.com>
*Cc:* Ian Sudbery <i.sudbery@sheffield.ac.uk>; Mention <
mention@noreply.github.com>
*Subject:* Re: [CGATOxford/UMI-tools] umi_tools cellbarcode (#111)



Hi @IanSudbery <https://github.com/iansudbery>. I've re-written *extract*
so that it now works from a regex rather than a pattern of N/Xs. See b35e9c8
<https://github.com/CGATOxford/UMI-tools/commit/b35e9c8ff6b6893972809cf6ceddd44b61949227>
.

This approach gives is much more flexible than over simply extending the
N/X approach. We can now handle:

   - Almost any conceivable umi encoding
   - Different length barcodes (see the indrop example in tests.yaml)
   - Encodings dependent on e.g poly T tail (see the indrop example in
   tests.yaml)

The downside of this approach is that it's slightly less intuitive for
users to see how to describe their umi +/- cell pattern.

I've added the following:

   - Cell barcode extraction and filtering However, functions to generate a
   whitelist using the "knee" method or network-based methods haven't been
   included yet. Currently there's just a dummy function which returns all
   cell barcodes observed.
   - Option to supply a cell barcode whitelist. However, this doesn't yet
   correct errors.
   - UMI masking (e.g low quality bases > "N")
   - New tests for scrb-seq and indrop barcode encoding

Documentation leaves a lot to be desired!

A few thoughts:

   - Do we want to continue supporting the old --bc-pattern, --3-prime etc
   options? We could do this with a function that read these old functions in
   and converted them to the correct regex and make clear these functions are
   deprecated and liable to be removed from future versions. What do you think?
   - The indrop test gives an example of how to extract a variable length
   cell barcode. However, this is dependent upon a perfect 22bp match in the
   middle of the read. Ideally we would allow errors in this portion of the
   match. I've used the regex module previously which allows you to specify an
   error tolerance in the match so I'll try this again unless there is a way
   to do this with re?
   - The regexes can become a bit cumbersome to include on the command
   line. We could allow the user to supply a flatfile with the regex(es).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CGATOxford/UMI-tools/issues/111#issuecomment-300849311>,
or mute the thread

**Comment by TomSmithCGAT** [comment]
I've reinstated the --bc-pattern options and included a --extract-method option so that the user can either provide a string of X/N/Cs to extract UMI +/- cell barcodes or a regex (see 92ddf1c0de07e4a3759af8e2bfd9d43fc343191e).

**Comment by TomSmithCGAT** [comment]
I've also had a quick look at the merits of using the network-based methods for detecting the true cell barcodes. I started with the Soumillon et al SCRB-Seq data since this involves 384 whitelist barcodes so I've got a ground truth. The plots below shows the sensitivity and FPR with increasing numbers of reads parsed (not sampled randomly). I was lazy with the 'knee' method and just took the top 384 barcodes which should be a reasonable estimate of the best performance we would get with this method - I've not yet implemented the 'knee' method. The plot is facetted by the edit-distance threshold. The 'best-knee' method is shown in both panels for comparison although this method obviously doesn't involve an edit-distance threshold.

![psens](https://cloud.githubusercontent.com/assets/6096414/26116949/d400b316-3a5c-11e7-8017-42a637bedf54.png)

![pfpr](https://cloud.githubusercontent.com/assets/6096414/26116953/d5315bdc-3a5c-11e7-98a3-e0c66be6915e.png)

The directional method appears to be very suitable to determine the top cell barcodes with this data. I'll have a look for some other publically available data with a whitelist to repeat the comparison. The obvious caveat with using data with a whitelist is that these barcodes have been purposely designed to be > 1 edit-distance apart so good performance with these data sets might not correspond to good performance when the cell barcodes are truly randomly selected. I can't see any way to test performance with truly random cell barcodes except by simulations?

There's a danger with truly random cell barcodes that we'll be over zealous in the cell barcode correction using the network-based methods. I think we should mitigate against this by only correcting cell barcodes where the counts are less than the least abundant 'true' cell barcode. This way, if we do erroneously group multiple barcodes from different cells together, only the reads from the top cell barcode in the group will be retained - We will still lose some cells but we should minimise the probability of accidentally merging cells _in silico_.

**Comment by TomSmithCGAT** [comment]
First off, the good news: I've implemented a version of the 'knee' method. Now the bad news, network-based methods will not work for droplet scRNA-Seq.

**Knee method**
I started with the SCRB-Seq data again and tried to identify the 'inflection' point in the graph of ranked cell barcodes vs. cumulative sum of reads, as suggested in the drop-seq paper (See [Supp.Fig 3A](http://www.sciencedirect.com/science/article/pii/S0092867415005498) and supp methods). I found it easier to work from a density plot of reads per barcode and identify the mid point between the distribution of 'true' barcodes and 'false' barcodes which should be equivalent to the inflection point. To estimate this I simply took the local minima (see Fig. 1 below). As you can see, there are multiple local minima and often there is one in the region of very high read counts. To deal with this heuristically, I took the first local minima at <80% of the max (log10) read counts per barcode. I'm very open to suggestions about how to do this better. The plot also shows the position of the 384th read which should be a good estimate of the true inflection point as there were 384 whitelist barcodes here. 

![100000000_dist](https://cloud.githubusercontent.com/assets/6096414/26202276/ab8f1936-3bce-11e7-9dc2-392547eff745.png)
_Fig. 1 Distibutions of reads(log10) per cell barcode. Blue vertical line represents 384th cell barcode. Green = local maxima, Orange = local minima._

Fig. 2 + 3 show the ranked cumulative plot which clearly demonstrates that this method identifies the inflection or 'knee' as intended. Please ignore the 'directional' line here.

![all_methods_knee_100000000](https://cloud.githubusercontent.com/assets/6096414/26202383/2b0defde-3bcf-11e7-84be-31081ae77396.png)
_Fig. 3_ Cumulative frequency plot with 'knee' method inflection point estimation

![all_methods_knee_100000000_zoom](https://cloud.githubusercontent.com/assets/6096414/26202403/3e563574-3bcf-11e7-92cf-ef4ab5737dce.png)
_Fig. 3_ Cumulative frequency plot with 'knee' method inflection point estimation (zoomed)

Fig. 4 + 5 are the same as the comment above but with the actual 'knee' method shown separately from simply selecting the top 384 barcodes. As you can see, the directional method outperforms the 'knee' method. Fig. 6 + 7 are Fig 4 +5 zoomed into the region of interest

![psens](https://cloud.githubusercontent.com/assets/6096414/26202443/61faad34-3bcf-11e7-95fb-a314db8729ca.png)
_Fig. 4_ 

![pfpr](https://cloud.githubusercontent.com/assets/6096414/26202430/5397e798-3bcf-11e7-9530-043b84c03fc1.png)
_Fig. 5_ 

![psens_zoom](https://cloud.githubusercontent.com/assets/6096414/26202499/92a11964-3bcf-11e7-95a8-dd6970821ab3.png)
_Fig. 6_ 

![pfpr_zoom](https://cloud.githubusercontent.com/assets/6096414/26202504/96c1f1c6-3bcf-11e7-8c32-73c828ea5f7c.png)
_Fig. 7_ 

** droplet scRNA-Seq **
I next took a sample from the above drop-seq paper where the authors suggest there were ~570 true cell barcodes based on the inflection point (I think this was done by visual assessment). Fig. 6 below shows that the knee method correctly identifies the position of the inflection (573 cell barcodes). However, when I use the directional method, I get high sensitivity (>95%) but very poor specificity (<30%). Furthermore, the specificity is worse with more reads! This lead me to realise that this issue here is that the 'false' cell barcodes are not by-and-large sequencing errors but real cell barcodes from droplets without cellular RNA (ambient RNA only as discussed in the Sup Fig3A legend). We can demonstrate this by looking at the minimum edit distance between the 'false' barcodes and the 'true' barcodes and separating the false barcodes into three groups based on Fig. 8 density plot (bin "1" < 100 reads per barcodes, "2" 100-1000, "3" = 1000-10000). Fig. 9 shows the distribution of minimum edit distances for the 3 bins. Bin 3 clearly contains some barcodes generated by errors from a 'true' barcode since this bin is heavily skewed towards single edit distance relative to the null. On the other hand bins 1 + 2 show null-like distributions suggesting these reads originate from very low frequency cell barcodes (e.g non-droplet encapsulated). From the density plot and edit-distances, I'd be tempted to suggest the barcodes in these bins are in fact generated by two separate processes. 

![indrop_dist](https://cloud.githubusercontent.com/assets/6096414/26202916/11c4f8ea-3bd1-11e7-9e63-4b0e23e0829b.png)
_Fig. 8_ 

![edit_distances_drop_seq](https://cloud.githubusercontent.com/assets/6096414/26203303/9df08e28-3bd2-11e7-8329-561891410289.png)
_Fig. 9_ 

The strength of the knee method is that it doesn't make any assumptions about the sequences themselves. Thus, it works well in both situations. I had hoped we might be able to resolve this by combining the methods. I.e, use the 'knee' method to exclude the background random barcodes (remove all barcodes with < 0.1 * read counts at the knee = bins 1 + 2) and then use the network method to more accurately separate 'true' barcodes and errors. Unfortunately, even Bin 3 contains many barcodes which do not appear to have originated from errors, regardless how tight the threshold is set

** Summary ** 
The directional method slightly outperforms the knee method when false barcodes are only generated by errors. However, when this is not the case, the knee method is the only sensible options demonstrated so far. I suggest we make both options available, default to 'knee', document the situation in which directional will work and warn users if they use it. We can also output plots to allow users to asses how well the 'true' barcode selection worked.

**Comment by TomSmithCGAT** [comment]
I've spun this out into a [post on the CGAT blog](https://cgatoxford.wordpress.com/2017/05/18/estimating-the-number-of-true-cell-barcodes-in-single-cell-rna-seq/?iframe=true&theme_preview=true) to try and help publicise what we're up to with UMI-tools at the moment.
