### ISSUE TITLE
Add ability to consider cell barcode with count command

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/UMI-tools#112]

**Comment by TomSmithCGAT** [comment]
@IanSudbery. Could you clarify exactly where we want to consider the cell barcode and for what purpose? E.g do we want to support cell barcodes for both _dedup_ and _count_? Are we going to output error-corrected cell barcodes?

**Comment by IanSudbery** [comment]
I think it would be easy enough to support in both dedup and count.

**Comment by TomSmithCGAT** [comment]
I'm moved this back to 'To Do' since we haven't actually finished off the handling of cell barcodes. The last step is to support cell barcodes within _group_, _count_ and _count_tab_
