### ISSUE TITLE
per-gene deduplication on genome mapping

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/UMI-tools#113]

**Comment by TomSmithCGAT** [comment]
This is currently supported using the --gene-tag  option. However, this assumes the reads will be in gene order which may not be the case where there are overlapping genes. We need to come up with a more robust method to yield all reads per gene

**Comment by IanSudbery** [comment]
The problem with the non-sorted gene tags was what made me come up with the idea for "count" in the first place.

**Comment by TomSmithCGAT** [comment]
Of course, we just enable `--gene-tag` with `count` only since all users will ultimate be using `--gene-tag` to obtain counts per gene in the end. I was stuck thinking of a way to solve a problem that doesn't need to be solved!

**Comment by TomSmithCGAT** [comment]
We currently support --per-gene deduplication with genome mapping providing the BAM contains a tag with the gene id or transcript_id and a transcript2gene map file. We have no plans to support --per-gene deduplication when gene tags are not present.
