### ISSUE TITLE
deciding when to output

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/UMI-tools#12]
When using positions, the alogrithm uses the following code to decide whether to output or not:

```python
           if whole_contig:
                do_output = not read.tid == last_chr
            else:
                do_output = start > (last_pos+1000) and not read.tid == last_chr
```
note that in the second case the condition is that we are 1kb on AND on a different chr. Surely this should be OR? 

This was leading to reads being output in a very strange order. Could possibly lead to reads from difference chrs being combined in the same bundle, and is possibly to blame for some of the high memory usage (will almost certainly read whole file into memory this way).

Again, seems like a simple fix, but I feel like we've been here before, and don't want to make the change if I'm missing something.

**Comment by TomSmithCGAT** [comment]
I hadn't noticed that. Yeah, as far as I'm concerned the last line should be:
```python
do_output = start > (last_pos+1000) or read.tid != last_chr
```
It'd be interesting to know how it affects memory usage?..

**Comment by IanSudbery** [comment]
I'll put it in my next commit.

**Comment by IanSudbery** [comment]
Done, see 7490815a97e4affd959d215505dec987af5e9e21. Can lead to a drastic reduction in memory usage.

In my test of one chr, memory usage went from 3Gb to 300mb. This is good because on a full genome, I was breaching a 21Gb usage!

**Comment by TomSmithCGAT** [comment]
Thanks Ian!
