### ISSUE TITLE
--paired causes crash

### ISSUE THREAD

**Issue by singerj** [CGATOxford/UMI-tools#132]
If I specify the --paired option I get the following message:

File "UMI-tools-0.4.4/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "UMI-tools-0.4.4/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 46, in main
    module.main(sys.argv)
  File "UMI-tools-0.4.4/lib/python2.7/site-packages/umi_tools/group.py", line 520, in main
    outfile.write(read, unique_id, top_umi)
TypeError: write() takes exactly one argument (3 given)

Since there is no specialised write function I guess the unique_id and top_umi have to be treated similar to the case with --paired not specified.

if options.paired:
    # if paired, we need to supply the tags to
    # add to the paired read
    outfile.write(read, unique_id, top_umi)
else:
    # Add the 'UG' tag to the read
    read.tags += [('UG', unique_id)]
    read.tags += [(options.umi_group_tag, top_umi)]
    outfile.write(read)

**Comment by IanSudbery** [comment]
See issue #130

**Comment by singerj** [comment]
Thank you for the swift response! Indeed, the patch proposed for issue 130 solved the problem. 

Many thanks,
Jochen
