### ISSUE TITLE
options.gene_map should be options.gene_tag ?

### ISSUE THREAD

**Issue by JakeHagen** [CGATOxford/UMI-tools#133]
Hello, 

I know there is currently some flux with the gene_tag in dedup.py and count.py, but i think the code below should be gene_tag, not gene_map

```
if options.per_gene:
    if not options.gene_transcript_map and not options.gene_map:
        raise ValueError("--per-gene option requires --gene-transcript-map or --gene-tag")
```
It works as expected when changed.

Thanks

**Comment by TomSmithCGAT** [comment]
Yep, this looks like a typo! I'll fix on the master directly. Thanks!
