### ISSUE TITLE
Edit-distance option

### ISSUE THREAD

**Issue by MeAndATCG** [CGATOxford/UMI-tools#134]
Thank you very much for designing/releasing a wonderful package. Great algorithm!!!

I need your help with edit distance option. In particular, I need to know how to generate the average edit distance plot (regenerate Fig.1-B in your paper), so I can change edit distance default setting.

Thank you!!!
Sheida

**Comment by TomSmithCGAT** [comment]
Hi @MeAndATCG. You can generate the average edit distance statistics using the 
`--output-stats=[FILE_PREIFX]`
option, replacing `[FILE_PREFIX]` with a filename prefix. This will output a file called [FILE_PREFIX]__stats_edit_distance.tsv. 

As a rough guide, we recommend using the default edit distance of 1 for UMIs <14bp and an edit distance of 2 for UMIs >=14bp. If you have very high error rates (Phred <15) in the region of your UMI, you may also want to use an edit distance of 2 for UMIs >=10bp.

**Comment by MeAndATCG** [comment]
Thank you very much for your help, Tom!!!
I always look into stat_edit_distance.tsv file, but I do not understand why UMIs count does not match/correlate with my total prior and post UMI count. As an example, consider I have an input bam file with 589554 reads (UMIs) and output (dedup) of 74515 UMIs. Here is the edit distance file:

directional	directional_null	edit_distance	unique	unique_null
90      90      Single_UMI      88      88
0       0       0       0       0
0       0       1       2       0
2       0       2       2       0
2       0       3       2       0
5       0       4       7       0
7       2       5       6       0
6       1       6       6       1
8       3       7       9       2
14      7       8       13      4
45      66      9       46      68
13      17      10      11      26
2       8       11      2       3
0       0       12      0       2
0       0       13      0       0
How do you explain this? 

Thanks again for your help.

**Comment by IanSudbery** [comment]
The edit distance stats shows the number of *positions* with each average edit distance, rather then the number of reads. Thus each one of those 46 positions with an average edit distance of 8 may have many reads.

However, your results do look very extreme. They suggest that your 75k reads map to only a very small number of locations. Is this what you would expect? What is the results of running with --ignore-umi?

>

**Comment by MeAndATCG** [comment]
Yes, this is what I've expected, a few targets. Thank you for clarification!!!
