### ISSUE TITLE
regex depedency not documented

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/UMI-tools#140]
The new regex dependency is not documented anywhere.

**Comment by IanSudbery** [comment]
And scipy dependency

**Comment by TomSmithCGAT** [comment]
They're both included in setup.py and requirements.txt. Do you mean the dependency is not noted at the bottom of the Github repository readme?

**Comment by IanSudbery** [comment]
Or in the manual installation instructions.

**Comment by TomSmithCGAT** [comment]
See #139
