### ISSUE TITLE
ValueError reference id out of range for umi dedup

### ISSUE THREAD

**Issue by samvidav** [CGATOxford/UMI-tools#147]
Hi, I have been trying to run umi_tools dedup on a large number of BAM files after STAR alignment, and I get the same ValueError reference_id -1 out of range error for each of them - 

`Traceback (most recent call last):
  File "/home/obgynae/svenkate/.local/bin/umi_tools", line 11, in <module>
    load_entry_point('umi-tools==0.4.4', 'console_scripts', 'umi_tools')()
  File "/home/obgynae/svenkate/.local/lib/python3.5/site-packages/umi_tools/umi_tools.py", line 46, in main
    module.main(sys.argv)
  File "/home/obgynae/svenkate/.local/lib/python3.5/site-packages/umi_tools/dedup.py", line 612, in main
    outfile.write(read)
  File "/home/obgynae/svenkate/.local/lib/python3.5/site-packages/umi_tools/umi_methods.py", line 99, in write
    key = read.query_name, read.next_reference_name, read.next_reference_start
  File "pysam/libcalignedsegment.pyx", line 1011, in pysam.libcalignedsegment.AlignedSegment.next_reference_name.__get__ (pysam/libcalignedsegment.c:13235)
  File "pysam/libcalignmentfile.pyx", line 1626, in pysam.libcalignmentfile.AlignmentFile.getrname (pysam/libcalignmentfile.c:18746)
  File "pysam/libcalignmentfile.pyx", line 691, in pysam.libcalignmentfile.AlignmentFile.get_reference_name (pysam/libcalignmentfile.c:9608)
ValueError: reference_id -1 out of range 0<=tid<24`

I checked the validity of my BAM files with picard tools, and they seem to be fine. Do you have any suggestions to help with this? 

Thanks!

**Comment by IanSudbery** [comment]
The reference_id of -1 is returned when the read is unmapped. The line causing the error suggests that umi_tools is trying to retrieve the contig of the mate of the current read. However, umi_tools checks the flags to see if the mate is unmapped and doesn't ask for its contig if its told that it isn't.

Thus the most obvious problem here would be that you have a read that claims its mate is mapped, but has no contig in the field that is supposed to hold the contig of the mate (i.e. it is set to '*'). I don't know if picard tools checks for this. 

You can find if this is the case using:
```
samtools view -F8 my_bam.bam | awk '$6=="*"'
```

A valid BAM file should have empty output for this.

**Comment by samvidav** [comment]
I just checked the mate mapping on some of the BAM files and the output is indeed empty. Additionally, I don't know if this helps in identifying the issue but dedup does produce an output file - it has just the header and nothing else.

**Comment by IanSudbery** [comment]
Sorry, that command should have been
```
samtools view -F8 my_bam.bam | awk '$7=="*"'
```


That the output contains only the header suggests the first read that it tries to output is breaking it!

You could also try sending me the first few lines of your BAM (or the first chr would be even more helpful). Remove the sequence and qualities (replace them with *) if that makes you feel more comfortable. FUrthe anonmyissation can be achieved by adding a secrete distance to each POS and PNEXT (same one to each). Also you can email them to me if you don't want it on here.

**Comment by samvidav** [comment]
Ah okay, with that change in awk I seem to have found the problem - the BAM files are invalid. It works after mapping again!
