### ISSUE TITLE
Python interface?

### ISSUE THREAD

**Issue by koelling** [CGATOxford/UMI-tools#148]
I was wondering - is there a good way to call umi_tools methods directly from a python script, rather than through the executable?

I have a python script in which I collect a set of reads at a given position and then want to do things with them based on their UMI groups. At the moment I do this by first running `umi_tools group` on the BAM file (using the adjacency method), reading the grouped BAM file in my script and extracting the UMI group tag from that.

However, it would be much more convenient if I could simply read the original BAM file, extract the raw UMI sequences myself, and then simply call umi_tools to do the adjacency grouping.

Looking at your code it seems like I might be able to do something similar to this: https://github.com/CGATOxford/UMI-tools/blob/master/umi_tools/group.py#L510

Eg.
```
import umi_tools.network
processor = umi_tools.network.UMIClusterer('adjacency')
umi_groups = processor(umi_raw_seqs, umi_raw_counts)
```

Where `umi_raw_seqs` is my list of UMIs at a given location and `umi_raw_counts` a dict of their counts. I would then assume I would get back a list of UMI groups with the raw UMIs in each.

Is that correct?

It would be great if there was an official interface for this though, in particular since I'd want to be sure that this doesn't get broken with the next update.

**Comment by IanSudbery** [comment]
Yes, that is exactly right. 

An official interface to this is something we are working on, what you've found is the refactoring we've done recently to make this possible. Eventually we hope to make this a C-library to aid with portability to many libraries. 

At the moment, as the interface is currently internal I can't guarantee it won't change. That said, I think that change is unlikely in the near future.

**Comment by IanSudbery** [comment]
Oh, and just checking that you meant to do adjacency clustering rather than directional adjacency clustering (using `method="directional"`)? Directional is usually our recommendation, unless you have specific reasons to use `adjacency`.

**Comment by koelling** [comment]
Yes, I meant directional, sorry! So something like this should work then?

```
umi_raw_seqs = ['AAAC', 'AAAG', 'TCAG']
umi_raw_counts = {'AAAC': 10, 'AAAG': 1, 'TCAG': 10}
import umi_tools.network
processor = umi_tools.network.UMIClusterer('directional')
umi_groups = processor(umi_raw_seqs, umi_raw_counts)
for umi_group in umi_groups:
    top_umi = umi_group[0]
    for raw_umi in umi_group:
        print('%s belongs to group %s' % (raw_umi, top_umi))
```

Is there anything else I should keep in mind if I use this? Any reason you require UMIs and counts as two separate arguments instead of just doing `umis = counts.keys()`?


I did actually just try to run this, but realised that the latest release doesn't actually include these changes yet. Do you know when this might be ready to be released?

**Comment by IanSudbery** [comment]
There was a reason, although I don't now remember what it was! I think it might have been to preserve pre-existing function signatures. I think it might have been because we had to get the list to make the dictionary, and it seemed inefficient to discard the list only to regenerate it on the other side of the call. 

We were planning to release this week, but things have gotten in the way, So we'll see. It might be next week.

**Comment by koelling** [comment]
Maybe you could redefine `UMIcluster.__call__` as `def __call__(self, counts, threshold, umis = None)` and then do `if umis is None: umis = counts.keys()`? But it's no big deal, I was just curious.

Great to hear you're planning on releasing the updated version soon, this/next week would be great! Also to fix that issue with `umi_tools group --paired` crashing.

**Comment by koelling** [comment]
Just wanted to check whether you had an ETA for the new release already! It would be good to know if that's coming soon or if it's better to downgrade to 0.4.3 and work with that for now.

**Comment by TomSmithCGAT** [comment]
Hey @koelling - The master branch is now essentially ready for release as v0.5. The final things we want to complete relate to documentation and a minor update to the `whitelist` command. I'd recommend using the master as it currently stands as updating to 0.5 when it's released.

**Comment by koelling** [comment]
Thanks @TomSmithCGAT! I could certainly do that, but it would make things quite complicated for some other people that want to run my code. I was planning on just asking them to install umi_tools 0.5 through pip, which would be a lot less complicated than asking them to install something manually from GitHub. Especially since that would then probably need to be replaced by the official release later on.

Do you have a rough idea how long 0.5 might take? If it's a few more days I'd wait, if it's a few more weeks we might need to go with the Github version...

**Comment by TomSmithCGAT** [comment]
We are expecting to release 0.5 tomorrow!

**Comment by k3yavi** [comment]
kudos!!

**Comment by TomSmithCGAT** [comment]
Hi @koelling. v0.5 is now out (and available through `pip` and `conda`). Happy grouping!

**Comment by koelling** [comment]
This is perfect, thank you very much @TomSmithCGAT @IanSudbery!
