### ISSUE TITLE
group.py  --paired option error

### ISSUE THREAD

**Issue by djm-h** [CGATOxford/UMI-tools#150]
I have been receiving the following error when trying to run group.py on a BAM file using the --paired option:

_Traceback (most recent call last):
  File "/home/davemh/Envs/UMI/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/home/davemh/Envs/UMI/local/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 46, in main
    module.main(sys.argv)
  File "/home/davemh/Envs/UMI/local/lib/python2.7/site-packages/umi_tools/group.py", line 520, in main
    outfile.write(read, unique_id, top_umi)
TypeError: write() takes exactly one argument (3 given)_

I have tried running the exact same group.py command without the --paired option and it runs fine.  It looks like the --paired option is throwing the script to an outfile.write() with 3 arguments which makes python unhappy, whereas without the --paired option the script goes to outfile.write() with 1 argument.  The error is happening on line 520 in group.py, I have copied that area of the script below.  Any thoughts??

for umi in umi_group:
    reads = bundle[umi]['read']
    for read in reads:
        if outfile:
            if options.paired:
                # if paired, we need to supply the tags to
                # add to the paired read
                **outfile.write(read, unique_id, top_umi)**  #(this is line 520 throwing the error)

            else:
                # Add the 'UG' tag to the read
                read.tags += [('UG', unique_id)]
                read.tags += [(options.umi_group_tag, top_umi)]
                outfile.write(read)

**Comment by djm-h** [comment]
Sorry, formatting of the code looked good when I was writing up the issue... looks funky now that I submitted the issue.

**Comment by djm-h** [comment]
nevermind, working with wrong version.

**Comment by djm-h** [comment]
Pulled latest version 0.4.4 and still having the same issue.  Line 520 in group.py.  If --paired is used, group tries to outfile.write() with 3 arguments, causing group to throw an error.  If --paired is not used, group calls outfile.write() with 1 argument and the program runs fine.  

Any thoughts on how to fix?  Or am I not using group correctly?

**Comment by IanSudbery** [comment]
This is fixed in the master branch of the repository, but not yet in any of the released versions. It should be coming to the releases very soon.

In the meantime, you can download the master version here:
https://github.com/CGATOxford/UMI-tools/archive/master.zip

unzip and install using `setup.py install`

(you may need `--user` depending on your setup)

**Comment by djm-h** [comment]
Great. Thanks!
