### ISSUE TITLE
Unix newbie having umi_tools installation problems

### ISSUE THREAD

**Issue by mnk2017** [CGATOxford/UMI-tools#151]
Hi,

I had a successful install as far as I can tell with pip using the command:
>python -m pip install umi_tools

But when I test the installation using for example:
>python -m umitools --version

It fails: with the error message:
>No module named umitools.__main__; 'umitools' is a package and cannot be directly executed.

When I go into the build directory:
/bin/python/lib/python2.7/site-packages/umi_tools/

 there is no __main__.py only __ini__.py?  Is this right or did the installation fail?

Any help would be appreciated!

**Comment by koelling** [comment]
Maybe I'm missing something here, but shouldn't it just be `pip install umi_tools` to install and then `umi_tools --version` to test? Not sure why you are using `python -m`, or why you wrote `umitools` (without the underscore) in your second command.

**Comment by IanSudbery** [comment]
Hi, 

Yes, that is correct. there is no need for `python -m umitools`

I tink the confusion might be stemming from the fact that there is another package called umitools that has nothing to do with `umi_tools`.

**Comment by mnk2017** [comment]
Thanks those are helpful comments, I have uninstalled umitools.
 
I think umi_tools successfully installed, I've copied and pasted below the results from executing the pip install command.  But I still have the same problem running umi_tools.  I'm finding I need to specify "python -m" for any python program or module to execute in the bash shell.  I've cut and paste the commands I attempted to use and the output that I'm getting.  Any advice is appreciated.

>umi_tools --version
bash: umi_tools: command not found

python -m umi_tools --version
/home/PublicProgramFiles/Python-2.7.12/python: No module named umi_tools.__main__; 'umi_tools' is a package and cannot be directly executed


>pip install umi_tools
-->bash: pip: command not found

>python -m pip install umi_tools
Requirement already satisfied: umi_tools in ./bin/python/lib/python2.7/site-packages
Requirement already satisfied: numpy>=1.7 in ./bin/python/lib/python2.7/site-packages (from umi_tools)
Requirement already satisfied: six in ./bin/python/lib/python2.7/site-packages (from umi_tools)
Requirement already satisfied: cython>=0.19 in ./bin/python/lib/python2.7/site-packages (from umi_tools)
Requirement already satisfied: pandas>=0.12.0 in ./bin/python/lib/python2.7/site-packages (from umi_tools)
Requirement already satisfied: future in ./bin/python/lib/python2.7/site-packages (from umi_tools)
Requirement already satisfied: setuptools>=1.1 in ./bin/python/lib/python2.7/site-packages (from umi_tools)
Requirement already satisfied: pytz>=2011k in ./bin/python/lib/python2.7/site-packages (from pandas>=0.12.0->umi_tools)
Requirement already satisfied: python-dateutil in ./bin/python/lib/python2.7/site-packages (from pandas>=0.12.0->umi_tools)

**Comment by k3yavi** [comment]
@mnk2017 Does your `PATH` variable has the path to the binary?
what does `echo $PATH` command say?

**Comment by mnk2017** [comment]
Sorry my $PATH variable is cluttered.  I'm running on a network that has very old versions of certain publicly available programs installed.  So I created a folder in my own directory that has the latest versions of programs I need installed in my home/PublicPrograms directory for lack of a better idea. (Python, gcc compiler, java, & umi_tools) 

>echo $PATH

/home/PublicProgramFiles/Python-2.7.12:/home/PublicProgramFiles/gcc-6.2.0/bin:/home/PublicProgramFiles/cmake-build/bin:/PublicProgramFiles/bin/python:/opt/UGE8/UGE-8.0.1p7/bin/lx-amd64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/compbio/bin:/compbio/bin/picard:/compbio/scripts:/compbio/pipeline:/home/PublicProgramFiles/jdk1.8.0_111/jre/bin:/compbio/software/IGVTools:/compbio/software/BEDTools-Version-2.9.0/bin:/compbio/software/git/latest/bin

**Comment by IanSudbery** [comment]
I'm guessing your python executable is in `/home/PublicProgramFiles/Python-2.7.12`. Odd that pip is not also there.
I don't know how `pip` determines what directory to install binaries to, I think it might be the directory that the pip executable itself is in. So I don't know what happens if you don't use the executable.
You could probably find out where umi_tools is installed by doing
```
cd /
find . -name umi_tools
```

Might take some time. It you want to use the `python -m` way round things, you'll need `python -m umi_tools.umi_tools --version`
(to call the `umi_tools` module that is part of the `umi_tools` package).

**Comment by mnk2017** [comment]
Thanks it was refreshing to get a different error message!  It seems a step closer to working this time.

>python -m umi_tools.umi_tools --version

Traceback (most recent call last):
  File "/home/PublicProgramFiles/Python-2.7.12/Lib/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/PublicProgramFiles/Python-2.7.12/Lib/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/PublicProgramFiles/bin/python/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 49, in <module>
    sys.exit(main())
  File "/home/PublicProgramFiles/bin/python/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 42, in main
    (file, pathname, description) = imp.find_module(command, [path, ])
ImportError: No module named --version

**Comment by IanSudbery** [comment]
Ooops, my bad, there is no option `--version`, try `--help` instead.

**Comment by mnk2017** [comment]
It works!!  Thank you so much, very excited to start analyzing my runs!
