### ISSUE TITLE
Is it possible to get a refined bam/sam file?

### ISSUE THREAD

**Issue by J-sara** [CGATOxford/UMI-tools#165]
Hi,

I am going to use UMI-tools for analysis of my data set. I want to perform some additional quality control analysis after alignment. Does UMI-tools provide a refined bam/sam file for post alignment quality control analysis?
If not, what is your suggestion for solving this issue? Is there a way to perform post alignment QC analysis according to the results of UMI-tools?

Thanks.

**Comment by IanSudbery** [comment]
Hi,

The `dedup` command will output a BAM file where UMI-tools has gathered together all of the reads that appear to be duplicates of each other and will select one read to output as the representitive read.

The `group` command on the other hand will output a BAM file with exactly the same number of reads as the original file, but each record will gain an extra tag containing the UMI group it belongs to (think of this as a corrected UMI). 

Hope this helps.

**Comment by TomSmithCGAT** [comment]
Hi @J-sara - Were you able to perform the post-alignment QC analysis?
