### ISSUE TITLE
Is newline printing intentional?

### ISSUE THREAD

**Issue by k3yavi** [CGATOxford/UMI-tools#168]
https://github.com/CGATOxford/UMI-tools/blob/e15fe8f8f25c7e0b10e8f7d60009dde7ec5ef1e8/umi_tools/dedup.py#L250

W/o `\r` it just fills the console with all the output.

**Comment by TomSmithCGAT** [comment]
Yeah, this was intentional but perhaps every 10,000 out reads is too frequent? Problem with testing out on smaller test files. Should possibly replace this with `U.debug()` so that this is only logged when user sets verbosity higher.

**Comment by IanSudbery** [comment]
Yeah, the newline is that every output gets a time stamp.

**Comment by k3yavi** [comment]
Gotcha, yes currently in one of the 10x dataset 10k is little too frequent but as you said it can vary. I think setting verbosity level higher is a good option.
