### ISSUE TITLE
UMI Tools dedup on paired end

### ISSUE THREAD

**Issue by Vaishn17** [CGATOxford/UMI-tools#172]
@IanSudbery 
Hi,
I have used the updated bcl2fastq to extract UMIs to the header and it is separated by ":". However when I use umi_tools dedup, it gives me only the read 1 of the paired end reads.

Is it mandatory to use umi extract only before I use umi_tools dedup on paired end reads?

Thanks
Vaish

**Comment by IanSudbery** [comment]
':' seperated UMIs are fine, just make sure you add the UMI to both reads in the pair and specify`--umi-seperator=':'`. You'll also need to run with `dedup` with `--paired`.

**Comment by Vaishn17** [comment]
Hi Ian,
Thanks for your feedback. I ran umi dedup with those options. Unfortunately, I have i5+i7 sequences at the end and umi dedup actually recognizes that as dedup. The UMI is separated by ":' in the read id but it is in between the read id and not at the end.
Is there any work around this?

**Comment by TomSmithCGAT** [comment]
Hi @Vaishn17. This is very odd. The end of the fastq read name line (after the space) shouldn't be included in the BAM read name. 

Would you mind showing us this read in the BAM, e.g:
`samtools view [BAMFILE] | grep "@nb501788:53:H3HYMBGX3:1:11101:19810:1046" | head -1`

**Comment by Vaishn17** [comment]
I could actually resolve this! Thanks!

**Comment by ihuerga** [comment]
Hi @Vaishn17 could you share how did you resolve this? I have exactly the same issue
