### ISSUE TITLE
Errors when sorting output bam

### ISSUE THREAD

**Issue by jingwen** [CGATOxford/UMI-tools#176]
Dear developers,

I tried to run umi-tools dedup on my paired-end bam file (sorted and indexed). After five-minute running, come some error messages below.

_Traceback (most recent call last):
  File "/usr/local/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 50, in main
    module.main(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/umi_tools/dedup.py", line 305, in main
    pysam.sort("-o", sorted_out_name, "-O", sort_format, out_name)
  File "/usr/local/lib/python2.7/site-packages/pysam/__init__.py", line 79, in __call__
    (retval, "\n".join(stderr)))
pysam.SamtoolsError: 'csamtools returned with error 1: [bam_sort] no prefix specified for temporary files (use -T option)\n'_

Then I downloaded example.bam provided in QUICK_START.md, indexed it, and ran the program again.
**umi_tools dedup -I example.bam -S example.dedup.bam --output-stats example.dedup**
However the same error messages came again.

I guess it's related with sorting output bam file... The UMI-tools version installed on my Mac is 0.5. Python version is 2.7.13 and pysam version is 0.8.4 as recommended in the installation guide. Do you have any ideas what caused such issue? 
Thank you!

**Comment by IanSudbery** [comment]
I'm guessing this is to do with the version of samtools/pysam. Either an incompatibility between the two, or we've changed something that means we need to update our pysam dependency version. 

Can you run 
`samtools --version' and let me know the output?

I can't dig into the pysam version right now as I'm on a train, but I'll look at it as soon as I can.

**Comment by jingwen** [comment]
Hi, Ian,
Thanks for your reply.
Here is the output of "samtools --version":
```
samtools 1.5
Using htslib 1.5
Copyright (C) 2017 Genome Research Ltd.
```

Now I realise that the usage of SAMtools sort module was changed after v1.1 (below)
`Usage: samtools sort [options...] [in.bam]`

SAMtools v 0.1.19
`samtools sort [options...] <in.bam> <out.prefix>`
The legacy usage works until v 1.2.

**Comment by IanSudbery** [comment]
Looks like the version of pysam is mismatched with the version of samtools. Could you try updating pysam.

 @TomSmithCGAT is the sort syntax compatible with the version of pysam we are requiring?

**Comment by jingwen** [comment]
Hi, I updated pysam to version 0.12, and it finally worked!
```
OS X 10.12.6
SAMtools 1.5
pysam 0.12
umi-tools 0.5
```
Thanks!
