### ISSUE TITLE
Count from tab-delimited file

### ISSUE THREAD

**Issue by NathanGuy14** [CGATOxford/UMI-tools#183]
Hi,
Not sure if this is the right venue to bring this up, but my project involves using UMIs to correct for amplification biases in an amplicon sequencing/counting experiment.  The basic idea is that I ligate UMIs to both sides of a DNA fragment before amplifying via PCR.  These DNA fragments are synthetic sequences, and until now, I've been using a custom python script implementing the naive "unique" method to count UMIs based on the sample they're from (analogous to the "cell barcodes") and what type of sequence it is (analogous to the "gene locus" if these were mapped reads).  It's like 16S sequencing, except the sequences I'm quantifying are synthetic.  I think that incorporating the network-based algorithm in UMI-tools for my analysis could be super-useful.

My question is, if I have a tab-delimited file that looks like the following (one line per read pair):
Cell                  Gene      UMI  
CellBarcode1   gene1   ATGATCGATA
CellBarcode1   gene2   CGATAGAGCT
Cellbarcode2   gene1   ATGATCAGAT
.....

is there an easy way to reformat this file into something that UMI-tools count can use?  Sorry if this is too specific to my project, but I thought that adding this feature might make UMI-tools generalizable to projects which don't involve mapping reads to a genome.  Thanks for any help you can give!

Nathan

**Comment by TomSmithCGAT** [comment]
Hi @NathanGuy14.
I can think of a couple of approaches so I'll mention them both.

1. Import the `umi_tools.network` module and use the `network.UMIClusterer` functor. 
You can see how the functor is used in `umi_tools.count` [here](https://github.com/CGATOxford/UMI-tools/blob/master/umi_tools/count.py#L129). All you need to do is instantiate it and then call it with a list of umis, a dictionary mapping UMIs to counts and an edit distance threshold. For each call, it'll 
return the groups of UMIs. For your purposes you would only need to know the number of groups which will represent the number of unique molecules identified. 

2. You could make a reference containing the expected synthetic sequences so you can follow the standard UMI-tools pipeline:
- Extract UMIs  -`umi_tools extract`
- Align reads to your reference with e.g BWA
- Count reads per reference contig - `umi_tools count --per-gene --per-contig`

The first approach has the advantage that it is compatible with your current analysis. However, should we update the functor, this may break your code. The second approach will require you to perform additional steps but the analysis will be more stable.

**Comment by IanSudbery** [comment]
> 

Unless I am missing something, I think the "count_tab" command should do exactly this?

>

**Comment by TomSmithCGAT** [comment]
Currently `count_tab` expects a tab-separated input with column 1 = read_id (inc. UMI) and column 2 = assigned gene. We could certainly enable count_tab to take in the input above with little effort

**Comment by NathanGuy14** [comment]
Ah, I missed count_tab!  Thanks for letting me know about that.  I can probably easily reformat my input to be what count_tab expects.  One question: do the read ids need to be in any special format?  I was intending to generate something like the following:

ReadID-UMI   GeneID
1-ATGCAT   gene1
2-GAGAT    gene1
3-GATCG    gene2
...

would this work (as long as each ReadID is unique)? Thanks again for your help!

**Comment by TomSmithCGAT** [comment]
Yes this would work fine, though you would need to add the option `--umi-separator="-"` to tell `count_tab` that your UMIs are separated by a hypen (it expects an underscore by default). It doesn't check the read ids so they could be identical!

**Comment by TomSmithCGAT** [comment]
Good thinking @IanSudbery -  I knew `count_tab` would come in use eventually, I just didn't remember it when it did!

**Comment by NathanGuy14** [comment]
Great!  This will work just fine then.  Thanks, all!
