### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by jsolvason** [CGATOxford/UMI-tools#188]
Sorry... Resolved this issue myself! I had to separately install gcc in order for umi_tools to work.

 did have trouble installing umi_tools with the following commands though (the commands listed on the git hub page):

`conda install -c https://conda.anaconda.org/toms umi_tools`
or
`pip install umi_tools`

Every time I run python setup.py install, I am prompted that I need to install a new required package, and eventually after installing "libfreetype6-dev" I kept being prompted that I need to install "libfreetype6-dev".
`git clone https://github.com/CGATOxford/UMI-tools.git`
`python setup.py install`

This seems to work:
`$ conda install -c bioconda umi_tools` 

Not sure if my troubles with installation are due particular to me or global, but I thought I'd share what works for me.

Joe

**Comment by IanSudbery** [comment]
Hi Joe,

You shouldn't need to run `python setup.py install` if you have run `conda install https://conda.anaconda.org/toms umi_tools`.

Glad it worked from bioconda though...
