### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by nsarode** [CGATOxford/UMI-tools#19]
I get the following syntax error when testing out the script. Is this some python version issue or something else (using version 2.6.6)
python dedup_umi.py --help
  File "dedup_umi.py", line 296
    for umi in umis}
      ^
SyntaxError: invalid syntax

Thanks,
Neha

**Comment by IanSudbery** [comment]
Dear Neha,





Yes I’m afraid it is a python version problem. Currently we only support
2.7. We are working on a proper installation routine that will test for the
correct version of python. Unfortunately, in terms of expanding our
support, we see supporting python 3 as a higher priority than supporting
2.6.



Ian

**Comment by nsarode** [comment]
Not a problem and thanks for getting back to me real quick. This should be an easy problem to fix.

Thanks !
Neha
