### ISSUE TITLE
umi-tools count output lacking gene names

### ISSUE THREAD

**Issue by dandepledge** [CGATOxford/UMI-tools#191]
I'm having trouble with the umi-tools count feature, my output genes are all listed as 'R' rather than the gene name. e.g.

umi_tools count --per-gene --gene-tag=XT --per-cell -I assigned_sorted.bam -S counts.tsv

gene    cell    count
R       AACTCCCCAATCCGAT        1
R       AACTCCCTCTTGGGTA        9
R       AAGACCTTCACCGGGT        4
R       AAGCAGTGGTATCAAC        1
R       ACAGCTAGTAATTGGA        2

Sample output of flags in my SAM file are as follows:

XT:A:R  NM:i:0  AM:i:3  XS:Z:Assigned   XN:i:1  XT:Z:RS1A.gene
XT:A:R  NM:i:18 AM:i:2  XS:Z:Assigned   XN:i:1  XT:Z:US1.gene
XT:A:R  NM:i:20 AM:i:2  XS:Z:Assigned   XN:i:1  XT:Z:US1.gene
NM:i:23 AM:i:7  XS:Z:Assigned   XN:i:1  XT:Z:US1.gene
NM:i:1  AM:i:42 XS:Z:Assigned   XN:i:1  XT:Z:US1.gene
NM:i:1  AM:i:42 XS:Z:Assigned   XN:i:1  XT:Z:US1.gene
NM:i:21 AM:i:9  XS:Z:Assigned   XN:i:1  XT:Z:US1.gene
NM:i:0  AM:i:44 XS:Z:Assigned   XN:i:1  XT:Z:US1.gene
NM:i:2  AM:i:38 XS:Z:Assigned   XN:i:1  XT:Z:US1.gene
NM:i:0  AM:i:44 XS:Z:Assigned   XN:i:1  XT:Z:US1.gene
XT:A:R  NM:i:15 AM:i:2  XS:Z:Unassigned_NoFeatures
XT:A:R  NM:i:12 AM:i:2  XS:Z:Unassigned_NoFeatures

I thought the issue might be related to the duplicate XT entries (the first is placed there by bbmap) but stripping these has no effect on the output (moreover, several entries do not have the XT:A:R flag).

Any help would be much appreciated

**Comment by IanSudbery** [comment]
Hi,

I'm sure that the duplicated XT flags are going to cause a problem, even if its not this one! I'm not sure how pysam (the bam parsing library we use), will handle some reads having the type of the XT flag being A and some being Z (i'm guessing it takes the first instance of the flag to be the value for that read). 

Will have a play and get back.

**Comment by TomSmithCGAT** [comment]
@dandepledge - Would you be able to share a subset of you SAM:

`LHEAD=$(samtools view -H <BAM> |wc -l); samtools view -h <BAM> |head -$(($LHEAD + 1000))) > <OUTPUT_BAM>`

 to help us work out what's going on here? You can email to me @: tss38@cam.ac.uk

**Comment by TomSmithCGAT** [comment]
Hi @dandepledge - I finally tracked this bug down! I believe originates from the different way featureCounts and HTSeq annotated reads which are not assigned to a gene. From what I understand, HTSeq uses just the `XF` tag and annotates each read with either the gene to which it is assigned, or a explanation as to why it was not assigned, e.g `__alignment_not_unique` ([doc here](http://htseq.readthedocs.io/en/release_0.9.1/count.html)). featureCounts uses the `XS`, `XN` and `XT` tags to describe the assignment status. number of targets, and target list.([doc here](https://rdrr.io/bioc/Rsubread/man/featureCounts.html)).

Currently, `umi_tools count` skips reads where the genes which match the `--skip-tags-regex` (default `^[__|Unassigned]`). These events are logged as "Gene skipped - matches regex". This works for HTSeq output where the gene tag and assigned tag is the same. However, for featureCounts, the assigned tag is different and for unassigned reads no XT tag is given. This should also results in the read being skipped by `umi_tools count` and the event logged as "Read skipped, no tag". However, some aligner also use the `XT` tag to describe the read alignment, e.g `XT:A:U`=unique and `XT:A:R`=repeat. Therefore, when using featureCounts, the unassigned reads retain their `XT` tag from the aligner, hence all those `R` genes. To get around this, I've introduced the `--assigned-tag` option. By defaults, this takes the same value as `--gene-tag` to support HTSeq-like output. For a featureCounts BAM, you can set this to `XS`. 

Would you mind installing from the [{TS}-DebugSkipCountUnassigned branch](https://github.com/CGATOxford/UMI-tools/tree/%7BTS%7D-DebugSkipCountUnassigned) and testing this option out for me. If it works, I'll release 0.5.4 with this option immediately.

**Comment by debjitray** [comment]
I have installed this branch. The command I use currently is.
umi_tools count --per-gene --assigned-tag=XS --gene-tag=XS --per-cell -I assigned_sorted.bam -S counts.tsv.gz

But it does not seem to work yet. Can you please explain what I am doing wrong here.

**Comment by TomSmithCGAT** [comment]
Hi @debjitray. Thanks for testing out the branch. Your gene names are contained in the `XT` tag so you need to include the option `--gene-tag=XT` rather than `--gene-tag=XS` as above. I'll rename the `--assigned-tag` option to `--assigned-status-tag` to make this clearer.
