### ISSUE TITLE
AttributeError: 'pysam.calignmentfile.AlignedSegment' object has no attribute 'reference_name'

### ISSUE THREAD

**Issue by ju-cheng** [CGATOxford/UMI-tools#199]
I had an error when using the umi_tools. The error is:
AttributeError: 'pysam.calignmentfile.AlignedSegment' object has no attribute 'reference_name'

I'm using pysam 0.8.3

Is it because of this specific version of pysam?

**Comment by TomSmithCGAT** [comment]
Hi @ju-cheng,  the attribute `reference_name` was introduced in version 0.8.4. See the `pysam` [release notes](http://pysam.readthedocs.io/en/latest/release.html) (relevant line copied below) .

'add reference_name and next_reference_name attributes to AlignedSegment'

**Comment by ju-cheng** [comment]
Thank you @TomSmithCGAT
