### ISSUE TITLE
ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by nsarode** [CGATOxford/UMI-tools#20]
Hi, I was trying out the dedup_umi script (using adjacency as the method) for a set of bam alignment files. The following message was displayed and I am not sure if this has something to do with the input or something else.

Traceback (most recent call last):
  File "/data/home/nsarode3/git_repos/UMI-tools/dedup_umi.py", line 1046, in <module>
    sys.exit(main(sys.argv))
  File "/data/home/nsarode3/git_repos/UMI-tools/dedup_umi.py", line 858, in main
    read_gn = random_read_generator(infile.filename, chrom=options.chrom)
  File "/data/home/nsarode3/git_repos/UMI-tools/dedup_umi.py", line 665, in __init__
    self.fill()
  File "/data/home/nsarode3/git_repos/UMI-tools/dedup_umi.py", line 679, in fill
    self.observed_umis, freq = zip(*self.umis.iteritems())
ValueError: need more than 0 values to unpack

Thanks,
neha

**Comment by IanSudbery** [comment]
Hi Neha,

Would you mind posting a couple of lines from your input lines? This could happen if the alogrithmn was having trouble finding the UMIs.

Ian
---

**Comment by nsarode** [comment]
Hi Ian,

Thanks for getting back to me. I am pasting below few lines from a file that gave me that error.

**Sequence input fastq file:**

@M01562:125:000000000-ALULG:1:1102:28320:10908_TGATAATTGA
GTGTCCCTATAGTGAGTCGTATTACGTCATCGGG
+
BBAABFFFFFFFDGGFGFEFGGHHGGHHGGHHGG
@M01562:125:000000000-ALULG:1:1105:13358:10552_CAGTCATACA
CCCATATTCAGACAGGATACCACGTGTCCCGCCCTACTCATCGAGCTCACAGCATGTGCATTTTTGTGTACGGGGCTGTCAGCTCGATGAGTAGGGCGGGACACGTGGTATCCTGTCTGAATATGGGGGGACCATCCTCCAAGGCTAAATACTCCTGACTGACCGATAGTGAACCCGCGTCGTGTAGGGAAAGAGTGTCCATATAGTGAGTCGTATTACGTCATCGTG
+
AABBBFFFFFBFGGFCGFGGGGHGHGFHHH?GGGGHHHHHHHFHGGGHHHHGFHGHGGGHFHHHGGHHHHHHGGGGFEFGGHHFFGCHHHG4FGHGHGGGF/FFG0CFGFHHHHHHGHGHHHHBGBAC@-BF.ABBFFFFFFFEEFFFFBFBFBFBBFFEFFFFAF-@D/FFFFEBFFFFFFDFFFFFFFF?FFF/FBFFFFFFFFFBFFFFFEFFFF/A.;?F/B9.

**Alignment file:**
M01562:125:000000000-ALULG:1:1102:28320:10908_TGATAATTGA	4	*	0	0	*	*	0	0	GTGTCCCTATAGTGAGTCGTATTACGTCATCGGG	BBAABFFFFFFFDGGFGFEFGGHHGGHHGGHHGG	YT:Z:UU
M01562:125:000000000-ALULG:1:2114:4308:16268_GCGCAAACTC	4	*	0	0	*	*	0	0	GATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTCCCTATAGTGAGTCGTATTACGTCATCGTG	BBABBBBBBFFFCFEGGGGGGGGHHHGHHHHHFGGH3F5EDGGHHHGA1BFHFCFAAAGBAA	YT:Z:UU
M01562:125:000000000-ALULG:1:2109:13048:18284_GAAGCAGAGT	4	*	0	0	*	*	0	0	AAATACTCCTGACTGACCGATAGTGAACCTCGCGTCGTGTAGGGAAAGAGTGTTCCTATAGTGAGTCGTATTACGTCATCGTG	BBBBBFDDFDCFGFGGGGGGGGGHHHHHHHHGGGGGGEFHHGFGHHHHHHBGGEGGHHHHH5GFHGGE?F3CG4F2B114B?E	YT:Z:UU
M01562:125:000000000-ALULG:1:1105:13358:10552_CAGTCATACA	4	*	0	0	*	*	0	0	CCCATATTCAGACAGGATACCACGTGTCCCGCCCTACTCATCGAGCTCACAGCATGTGCATTTTTGTGTACGGGGCTGTCAGCTCGATGAGTAGGGCGGGACACGTGGTATCCTGTCTGAATATGGGGGGACCATCCTCCAAGGCTAAATACTCCTGACTGACCGATAGTGAACCCGCGTCGTGTAGGGAAAGAGTGTCCATATAGTGAGTCGTATTACGTCATCGTG	AABBBFFFFFBFGGFCGFGGGGHGHGFHHH?GGGGHHHHHHHFHGGGHHHHGFHGHGGGHFHHHGGHHHHHHGGGGFEFGGHHFFGCHHHG4FGHGHGGGF/FFG0CFGFHHHHHHGHGHHHHBGBAC@-BF.ABBFFFFFFFEEFFFFBFBFBFBBFFEFFFFAF-@D/FFFFEBFFFFFFDFFFFFFFF?FFF/FBFFFFFFFFFBFFFFFEFFFF/A.;?F/B9.	YT:Z:UU

**Comment by TomSmithCGAT** [comment]
Hi Neha. Apologies for the delay. All those reads are unmapped. In all cases the Sam flag (column 2) = 4, and there's no alignment information in the following columns. Could you first check you have mapped reads in your bam:

    samtools view -f4 -c BAMFILE

If that returns 0, then the bamfile doesn't contain any mapped reads

**Comment by nsarode** [comment]
Hi Tom,
No worries about the delay. I ran the command on the bam file I pasted above and it returned '4' . But you are correct, the "ValueError: need more than 0 values to unpack" error came only for those files where no reads were mapped (checked back on each file).

Is there any manual or wiki for UMI that I could refer to instead of bugging you or Ian with silly problems like these ?

Thanks,
Neha

**Comment by TomSmithCGAT** [comment]
Hi Neha. You can run either script with the "--help" options to get the documentation. We don't have a manual right now but the  It sounds like you might need to return to the mapping stage though if you have bamflies without any aligned reads.

**Comment by nsarode** [comment]
Yeah, am working on sorting that right now.

Thanks for your help !
