### ISSUE TITLE
Paired-end reads group with --read-length do not take R2 length into account

### ISSUE THREAD

**Issue by nrosewick** [CGATOxford/UMI-tools#206]
Hi,

I want to group reads based on UMI, alignment position and read length. I've paired-end data.
So I use this command to group my reads :

`python $umitools/group.py -I sorted.bam --paired --read-length --edit-distance-threshold=1  --group-out=groups.tsv -L stats.txt`

When I check the groups.tsv file and extract reads from the same group I found that R1 reads have the same UMI, the same alignment position and the same length. **But** when I check the associated R2 reads they have same UMI and alignment positions but do not have the same length. 

Example for a group with 7 reads: 

R1 reads
```
[1] CTAGCGGCCAGGAGAGACCAGATCGGAAGAGCGCGAACTCCCGTC
[2] CTAGCGGCCAGGAGAGACCAGATCGGAAGAGCGCGAACTCCCGTC
[3] CTAGCGGCCAGGAGAGACCAGATCGGAAGAGCGCGAACTCCCGTC
[4] CTAGCGGCCAGGAGAGACCAGATCGGAAGAGCGCGAACTCCCGTC
[5] CTAGCGGCCAGGAGAGACCAGATCGGAAGAGCGCGAACTCCCGTC
[6] CTAGCGGCCAGGAGAGACCAGATCGGAAGAGCGCGTAATGTGCTG
[7] CTAGCGGCCAGGAGAGACCAGATCGGAAGAGCGCGTAATGTGCTG
```

R2 reads
```
    aln 
[1] GGTCTCTCCTGGCCGCTAG-------------------------------
[2] GGTCTCTCCTGGCCGCTAGCTGTCTCTTATACACTCTGACGCTGCCGACG
[3] GGTCTCTCCTGGCCGCTAG-------------------------------
[4] GGTCTCTCCTGGCCGCTAG-------------------------------
[5] GGTCTCTCCTGGCCGCTAG-------------------------------
[6] GGTCTCTCCTGGCCGCTAG-------------------------------
[7] GGTCTCTCCTGGCCGCTAG-------------------------------
```
the second R2 read has a different length. How can I tell UMI-tools to take R2 length also into account.

Thanks

**Comment by IanSudbery** [comment]
Hi,

Currently we have no way of taking the length of red 2 into account because that would mean having simulataneous access to a read and its mate at the same time. Unfortunately that is not the case: we do not have access to mates when we reprocess reads and we get the mapping position of read2 from read1s information. 

What is your experimental design? read length was initially included for people doing short RNA work where reads might be different length do to the very short fragments used. In most situations, I wouldn't think of the read length as being informative.

**Comment by nrosewick** [comment]
Hi Ian,
My goal is to use UMI-tools to group paired reads and then compute a consensus read for each group (merge PCR duplicates). So for me I need to group paired reads originating from the same DNA fragment thus same UMI (encoded in R2 in my experiment), same R1 alignment start, same R2 alignment start, same R1 length and same R2 length.

For now I use two UMI-tools group separately on R1 and R2. In summary I align R1 and R2 separately with bwa, then use umitools group on each bam to have two groups.tsv. I then post-process these two group files in R to output a final group file. Works fine for me but may be interesting to have such feature in umi-tools (FYI great tools).

**Comment by IanSudbery** [comment]
So I would question your assumption that two reads with the same outer coordinates (i.e. read1 start and read2 start) and the same UMI, but different lengths were from different fragments. I feel like the most likely explaination for two pairs with the same outter coords and the same UMI, but different read lengths is differential quality trimming.

**Comment by nrosewick** [comment]
I've a last question : If I leave out the --read-length option out, will the reads from the same group starts at the same position. So all R1 starts at the same position, and all R2 starts at the same position. And R1-R2 length can be different. Am I right ?

**Comment by IanSudbery** [comment]
Just to be clear - if you run in `--paired` we will look for reads that have the same R1 start and the same R2 start. The lengths of R1 and R2 can be different (without `--read-length`) BUT the length from the start of R1 to the start of R2 will be the same.

**Comment by TomSmithCGAT** [comment]
I'm closing this issue due to low activity
