### ISSUE TITLE
Q: Collapsing UMI's without using gene or coordinate information.

### ISSUE THREAD

**Issue by gitbuckley** [CGATOxford/UMI-tools#207]
My goal is to deduplicate UMI's within each cell barcode group, without first aligning the reads and making use of gene annotations. My analysis depends on using multimapping reads which makes gene/coordinate based deduplication problematic. In other words, I want reads with equivalent UMIs that occur in distinct cells to not be collapsed, but reads with equivalent UMIs that also share equivalent cell barcodes to be collapsed. It this possible with UMI-tools? It seems the "group" command relies heavily on genomic coordinates and/or gene tags.

**Comment by TomSmithCGAT** [comment]
Hi @gitbuckley. Can I just check that want to do is deduplicate using the cell barcode (CB) and UMI only? If so, I'm afraid this isn't currently possible within UMI-tools.
