### ISSUE TITLE
running UMI tools from the command line

### ISSUE THREAD

**Issue by annamarialara** [CGATOxford/UMI-tools#208]
Hi I am trying to install UMI_tools. Pip didn't work so I followed these instructions:

$ wget https://github.com/CGATOxford/UMI-tools/archive/master.zip
$ unzip master.zip
$ cd UMI-tools-master
$ python setup.py install --user

Which ran fine but then I don't seem to able to find any executable as in I am unsure how to now run umi-tools from the command line without using python.

tried simple thinks like umi_tools --help ect. but this won't run (returns command not found)
I also downloaded the UMI-tools-0.5.1 package in the same way but this is the same problem-not sure if there is any difference...

I tried as suggested in the installation guide:
$ nosetests tests/test_umi_tools.py 

which ran but returned 33 failures.

Could you perhaps advise on how to run umi_tools from the command line after the installation ? Thanks a lot!

**Comment by IanSudbery** [comment]
Hi,

I  where setuptools puts the binaries depends on your environment, but I think the default location is `~/.local/bin`. You will need to make sure that this location is on your `$PATH` . e.g.:

```
$ export PATH=~/.local/bin:$PATH
```

**Comment by annamarialara** [comment]
Thank you Ian, I had PATH set and exported for python and other things but seems like I did not have that one trivial location in there so it works now :)
