### ISSUE TITLE
Allow barcode fasta to guide cell barcode extraction

### ISSUE THREAD

**Issue by aarzalluz** [CGATOxford/UMI-tools#209]
Hi,

I am using UMI-tools for de-multiplexing of single-cell data generated from a 96-well, barcoded plate, also including UMIs. So far I've had no issues, but I would like to give you some input, in case you may find it useful.

As our cells were sorted into the plates, we decided that sorted population would be represented in each plate, to account for batch effects. I would say this will become common practice in future single-cell experiments, although it makes correct de-multiplexing essential to associate cell types with expression data... Luckily, we had access to the sequences of the cell barcodes that are used in library prep.

Maybe I have missed it, but it seemed to me that this information could not be input into UMI-tools to guide barcode extraction. When I obtained the expression matrix from our first plate, I compared the barcodes estimated by UMI-tools with the sequences provided by the company. The result is overall correct, except for two wells where the software seems to have misinterpreted the barcode, and no match is found with the true barcodes. Since this is not a significant proportion of my cells, it will not a big interpretability issue, however, I still wanted to suggest making the option to input a fasta file of barcodes (when available) as an enhancement.

Cheers,

Ángeles

**Comment by IanSudbery** [comment]
Dear Ángeles,

If I understand you correctly, you would like to be able to provide extract
with a list of the known cell barcodes. If this what you mean then we do
indeed already offer this possibility via the whitelist and
filter-cell-barcodes or correct-cell-barcodes options to extract.

Am I understanding correctly?

Ian

**Comment by aarzalluz** [comment]
Hi, Ian, and thank you for your quick reply! Yes, that is what I meant. I was not aware that this was already possible, I have not been able to find this explicitly in the documentation or on your single-cell tutorial. Could you elaborate a bit more on how I would go about this? Like I said, it is a minor thing, because UMI-tool is in general terms very successful in predicting the correct barcodes. But I still would like to have that option in the future.

Thanks,

Ángeles

**Comment by IanSudbery** [comment]
So in the tutorial we use `umi_tools whitelist` to generate a list of valid barcodes, which is stored in a file (here called `whitelist.txt`) and passed to `umi_tools extract` using the `--whitelist` option.

While in this case we generated the whitelist file from the data, the file itself is just a list of acceptable barcodes, one on each line. If you also pass `--filter-cell-barcode` then only reads that have one of the whitelisted barcodes will be retained. 

If you add a second column to your whitelist file (seperated from the first by a tab) which contains a comma separated list of barcodes and supply the `--correct-cell-barcode`, then any barcodes in the second column will be corrected to those in the first.  However, our investigations suggest this usually does more harm than good. 

This is explained in the help to `extract` (`umi_tools extract --help`)

**Comment by aarzalluz** [comment]
I did think of this, however, I wanted to maximize the number of reads per cell using the  exploration of potential errors in the barcodes you perform in the whitelist tool. I thought that if I provided my own barcode list, I wouldn't benefit from this, since manually providing a list of barcodes to correct, as you said, doesn't seem like a good option. 

Do you therefore advise against accepting the barcodes in the second column of the generated whitelist file? Also, I thought it would be useful to be able to only accept barcodes (in the second column of the generated whitelist) when they are supported by a sufficiently high number of reads, but maybe I'm wrong about this?

**Comment by IanSudbery** [comment]
When we looked into it we found that accepting barcodes 1 error from the whitelist generally worstened performance: there is a real danger of merging cells.  But this was with non-preknown barcode list. Its probably better if you know the correct barcodes.

In general, I would say that barcodes not on your list, but with high counts (could be a real cell) present more of a danger than ones with low counts (which are probably due to sequencing errors).

We are actively working on the best way to proceed here.

**Comment by aarzalluz** [comment]
Thanks for your very useful input, Ian, I have all the information I need now. I'll stay posted on future info about barcode correction. Regarding this, maybe a filtering option based on what you just said about barcode correction based on read counts would be useful. 

In the meantime, I believe including some of the info on this thread (how to provide known barcodes, and whether to correct them or not) in your single-cell tutorial could be helpful to future users. They definitely were for me :)
