### ISSUE TITLE
Error in help message for "extract"

### ISSUE THREAD

**Issue by hy09** [CGATOxford/UMI-tools#211]
Hi,
Thanks for the great tool!
It seems like there is a minor yet important typo in the help message of the "extract" method. 

"For example if the discard group above was specified as below this would enable matches with up to 2 errors in the discard_1 group.
       (?P<discard_1>GAGTGATTGCTTGTGACGCCTT{s<=2})
"

The pattern should be:
 (?P<discard_1>GAGTGATTGCTTGTGACGCCTT){s<=2}

To end users who are not familiar with the regex module this may lead to mistakes. 

Thanks!

**Comment by TomSmithCGAT** [comment]
Hi @hy09 - This isn't a typo - The text states this is how one would change (just) the discard group in the pattern above this sentence in the help text.

The full pattern is:
(?P<cell_1>.{8,12})(?P<discard_1>GAGTGATTGCTTGTGACGCCTT)(?P<cell_2>.{8})(?P<umi_1>.{6})T{3}.*

so here we are referring to changing from
(?P<discard_1>GAGTGATTGCTTGTGACGCCTT) to (?P<discard_1>GAGTGATTGCTTGTGACGCCTT{s<=2})

**Comment by hy09** [comment]
Hi Tom,
Thanks for the reply. Sorry I didnt make myself clear. Maybe its a version
issue but in my case, I had to write the pattern like
(?Psequencetodiscard){s<=1} for the fuzzy matching to work in regex.match.
Its the position of the parenthesis.

**Comment by TomSmithCGAT** [comment]
Hi @hy09 - You're absolutely correct. After some manual testing I can confirm that inclusion of the `{s<=2}` inside the parentheses for the group causes the fuzzy matching to be applied to just the final base, not the whole string of bases. This is an oversight on my behalf. I'll rectify the documentation directly on the master branch now!

Thanks greatly for persisting in spite of my insistence this wasn't a typo!
