### ISSUE TITLE
STAR --outFilterMultimapNmax and --outSAMunmapped options.

### ISSUE THREAD

**Issue by gresteban** [CGATOxford/UMI-tools#214]
Hello,

In your single cell tutorial for UMI-tools, STAR option `--outFilterMultimapNmax` is set to `1` in order not to allow multimapping reads. Is there a reason to make it advisable or even mandatory to set this option to `1`? Or it's a matter of choice if we want to take into account multimapping reads or not? In the case that we allow for multimapping reads, how does UMI-tools deals with them? According to my tests, I can see a difference in the final UMI counts (although very small), so I don't think UMI-tools just discards them.

Also, `--outSAMunmapped` defaults to `None`. Setting it to `Within` doesn't make a difference according to my tests. So, there's no harm in keeping the unmapped reads in the output .sam/.bam file, UMI-tools ignores them. Am I right?

Thanks for your time.

**Comment by IanSudbery** [comment]
Hi,

Multimapping is indeed a matter of choice. However, be aware that UMI-Tools basically makes no effort to deal with multimappers. Thus if a single read maps to two different places, UMI-Tools will treat these as entirely independent as though they came from two different reads.

You are right that keeping the unmapped reads or not has no downstream effect as unmapped reads are discarded by UMI-Tools. 

Hope this helps.

**Comment by gresteban** [comment]
It certainly does. Thanks a lot for the clarification.
