### ISSUE TITLE
umi_tools counts: MemoryError

### ISSUE THREAD

**Issue by romanhaa** [CGATOxford/UMI-tools#219]
Hi again!

I'm having some issues with `umi_tools counts` since it fails for all my four samples with the same error: `MemoryError`. It always happens after ~80 million reads which is about 1/3 to 1/2 of the total read count in each sample.

Here are the command I ran and the detailed error message:

```
umi_tools count --per-gene \
--gene-tag=XT \
--per-cell \
--wide-format-cell-counts \
--error=S2/molecule_count/molecule_count.stderr \
--stdin S2/featureCounts/featureCounts.sorted.bam \
--stdout S2/molecule_count/counts_wide.tsv
# output generated by count --per-gene --gene-tag=XT --per-cell --wide-format-cell-counts --error=S2/molecule_count/molecule_count.stderr --stdin S2/featureCounts/featureCounts.sorted.bam --stdout S2/molecule_count/counts_wide.tsv
# job started at Thu Dec 14 14:57:09 2017 on modhep-n4 -- 26cd84ac-03ee-4044-a48c-47c54697af29
# pid: 24086, system: Linux 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3~bpo70+1 (2015-08-08) x86_64
# cell_tag                                : None
# chrom                                   : None
# compresslevel                           : 6
# gene_tag                                : XT
# gene_transcript_map                     : None
# get_umi_method                          : read_id
# ignore_umi                              : False
# in_sam                                  : False
# log2stderr                              : False
# loglevel                                : 1
# mapping_quality                         : 0
# method                                  : directional
# paired                                  : False
# per_cell                                : True
# per_contig                              : False
# per_gene                                : True
# random_seed                             : None
# short_help                              : None
# skip_regex                              : ^[__|Unassigned]
# stderr                                  : <open file 'S2/molecule_count/molecule_count.stderr', mode 'w' at 0x7f360bd9ef60>
# stdin                                   : <open file 'S2/featureCounts/featureCounts.sorted.bam', mode 'r' at 0x7f360bd9eed0>
# stdlog                                  : <open file '<stdout>', mode 'w' at 0x7f3657b51150>
# stdout                                  : <open file 'S2/molecule_count/counts_wide.tsv', mode 'w' at 0x7f3622492e40>
# subset                                  : None
# threshold                               : 1
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# umi_sep                                 : _
# umi_tag                                 : RX
# wide_format_cell_counts                 : True
2017-12-14 15:00:34,103 INFO Parsed 1000000 input reads
2017-12-14 15:00:38,992 INFO Parsed 2000000 input reads
2017-12-14 15:00:44,295 INFO Parsed 3000000 input reads
2017-12-14 15:00:48,415 INFO Parsed 4000000 input reads
...
2017-12-14 15:39:24,837 INFO Parsed 80000000 input reads
2017-12-14 15:39:28,099 INFO Parsed 81000000 input reads
2017-12-14 15:40:44,052 INFO Parsed 82000000 input reads
2017-12-14 15:40:48,885 INFO Parsed 83000000 input reads
2017-12-14 15:40:53,651 INFO Parsed 84000000 input reads
Traceback (most recent call last):
  File ".../umi_tools", line 11, in <module>
    sys.exit(main())
  File ".../lib/python2.7/site-packages/umi_tools/umi_tools.py", line 59, in main
    module.main(sys.argv)
  File ".../lib/python2.7/site-packages/umi_tools/count.py", line 154, in main
    index='gene', columns='cell')  # pivot
  File ".../lib/python2.7/site-packages/pandas/core/reshape/pivot.py", line 160, in pivot_table
    table = table.sort_index(axis=1)
  File ".../lib/python2.7/site-packages/pandas/core/frame.py", line 3265, in sort_index
    convert=False, verify=False)
  File ".../lib/python2.7/site-packages/pandas/core/internals.py", line 4011, in take
    axis=axis, allow_dups=True)
  File ".../lib/python2.7/site-packages/pandas/core/internals.py", line 3893, in reindex_indexer
    fill_tuple=(fill_value,))
  File ".../lib/python2.7/site-packages/pandas/core/internals.py", line 3973, in _slice_take_blocks_ax0
    fill_tuple=None))
  File ".../lib/python2.7/site-packages/pandas/core/internals.py", line 1042, in take_nd
    allow_fill=False)
  File ".../lib/python2.7/site-packages/pandas/core/algorithms.py", line 1467, in take_nd
    out = np.empty(out_shape, dtype=dtype)
MemoryError
```

I tried running the job with more memory but it failed anyway, even though I gotta admit that I'm not 100% sure the memory specification worked.

The input BAM is ~8.4 GB large, so actually not that gigantic.

Anybody an idea if this is a problem on my end or some kind of bug?

**Comment by TomSmithCGAT** [comment]
Hi @romanhaa. `count` is actually a pretty memory efficient command since we only need to keep track of the UMI tallies as we parse the reads. 

The error occurs after all the reads have been parsed and the read counts are pivotted from a long format to a wide format (line 154 in `count`). You can check this yourself by leaving out the `--wide-format-cell-counts` option. There should be a more memory efficient way to pivot the data here so I'll take a look into this

BTW - the # reads "parsed" according to the log only includes those which passed all the filters (mapped and gene assigned) which is why it appeared that you had only parsed 1/3-1/2 of the reads. I'll update the logging info to make this clearer. Had you not received the error, the next step would have been to log the number of reads at each stage in the filtering process which should sum to the total number of input reads. Again, if you run without the `--wide-format-cell-counts` option, you should see this information in the log.

**Comment by romanhaa** [comment]
Ah, that makes sense. I changed a couple of parameters but didn't think that `--wide-format-cell-counts` could be the problem. Anyway, I can confirm that running it without the wide format works fine!

Anyway, thanks for the support! I'm looking forward to seeing this work in a future release :) Until then I'll work with the other format.

**Comment by TomSmithCGAT** [comment]
Hi again @romanhaa. I've pushed an update to the [{TS}-ReduceMemoryUsageForWideFormatCounts branch](https://github.com/CGATOxford/UMI-tools/tree/%7BTS%7D-ReduceMemoryUsageForWideFormatCounts) which should reduce the memory requirement to output the data in a wide format. If you'd like, you can test this out by installing from this branch. Alternatively, you can wait until the release of 0.5.2 (hopefully by the end of the week) which will include this update.

**Comment by romanhaa** [comment]
Great work @TomSmithCGAT! I tested the branch and it works now. I actually manage my environments through conda because of the integration in snakemake. As soon as the update will be pushed to conda I'll implement it.

Thanks again for the fantastic support!

**Comment by TomSmithCGAT** [comment]
Glad to hear the branch fixes the problem. We'll release an update via conda very soon.

**Comment by TomSmithCGAT** [comment]
Hi @romanhaa - 0.5.3 is now available through `conda`
