### ISSUE TITLE
Split CBC/UMI across paired-end reads causing (directional) problems 

### ISSUE THREAD

**Issue by bdoughty** [CGATOxford/UMI-tools#220]
I have reads with the following structure:
R1:
NNNNNNNNNNXXXXXXXXXX...
[10bp UMI followed by actual read]
R2:
CCCCCCCCCCCC
[just 12bp CBC]

If I try to run: 
umi_tools extract --stdin=[R1.fastq.gz] --read2-in=[R2.fastq.gz] --bc-pattern=NNNNNNNNNN --bc-pattern2=CCCCCCCCCCCC --stdout=[R1.extracted.fastq.gz] --read2-out=[R2.extracted.fastq.gz] 

I get an "IndexError: string index out of range" exception. 

However, if I swap R1 and R2 (and bc-pattern and bc-pattern2) and run:
umi_tools extract --stdin=[R2.fastq.gz] --read2-in=[R1.fastq.gz] --bc-pattern=CCCCCCCCCCCC --bc-pattern2=NNNNNNNNNN --stdout=[R2.extracted.fastq.gz] --read2-out=[R1.extracted.fastq.gz]

the program finishes running and returns R1 reads with a 12bp CBC and 10bp UMI in the name, but I lose the first two XX of the actual read. (They just disappear and aren't appended to the name.) Without digging into the code, can you recommend any fixes beyond manually prepending the CBC from R2 onto R1 (which would take a long time for big files)?

Thanks!

[Edited] I guess my question is, what is the best way for dealing with split barcodes (both CBCs and UMIs) across paired-end reads? Am I forgetting some flag?

**Comment by TomSmithCGAT** [comment]
Hi @bdoughty. There were some bugs in the 0.5.1 release (See #201 and #221) which may explain your error. We should get the patches out in version 0.5.2 before the end of the week but it'll be quicker for you to reinstall from the master branch if you want to check now.

**Comment by bdoughty** [comment]
Reinstalling from master worked for me, thanks!
