### ISSUE TITLE
Market Exchange Formats for expression matrix output

### ISSUE THREAD

**Issue by dbrg77** [CGATOxford/UMI-tools#223]
Hello,

Maybe I missed this, but it seems the current expression matrix output from the "count" function can only be either the default or the wide format. Is it possible to add an option to output the expression matrix as Market Exchange Formats like the ones from cellranger, so that some downstream analysis packages can take directly from that?

Thank you very much.

Regards,
Xi

**Comment by TomSmithCGAT** [comment]
Hi Xi. I've not got any experience of working with Matrix Market exchange formats but this certainly seems like a reasonable output to support. I'll take a look into this.

**Comment by dbrg77** [comment]
Thanks very much, Tom.

In case this helps: https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/matrices

**Comment by TomSmithCGAT** [comment]
Closing due to low activity. I'll labelled this so we can find it again when discussing updates.
