### ISSUE TITLE
Update PyPi version to 0.5.2

### ISSUE THREAD

**Issue by cbrueffer** [CGATOxford/UMI-tools#226]
Would it be possible to update umi-tools on PyPi to 0.5.2? We currently use it as the source to build the corresponding bioconda package.

Thanks!

**Comment by TomSmithCGAT** [comment]
Oops. Forgot to do this in the rush to get things finished off before the Christmas break. Thanks for maintaining `umi_tools` on `bioconda`. Much appreciated!
