### ISSUE TITLE
issues with --wide-format-cell-counts

### ISSUE THREAD

**Issue by kevin199011** [CGATOxford/UMI-tools#227]
Hi, I was using umi_tools count to count the number of UMIs per gene/per cell. However, when I use wide-format-cell-counts option to output matrix, I get fewer cells than without using this option (without: 93 cells; with:29 cells). Could you please let me know how to solve this issue? Thank you!

Kevin

**Comment by TomSmithCGAT** [comment]
Hi Kevin. Thanks for spotting this. I introduced a bug in 0.5.2 which wasn't picked up in the testing. I'll rectify today and release 0.5.3.

**Comment by TomSmithCGAT** [comment]
This should have been rectified in `0.5.3` - available here and via `pip` and `conda`. If this update doesn't solve this issue, please re-open
