### ISSUE TITLE
In `count`, the default for `skip_regex` sporadically removes legitimate genes

### ISSUE THREAD

**Issue by ekernf01** [CGATOxford/UMI-tools#231]
In `umi_tools count`, the argument `skip_regex` defaults to `^[__|Unassigned]`, which matches any gene starting in U or any gene starting in `n`, `a`, `s`, et cetera. I suggest you replace it with `^(__|Unassigned)`, which only matches `__` or `Unassigned`.

**Comment by TomSmithCGAT** [comment]
Thanks for spotting a very stupid bug @ekernf01!

@IanSudbery - I've rectified this on the master branch and will update the `conda` and `pip` releases shortly. I'll leave this open until I do so as a reminder

**Comment by ekernf01** [comment]
Thanks for the speedy response! I'm really enjoying working with umitools so far.
