### ISSUE TITLE
question on pre dedup sorting for pair-end reads

### ISSUE THREAD

**Issue by e-manduchi** [CGATOxford/UMI-tools#233]
Quick question: in the doc it states to sort and index the bam file prior to using umi_tools dedup. Should samtools sort used with default options in the case of paired-end reads? I guess it could happen that in this case some paired reads won't be written one after the other in the resulting bam.
Thanks.

**Comment by IanSudbery** [comment]
Yes, thats right. Read pairs do not need to be adjacent in the bamfile for the deduping to work.

**Comment by e-manduchi** [comment]
Thanks for confirming.
