### ISSUE TITLE
Error running whitelist

### ISSUE THREAD

**Issue by garrett-parker** [CGATOxford/UMI-tools#234]
I am following the tutorial for single cell and I received an error trying to run the following command:

umi_tools whitelist --stdin hgmm_100_R1.fastq.gz \ --bc-pattern='(?P<cell_1>.{16})(?P<umi_1>.{10})' \ --extract-method=regex \ --set-cell-number=100 \ --log2stderr > whitelist.txt

examining the whitelist.txt file showed ERROR Must supply --bc-pattern for single-end

I'm not sure how to solve this issue, can you please help?

**Comment by IanSudbery** [comment]
Hi Garrett, 
Those `\` charactors are line continuation characters. They were used in the tutorial to make the command fit within a page width. However, they must not be followed by a space to function. Thus this:

```
umi_tools whitelist --stdin hgmm_100_R1.fastq.gz \
 --bc-pattern='(?P<cell_1>.{16})(?P<umi_1>.{10})' \
 --extract-method=regex \
 --set-cell-number=100 \
 --log2stderr > whitelist.txt
```
(note no spaces after the `\` characters. )
And this should also work:

```
umi_tools whitelist --stdin hgmm_100_R1.fastq.gz --bc-pattern='(?P<cell_1>.{16})(?P<umi_1>.{10})'  --extract-method=regex  --set-cell-number=100  --log2stderr > whitelist.txt
```
(single line no, `\`'s)


Unfortunately the tutorial DOES contain spaces after the `\`. I'll fix that.
