### ISSUE TITLE
installation using pip

### ISSUE THREAD

**Issue by sunnyyakima** [CGATOxford/UMI-tools#236]
Hi,
I installed umi_tools using pip, and didn't get any error. but it seems it was installed as a python package (I can import it in python console ), not a command line program (cannot run _umi_tools extract_ ...).
Could you help to figure it out? thanks

Leo

**Comment by IanSudbery** [comment]
Hi, if you installed using pip --user, the binaries have probably been
installed in ~/.local/bin. Do you have this on your $PATH?

**Comment by sunnyyakima** [comment]
got it, and solved.  Thanks for quick response!
