### ISSUE TITLE
question on using umi_tools for hybrid paired-end reads

### ISSUE THREAD

**Issue by e-manduchi** [CGATOxford/UMI-tools#237]
I have paired-end reads that are coming  from hybrid fragments. I assume this would not pose a problem for umi_tools. In other words if I run it with the --paired option I would want 2 UMIs to be considered as mapping to the same position only if BOTH their read 1 and read 2 locations are identical, independently of whether or not read 1 and read2 are on the same chr and, if on the same chr, independently of how distantly they map to.
Is this correct, or umi_tools should not be used in the scenario of hybrid paired-end reads?
Thanks for your attention.

**Comment by TomSmithCGAT** [comment]
Hi @e-manduchi. Currently `umi_tools` is not set up to handle chimeric read pairs (where one read aligns to one chr and the pair aligns to another chr). To identify possible duplicate read pairs, `umi_tools` uses the position of the first read and the template length, to obtain the end-to-end mapping position of the read pair. I'm not actually sure what the template length value will be for chimeric read pairs but it certainly wont be informative. I can't think of any way to use `umi_tools` to identify duplicate reads for this analysis unfortunately, but I'll leave this up here for now in case @IanSudbery has any ideas?

**Comment by e-manduchi** [comment]
Thank you for your response. 
Just to clarify, if the chimeric read pairs is made up of reads *on the same chromosome* will umi_tools be able to handle indipendently of how far these reads are, i.e. independently of how long the template is?
Regarding the situation of pairs on different chr, it would be great if there was a way to deal with that as well in a future release of the software.

**Comment by TomSmithCGAT** [comment]
Yes, it'll work for the read pairs on the same chromosome regardless of how long the template is. The chimeric read pairs on different chromosomes will cause some issues which aren't easily resolved in our current framework so I suspect this might not be supported for some time to come. I'll mark this issue as one to consider for the next major release but it may not make the list of priorities unfortunately.

**Comment by e-manduchi** [comment]
Thanks again.

**Comment by TomSmithCGAT** [comment]
Chimeric read pairs are now explicitly handled in UMI-tools, with the option `--chimeric-pairs=[discard/use/output]`. This is now available on the master branch and will be part of the next release. For more details, see #312.
