### ISSUE TITLE
isoform quantification with UMI-tools

### ISSUE THREAD

**Issue by ccshao** [CGATOxford/UMI-tools#238]
Hi, 

We are interested in obtaining the UMI counts for two isoforms with different 3'UTR. 
I got confused on the mapping strategy and `count` parameter. 
Here is what I thought:
- If the reads are **mapped to genome**
   Then there is no way to get the isoforms counts via `featurecount` and `count` in UMI-tools, am I right on this?

- If the reads are **mapped to transcriptome**
  - I should **NOT** generate a  **collapsed transcriptome**?
  - Instead, use `star` and `--quantMode TranscriptomeSAM`
     - umi_tools [COMMAND] --per-contig --per-gene --gene-transcript-map=[MAPFILE]
     - MAPFILE is a **transcript to transcript** map (`--sjdbGTFfile` is not needed anymore I think)

- If I directly build a **star index with transcriptome** and map reads to it, then how should I get UMI counts?

Thanks!

**Comment by ccshao** [comment]
Hi again, 

I tried the gene level summary with the dropseq data (GSE107122)
however, I got different number of genes in batches though same gtf is used:

> 
> Read 82896 rows and 2001 (of 2001) columns from 0.311 GB file in 00:00:05
> Read 86200 rows and 3001 (of 3001) columns from 0.484 GB file in 00:00:08
> Read 78210 rows and 2001 (of 2001) columns from 0.293 GB file in 00:00:05
> Read 82833 rows and 1993 (of 1993) columns from 0.309 GB file in 00:00:05
> Read 79331 rows and 2000 (of 2000) columns from 0.297 GB file in 00:00:05
> 
In above log, rows are genes and columns are cells (in wide format).
How umi count keep and discard genes?

**Comment by IanSudbery** [comment]
Hi There,

I would definitely recommend mapping to the transcriptome in this case. 

Either use a transcriptome index with STAR and map in the usual way.

Or use a genome index with STAR, but map using the `--quantMode TranscriptomeSAM` option, this will output the BAM file in transcriptome co-ordinates despite the index being a genome one.

Then use
`umi_tools count --per-contig --per-gene --gene-transcript-map=[MAPFILE] --stdin=[BAMFILE]`
where MAPFILE maps transcripts to genes.

**Comment by ccshao** [comment]
Thanks! I used the `--quantMode TranscriptomeSAM` to the sam file. I guess `--gene-transcript-map=[MAPFILE]` is not necessary if I am not interested in getting the gene level summary?

**Comment by IanSudbery** [comment]
Thats correct. I don't think you need `--per-gene` either, just `--per-contig`.

**Comment by ccshao** [comment]
Thanks!
