### ISSUE TITLE
Extract pattern format

### ISSUE THREAD

**Issue by royfrancis** [CGATOxford/UMI-tools#24]
In the help content for `umi_tools extract`, the explanation for pattern is a bit confusing. If Ns are random bases and Xs are UMIs, then Xs should be extracted for name and Ns must be reattached as read? If so, in the example below, GG should be added to the read name.

       --bc-pattern
       Use this option to specify the format of the UMI/barcode. Use Ns to
       represent the random positions and Xs to indicate the bc positions.
       Bases with Ns will be extracted and added to the read name. Remaining
       bases, marked with an X will be reattached to the read.

       E.g. If the pattern is NNXXNN,
       Then the read:

       @HISEQ:87:00000000 read1
       AAGGTTGCTGATTGGATGGGCTAG
       DA1AEBFGGCG01DFH00B1FF0B
       +

       will become:
       @HISEQ:87:00000000_AATT read1
       GGGCTGATTGGATGGGCTAG
       1AFGGCG01DFH00B1FF0B
       +

**Comment by IanSudbery** [comment]
Hi There,

The Xs refer to the sample barcode, not the UMI barcode. The UMI barcode is the "random bases". The necessity for this comes from labeling scheme used in several techniques, most commonly iCLIP, where the UMI is formed of several independent sub sequences - that pattern looks like:

UMI-UMI-UMI-Sample-Sample-Sample-Sample-UMI-UMI

for which we would input NNNXXXXNN for the --bc-pattern

 Other techniques do indeed embed a single UMI subsequence among the several other components. In that case a pattern of, say XXNNXX would be more appropriate. 

If your UMI is simply 6 bases on the start of the read, then you would use: NNNNNN as --bc-pattern

Hope this helps.

**Comment by royfrancis** [comment]
Aha. ok. Thanks. So Ns are UMI bases.
