### ISSUE TITLE
error allowed in fuzzy matching for cell barcode?

### ISSUE THREAD

**Issue by ccshao** [CGATOxford/UMI-tools#242]
The single cell tutorial introduced the fuzzying matching for the discard sequence, but is it allowed for 
cell barcodes as well for the version 0.5.3, like` (?P<cell_1>.{s<=2})`?

I read a thread in May, 2017 that fuzzy matching is not allowed, and wonder whether this has been changed.

**Comment by TomSmithCGAT** [comment]
Could you explain why you would want to use fuzzy matching with the cell barcode? In the example above the cell barcode is specified as being a single `.` which will match any character (except newline) and the fuzzy matching will allow up to two substitutions which seems odd?

**Comment by ccshao** [comment]
In our sequencing data we have a whitelist of 96 cell barcodes, and they are selected by maximuming hamming distance by my colledges. 
So we think it will make sense to keep cell barcodes which are different to known whitelist barcodes but within certain disances.

**Comment by TomSmithCGAT** [comment]
In that case, you can supply the whitelist to `umi_tools extract` like so `--filter-cell-barcode --whitelist=<WHITELIST.TSV>`. The text below is copied from the documentation (`umi_tools extract --help`)

```
Filtering and correcting cell barcodes
--------------------------------------

umi_tools extract can optionally filter cell barcodes
(--filter-cell-barcode) against a user-supplied whitelist
(--whitelist). If a whitelist is not available for your data, e.g
if you have performed droplet-based scRNA-Seq, you can use the
whitelist tool.

Cell barcodes which do not match the whitelist (user-generated or
automatically generated) can also be optionally corrected using the
--error-correct-cell option.

The whitelist should be in the following format (tab-separated):

    AAAAAA      AGAAAA
    AAAATC
    AAACAT
    AAACTA      AAACTN,GAACTA
    AAATAC
    AAATCA      GAATCA
    AAATGT      AAAGGT,CAATGT

Where column 1 is the whitelisted cell barcodes and column 2 is
the list (comma-separated) of other cell barcodes which should be
corrected to the barcode in column 1. If the --error-correct-cell
option is not used, this column will be ignored. Any additional columns
in the whitelist input, such as the counts columns from the output of
umi_tools whitelist, will be ignored.
```

**Comment by ccshao** [comment]
This is what I thought in the begining. However, currently such a list is not availalbe. I will try the 96 barcodes and waiting for the extened barcodes. 

Related to to the fuzzy matching, I have questions on indrop-like barcode extraction. 
In the data, the R1 reads is much like indrop, but with a few leading base pairs (it could no leading bp, or A,  or TC or GTA), i.e. 
`[_nothing_|A|TC|GTA][cell_1 8bp][discard_1 20bp][cell_2 8bp][umi 8bp]TTT`
then, would the following pattern works while tollerating leading base pairs:
`(?P<cell_1>.{8})(?P<discard_1>GAGTGATTGCTTGTGACGCCTT)(?P<cell_2>.{8})(?P<umi_1>.{8})T{3}.*`

or it could only find the reads with **0** bp before cell barcode 1?

In python, I think it is a `match` or `search` question.

**Comment by TomSmithCGAT** [comment]
`extract` uses a `match` so the above regex would need to start with `.*` in order to allow zero or more characters before the cell barcode

The documentation should be updated to make this clear.

**Comment by ccshao** [comment]
Thanks for quick reply! I have one more questions on the fuzzy matching syntax: will the group name 
appeared twice in  --bc-pattern and --bc-pattern2 cause problem in umi_tools?

For example:
```
                 --bc-pattern="(?P<cell_1>.{8})(?P<discard_1>ATCCACGTGCTTGAG){e<=2}(?P<cell_2>.{8})(?P<umi_1>.{8})T{3}.*" \
                  --bc-pattern2="(?P<cell_1>.{8})(?P<discard_1>.{6}).*" \

```
Here **cell_1** and **discard_1** appears twice but in `bc-pattern `and ` bc-pattern2`, respectively. Is this the correct way to write? or group name must be unique among patterns?

**Comment by ccshao** [comment]
Thanks so much for the online help!! We really appreciate this nice tool and are more confident with the 
parameters.
