### ISSUE TITLE
Value error when using dedup on bam file

### ISSUE THREAD

**Issue by garrett-parker** [CGATOxford/UMI-tools#243]
Hi,

I recently used umi_tools dedup successfully but now it won't seem to work for some reason I cannot figure out. When I run the command on my bam file it returns this error

Traceback (most recent call last):
  File "/u/home/g/garrettp/.local/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/u/home/g/garrettp/.local/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 59, in main
    module.main(sys.argv)
  File "/u/home/g/garrettp/.local/lib/python2.7/site-packages/umi_tools/dedup.py", line 146, in main
    raise ValueError("Input on standard in not currently supported")
ValueError: Input on standard in not currently supported

What does this error mean?

**Comment by TomSmithCGAT** [comment]
Hi @garrett-parker - Could you post you command please

**Comment by garrett-parker** [comment]
$ umi_tools dedup reads.simulated.bam reads.simulated.deduplicated.bam

**Comment by TomSmithCGAT** [comment]
Can I just confirm that
`$ umi_tools dedup -I reads.simulated.bam -S reads.simulated.deduplicated.bam`
works?

**Comment by garrett-parker** [comment]
Yes that accounts for the problem.

Thanks for your help.

**Comment by TomSmithCGAT** [comment]
Sorry for the non-informative error message!
