### ISSUE TITLE
UnboundLocalError: local variable 'read2_out' referenced before assignment

### ISSUE THREAD

**Issue by maximnorkin** [CGATOxford/UMI-tools#244]
Hi! I have a problem which I can not so far solve by myself. Once I run UMI extraction for pair-end sequencing I have a problem:

I run:
`$ umi_tools extract -I pair.1.fastq.gz --bc-pattern=NNNNNNNN \ --read2-in=pair.2.fastq.gz --stdout=processed1.fastq.gz \--read2-out=processed2.fastq.gz`
I get:
`UnboundLocalError: local variable 'read2_out' referenced before assignment`

What is the problem here? What do I do wrong? It worked perfectly for single end. Seems people overcome that problem by using global command, but it seems it can not be found in UNIX.

Thanks in advance
Maxim

**Comment by TomSmithCGAT** [comment]
@maximnorkin , I'm closing this issue now as I believe it has been resolved. Please re-open if needed
