### ISSUE TITLE
Nodes belonging to more than one cluster

### ISSUE THREAD

**Issue by jeremyadamsfisher** [CGATOxford/UMI-tools#247]
Hi developers,

I wanted to reach out. I have been studying the `get_connected_components_adjacency` method and I was wondering: what prevents a UMI from being clustered more than once?

I would have expected a line like the one indicated:

```
def _get_connected_components_adjacency(self, umis, graph, counts):
        ''' find the connected UMIs within an adjacency dictionary'''

        found = set()
        components = list()

        for node in sorted(graph, key=lambda x: counts[x], reverse=True):
            if node not in found: 
                component = breadth_first_search(node, graph)
                component.difference_update(found)  # <-----------------
                found.update(component)
                components.append(component)
        return components
```
Is this not an issue because the effect is typically too small? Or, perhaps, am I missing something more fundamental?

**Comment by TomSmithCGAT** [comment]
Hi @jeremyadamsfisher - Sorry for missing this issue.

The process of read grouping in `umi_tools` involves the following steps:

1. Build adjacency network
2. Identify clusters
3. Find groups

https://github.com/CGATOxford/UMI-tools/blob/c8ac0677e5c8b91c56128deb7273973776b3895d/umi_tools/network.py#L374-L377

The exact processes in each step are dependent on the clustering method specified (`--method`), hence `self.get_adj_list` etc above are set in `UMIClusterer.__init__`. 

When using `--method=adjacency`, the separate clusters identified can indeed contain the same UMI. However, when groups of UMIs are defined, each UMI can only exist in one group. The group method for adjacency (below)

**Comment by TomSmithCGAT** [comment]
Hi @jeremyadamsfisher - Sorry for missing this issue.

The process of read grouping in `umi_tools` involves the following steps:

1. Build adjacency network
2. Identify clusters
3. Find groups

https://github.com/CGATOxford/UMI-tools/blob/c8ac0677e5c8b91c56128deb7273973776b3895d/umi_tools/network.py#L374-L377

The exact processes in each step are dependent on the clustering method specified (`--method`), hence `self.get_adj_list` etc above are set in `UMIClusterer.__init__`. 

When using `--method=adjacency`, the separate clusters identified can indeed contain the same UMI. However, when groups of UMIs are defined, each UMI can only exist in one group. The group method for adjacency (below) keeps track of the `observed` UMIs to ensure this

https://github.com/CGATOxford/UMI-tools/blob/c8ac0677e5c8b91c56128deb7273973776b3895d/umi_tools/network.py#L276-L298
