### ISSUE TITLE
Run whitelist to suggest possible threshold without choosing one

### ISSUE THREAD

**Issue by romanhaa** [CGATOxford/UMI-tools#249]
Hi guys,

I'm using UMI-tools in the scRNAseq pipeline of our lab and found that preparing the right number of cells in each sample is probably the most common experimental problem in our experiments. Therefore, the whitelist function often fails and causes errors ("no local minima"). I designed my pipeline in a way that it first runs the whitelist step and then stops. I then inspect the plots, set a manual threshold and run whitelist again with `set-cell-number`. However, it would be nice if the whitelist could be used to just create the plots and suggest some thresholds if possible. This way I wouldn't get any errors which otherwise upsets the users.

Also, it would be useful to change the x-axis to logarithmic scale in the knee plot because sometimes (with too many barcodes plotted) I just see a vertical line for the first barcodes and then an almost horizontal line for the rest.

Thanks,
Roman

**Comment by TomSmithCGAT** [comment]
After a very long delay, we have now added a option (`--allow-threshold-error`) to allow `whitelist` to fail to select a threshold and exit without error. If combined with `--plot-prefix`, this will output the plots and table of possible thresholds for manual inspection. Note that `whitelist` will still try and identify the correct threshold but one can ignore the chosen threshold if desired.

This feature is available immediately from the master branch and will be made available in the next release.
