### ISSUE TITLE
umi_tools extract run error

### ISSUE THREAD

**Issue by royfrancis** [CGATOxford/UMI-tools#25]
I have paired end data (2 fastq files, 77 mil reads) and I have 8 nt UMI bases on the 5' end of the first fq file.

I have a shell script file with this content:
 
```Bash
newfilename="${1/_*/}"

cat "$1" | umi_tools extract \
--bc-pattern="NNNNNNNN" \
--read2-in="$2" \
--read2-out="$newfilename-um_2.fq" \
-L "umitools-extract.log" > "$newfilename-um_1.fq"
```
where  `$1` is the first fq file (fwd) and `$2` is the second fq file (rev). And run as `script.sh file_1.fq file_2.fq`. I get the below error after the script runs for a couple of minutes.
```
sbatch-umitools-extract.sh: line 42: 32582 Broken pipe             cat "$1"
     32583 Killed                  | umi_tools extract --bc-pattern="NNNNNNNN" --read2-in="$2" --read2-out="$newfilename-um_2.fq" -L "umitools-extract.log" > "$newfilename-um_1.fq"
```

Strangely, it works fine on a small test dataset (paired-end fastq) of 40 lines each. The output fq files show the UMIs have been correctly removed and added to the read name. But it doesn't work for my big dataset. I wonder if it is just a script syntax error or something else.

**Comment by IanSudbery** [comment]
Hi There,

I think this is almost certainy due to running out of memory - the "Killed" suggests that the job was killed by the OOM killer. The broken pipe comes from the fact that once the umi_tools process died, the cat had nowhere to send data. 

I'm going to have a look at why it might be using so much memory.

**Comment by royfrancis** [comment]
I had tried increasing the memory from 16GB to 48GB and I still get the same error.

**Comment by IanSudbery** [comment]
Hi Roy,

Can you try the code in [extract_memory](/CGATOxford/UMI-tools/tree/extract_memory) branch. It should reduce the memory usage from 100s of GB to 100s of MB for paired end files. 

Let me know if this fixes your problem.

**Comment by royfrancis** [comment]
Hi Ian,
This time, it worked, the run completed successfully without errors in 30 mins (74 mil reads paired-end). Available resources was 6 cores and 48gb RAM. This was reported from the job controller during the run:
`slurmstepd: Exceeded step memory limit at some point.`
which usually means that the job had exceeded the pre-allocated 48gb.

But on inspecting the job report, it seems like only a single core was used and RAM usage was low. Perhaps this may not be reliable. 

![run-profile](https://cloud.githubusercontent.com/assets/5083500/15407768/f012a39c-1e0c-11e6-9ca4-4962d6d2babf.png)

Is this application multi-threaded? Does it help to provide more cores?

**Comment by IanSudbery** [comment]
Glad that it works now. 

Currently the application isn't currently multithreaded. We might add multithreading at a later date, but it is not currently a priority.

**Comment by royfrancis** [comment]
Thanks for the quick fix.
