### ISSUE TITLE
documentation on stats file

### ISSUE THREAD

**Issue by e-manduchi** [CGATOxford/UMI-tools#250]
Hello,
can you please clarify the meaning of the fields reported in the *per_umi.tsv and the *per_umi_per_position.tsv files?
Thanks.

**Comment by TomSmithCGAT** [comment]
Apologies for the late reply. 

The *per_umi_per_position.tsv file details stats per UMI. The meaning of the columns is:
- times_observed_pre: How many positions was the UMI observed at?
- median_counts_pre: The median number of reads for this UMI across these positions
- total_counts_pre: Across all positions, how many reads had this UMI?
- median_counts_post,times_observed_post,total_counts_post: As above except after deduplication

Note a comparison between pre- and post-deduplication is somewhat complicated by the fact that some UMIs will be collapsed (error corrected) into other UMIs, hence the total counts for a UMI may increase post-deduplication. 

The *per_umi.tsv file simply tallys how many reads were observed per UMI per position.
