### ISSUE TITLE
Document that doesn't work with Python3

### ISSUE THREAD

**Issue by datakid** [CGATOxford/UMI-tools#251]
Increasingly Python3 is the default. My virtualenvs are now py3 by default. When installing umi_tools with py3 I get this error:

> Command "/config/binaries/umi-tools/0.5.3/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ghcq0cv2 https://files.pythonhosted.org/packages/1b/d2/22cde5ea9af055f81814f9f2545f5ed8a053eb749c08d186b369959189a8/wheel-0.31.0-py2.py3-none-any.whl#sha256=9cdc8ab2cc9c3c2e2727a4b67c22881dbb0e1c503d592992594c5e131c867107 https://files.pythonhosted.org/packages/8c/10/79282747f9169f21c053c562a0baa21815a8c7879be97abd930dbcf862e8/setuptools-39.1.0-py2.py3-none-any.whl#sha256=0cb8b8625bfdcc2d43ea4b9cdba0b39b2b7befc04f3088897031082aa16ce186 https://files.pythonhosted.org/packages/70/25/1e1521e6ce2cf78ff4a8b06fbc2cd513ce004ec337000eddfe016fdf3fc6/Cython-0.28.2-cp34-cp34m-manylinux1_x86_64.whl#sha256=85f7432776870d65639fed00f951a3c05ef1e534bc72a73cd1200d79b9a7d7d0 https://files.pythonhosted.org/packages/fc/1b/a1717502572587c724858862fd9b98a66105f3a3443225bda9a1bd16ee14/numpy-1.9.3-cp34-cp34m-manylinux1_x86_64.whl#sha256=bff36563f9d6a06a81ae232f49d2946c84c05e391a7dff057496033c79507860 https://files.pythonhosted.org/packages/02/64/c6c1c24ff4dbcd789fcfdb782e343ac23c074f6b8b03e818ff60eb0f937f/numpy-1.12.1-cp34-cp34m-manylinux1_x86_64.whl#sha256=4eac5f2f624c5e7eecbdb51395ff39a099c48cab607a158f16f288c6fe39a2b3 https://files.pythonhosted.org/packages/1b/ee/f65826b2880f67652c21326565b4c166c7cdb1019f84b82af65e625475cd/numpy-1.13.1-cp34-cp34m-manylinux1_x86_64.whl#sha256=838e48df3703c8747f355cd6386e0680b906a2f7b2bbd304e8a2d531692484ce" failed with error code 1 in None

You should document that umi_tools is a python2 only product.

**Comment by TomSmithCGAT** [comment]
Hi @datakid. `umi_tools` is indeed py3 compatible. How are you trying to install `umi_tools`? Could you please include the exact command you used.

**Comment by datakid** [comment]
```
virtualenv -p /usr/bin/python3.4 0.5.3-py3
source 0.5.3-py3/bin/activate
pip install -U pip setuptools
pip install umi_tools
```
I just recreated this exactly. On an up to date CentOS 7.4 with python3 installed.

**Comment by datakid** [comment]
No, I didn't have any of them installed because the installation instructions explicitly say `pip install umi_tools`. So that's what I did. I think that's a reasonable reading of the install instructions.

**Comment by datakid** [comment]
It's Pandas. Pandas requires py 27, 35, 36. No 34. Which is the default 3 in CentOS. I'll up to 36

**Comment by datakid** [comment]
python-devel (python36-devel) is also required for one of the dependencies. In Ubuntu that's python-dev (?python36-dev?)

**Comment by datakid** [comment]
It installs with Python 36 with some jiggling.
