### ISSUE TITLE
Novaseq bulk RNAseq with UMI

### ISSUE THREAD

**Issue by antgomo** [CGATOxford/UMI-tools#252]
Hi,

I am using a bulk paired-end RNAseq coming from NovaSeq sequencing run with UMIs in order to avoid duplicates related problems, the point is that I have i5 and i7 index, and UMI is 9bp and is located after i7 index.

I am completely newbie in the UMIs field, so I guess that I have to follow using your tool is

1. UMI tools extract 
  2.  STAR to align
   3. UMI tools dedup to remove duplicates
 4. Summarize counts with featurecounts

The thing is that I am very lost in step 1, in the examples that i read, the UMI is at the beginning of the read, theoretically the index are removed form the fastqs, so i assumed the UMI is at th beginning

Thanks in advance

**Comment by IanSudbery** [comment]
Hi there

Do you mean that the UMI is in the index read?

**Comment by TomSmithCGAT** [comment]
I'm closing this issue due to low activity.
