### ISSUE TITLE
Add flag for --temp-dir

### ISSUE THREAD

**Issue by ihuerga** [CGATOxford/UMI-tools#254]
Utilities.py#getTempFileName() and getTempFile() have an input parameter called 'dir' that specifies the directory to create the temporary file if the output needs to be sorted
see https://github.com/CGATOxford/UMI-tools/blob/068818e5d95252b60f24fe2db9ec09eee0d071f0/umi_tools/Utilities.py#L1161

To the best of my knowledge there's no way to pass this parameter from 'umi_tools group' since all the calls are being done as getTempFileName(), see https://github.com/CGATOxford/UMI-tools/blob/56b72de4584520ce960cd6936187169e86d0c205/umi_tools/group.py#L147

Could a flag called --temp-dir be added? I'm happy to submit a PR if that helps

**Comment by IanSudbery** [comment]
I see no reason why this wouldn't be fine. We'd be happy to consider a PR.

**Comment by TomSmithCGAT** [comment]
Hi @ihuerga. Since `U.getTempFilename()` ultimately uses `tempfile.mkstemp()` to get the tempdir, you can set the location by setting the environment variable `TMPDIR`. However, I agree there's no reason not to include this as an option so please do submit a PR if you'd like.

**Comment by TomSmithCGAT** [comment]
After a very long delay, this has now been added. This option is available immediately from the master branch and will be made available in the next release.
