### ISSUE TITLE
Pair-end bam :Where is the end pos in group output file ?

### ISSUE THREAD

**Issue by CN-Geminghui** [CGATOxford/UMI-tools#255]
In *.group.tsv,the contig and position just save the start pos ,where is the end pos;
I want to count each pos retain how many UMI-sequence,so I group by the contig and position;But then I find the unique pos group read have the same pos in R1 ,differen pos in R2.why?

**Comment by CN-Geminghui** [comment]
for example:
read1:
R1 : A00168:146:H2V7GDSXX:1:1441:13069:20494_AACAGAAGCGCTCC	1123	chr22	42525892	0	71M55S	=	42525892	71	TCCCCGAAGCGGCGCCGCAACTGCAGAGGGAGGGTCAGGGCCTCTTGTCAAGCCAGGATCCCCCCAGACTAGGAGCGCAGATCGGAAGAGCACACGTCTGAACTCCAGTCACATGAATAAATCTCG	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,F::F:F,FF	XA:Z:chr22,+42539563,71M55S,0;	MC:Z:49S71M
R2 : A00168:146:H2V7GDSXX:1:1441:13069:20494_AACAGAAGCGCTCC	1171	chr22	42525892	0	49S71M	=	42525892	-71	CATCTTGCCACACTCTTTCCCTACACGACGCTCTTCCGATCTAACAGAATCCCCGAAGCGGCGCCGCAACTGCAGAGGGAGGGTCAGGGCCTCTTGTCAAGCCAGGATCCCCCCAGACTA	F,,F::FFFFF:FFFF:FFFFFFF:FFFFFF:FFFFFF:FF:FFF,FFF:FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	XA:Z:chr22,-42539563,49S71M,0;	MC:Z:71M55S
read2  : 
R1 : A00168:146:H2V7GDSXX:1:1128:7862:34084_ACCAATGATAAGGC	1171	chr22	42525891	0	44S100M	=	42525892	-99	TTGCCACACTCTTTCCCTACACGACGCTCTTCCGATCTACCAATGTCCCCGAAGCGGCGCCGCAACTGCAGAGGGAGGGTCAGGGCCTCTTGTCAAGCCAGGATCCCCCCAGACTACAGGTCCTAGTCCTATTTGAACCTTGGA	F:FFFFFFFFFFFFFFFF,F:FF,FFFFF:FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFF	XA:Z:chr22,-42539562,44S100M,0;	MC:Z:99M45S
R2: A00168:146:H2V7GDSXX:1:1128:7862:34084_ACCAATGATAAGGC	1123	chr22	42525892	0	99M45S	=	42525891	99	TCCCCGAAGCGGCGCCGCAACTGCAGAGGGAGGGTCAGGGCCTCTTGTCAAGCCAGGATCCCCCCAGACTACAGGTCCTAGTCCTATTTGAACCTTGGAGCCTTATAGATCGGAAGAGCACACGTCTGAACTCCAGTCACATGA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFF:,FFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFF	XA:Z:chr22,+42539563,99M45S,0;	MC:Z:44S100M

this two reads is the sam pos ? but in group.tsv,this two pos is the same pos :chr22-42525892
confusion~ Please ,thanks!

**Comment by TomSmithCGAT** [comment]
We don't currently output the read 2 position with group since . This is something we're looking into for v0.6.0.
