### ISSUE TITLE
Add per-cell for count_tab. What input format is required for Umi_tools count?

### ISSUE THREAD

**Issue by runningvato** [CGATOxford/UMI-tools#259]
Hello,
My experimental setup is a bit complicated, but my goal is to generate a counts table for a single transcriptional target per cell that is captured on 10X. The transcriptional target is synthetic (not in genome) and delivered to cells prior to capture. Given the nature of my target, it requires multiple alignments (using a single STAR or hisat2 reference would significantly increase the amount of time used). As a result, I don't have a single .bam file that contains all mapping results (I have three). Instead, I have developed a pipeline that performs all the required processing and outputs a single output per read that I would like to use as a "Gene".  I am now trying to figure out how to append this "Gene" information to a .bam file to use as input for Count with --per-gene flag.  I was hoping I could get a precise definition of what the input bam file format is for Count.

I have read through whatever I could find on this topic and have tried to implement the following. 
1) Convert fastq to bam file using PicardTools fastqtosam (CB and UMIs added to readname prior)
2) Add "Gene" output from my pipeline to bam file with XT:Z:xxxx tag with awk. 

This results in a .bam file that I can open with samtools view. I have made sure to preserve its header (a single line output from the picardtools fastqtosam). 

I then run:
umi_tools count --per-gene --gene-tag=XT --per-cell -I input.bam -S counts.tsv.gz

I get the following error messages:

Traceback (most recent call last):
  File "/usr/local/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/umi_tools/umi_tools.py", line 59, in main
    module.main(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/umi_tools/count.py", line 83, in main
    infile = pysam.Samfile(in_name, in_mode)
  File "pysam/libcalignmentfile.pyx", line 401, in pysam.libcalignmentfile.AlignmentFile.__cinit__ (pysam/libcalignmentfile.c:5835)
  File "pysam/libcalignmentfile.pyx", line 611, in pysam.libcalignmentfile.AlignmentFile._open (pysam/libcalignmentfile.c:8072)
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False

I am assuming this is because I am not using a "real" bam file that contains alignment information. If so, is there anyway I can circumvent this requirement? Ideally, my input would be 1) Read_ID (with appended CB and UMI) and 2) "Gene". 

Thanks for your time and this great software suite!

**Comment by IanSudbery** [comment]
Hi. So UMI-Tools does have a command called `count_tab` which takes a two column table with read ID in column one, and gene_id in column two. Unfortunately at the moment, it isn't compatible with `--per-cell`. I can't remember why right now, I'll have to go investigate - it might be a simple fix, or there might be some deeply engrained algorithmic reason that I've forgotten. 

Id would guess the reason you can't currently open the BAM file is that the header isn't complete. Probably the header has no `@SQ` entries. What do the read in your pesudo-bam have as their contig?

**Comment by runningvato** [comment]
You are correct- the header of my pseudo bam file does not have any @SQ entries. The contig is blank ("*") for every read. 

With this in mind, I have tried an alternative approach where I add the "GENE" XT tag to one of the aligned bam files that are created as part of my pipeline. With this, there are ~500 @SQ entries and a contig value for each read. The @SQ line/contig values are essentially meaningless since they correspond only to the sequences I add in the experiment and don't have relative locations to each other. However, I am able to sort "by coordinate" and can now successfully run Count on this file.

This work around will do for now, but I would be very interested in Count_Tab gaining a --per-cell function (collaborators and I have many more of these types of experiments to perform). I'll be keeping an eye out for any such updates!

Thanks again for your time and effort in making this tool.

**Comment by TomSmithCGAT** [comment]
From the next release, it will be possible to use `count_tab` to count reads per cell using `--per-cell`. See #308
