### ISSUE TITLE
where fo find hg38_noalt_junc85_99.dir

### ISSUE THREAD

**Issue by niehu2018** [CGATOxford/UMI-tools#266]
Hi,
       I want to have some exploration and test. 
       Where can I get the index folder "hg38_noalt_junc85_99.dir"

Thanks!

**Comment by TomSmithCGAT** [comment]
Hi @niehu2018. I'm assuming you're trying to work through the Single cell tutorial. As it say at the top of the tutorial

```
Before you start, you will need:

    An installed copy of UMI-tools (see the installation guide)
    The STAR aligner
    A STAR index for the human genome
```
and later in the description of step 4:

```
We are mapping to an index built on the human NCBI38 reference, with the alternate
contigs removed (referred to by NCBI as the "analysis read set") using junctions from
ENSEMBL85 and a 99nt overhang.
```

We don't provide this index but it's easy to build yourself. Following section 2 of the [STAR manual](https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf), once you have obtained the hg38 human genome reference and ensembl85 geneset gtf, you can create the `hg38_noalt_junc85_99.dir` index directory using STAR with the following command. 

```--runThreadN NumberOfThreads
--runMode genomeGenerate
--genomeDir /path/to/genomeDir
--genomeFastaFiles /path/to/genome/fasta1 /path/to/genome/fasta2 ...
--sjdbGTFfile /path/to/annotations.gtf
--sjdbOverhang 99
```
