### ISSUE TITLE
"number of reads counted" in umi_tools count

### ISSUE THREAD

**Issue by kevin199011** [CGATOxford/UMI-tools#268]
Hi I'm using the umi_tools count to get the UMI counts. I have filtered the bam to only include maped reads and bowtie2 gives 95% unique mapping percentage. However, in the output of umi_tools count, it gave me:
Input Reads: 20041231
Number of reads counted: 2650396
I'm wondering why there is only about ~10% reads counted? Thank you!

Kevin

**Comment by kevin199011** [comment]
Just to add, I was using --per-contig --per-cell --wide-format-cell options.

**Comment by TomSmithCGAT** [comment]
Hi @kevin199011. `Number of reads counted` is after removal of duplicate reads. This number should be the same as the sum of gene counts
