### ISSUE TITLE
--3prime option

### ISSUE THREAD

**Issue by casimonet** [CGATOxford/UMI-tools#27]
Hi,

I am trying to extract my UMIs  from my reads to add it to the reads names. The UMIs are on the 3prime end so I used the --3prime option.

The help does not specify anything else to do but add this option in the command line when we want to use it. However the output seems to suggest that some arguments should be added to this option. Which ones are they?

Here is my command:
srun umi_tools extract -I /path/to/file/of/reads1 -S /reads1.UMIextracted.fq --bc-pattern XXXXXXNNNNNNNNNN --read2-in /path to file of reads2  --3prime --read2-out /reads2.UMIextracted.fq  -L extractUMI.log

Here is the error message I get:
TypeError: _joiner_3prime() takes exactly 4 arguments (3 given)

Thank you,
Camille

**Comment by TomSmithCGAT** [comment]
@IanSudbery Can you confirm that the _joiner_3prime function can be ammended thus 4572943

**Comment by TomSmithCGAT** [comment]
Hi Camille,

Sorry there was an unused option for the _joiner_3prime() function. This has been amended on the master branch and pushed to PyPi and Conda so you should be able to install the latest version (v0.0.11).

Thanks for raising this!

**Comment by casimonet** [comment]
Ok great thank you,

Camille

**Comment by IanSudbery** [comment]
Can this issue now be closed?

**Comment by casimonet** [comment]
Yes, Than you

2016-05-24 15:49 GMT+02:00 Ian Sudbery <notifications@github.com>:
