### ISSUE TITLE
remove singleton UMIs in umi_tools count

### ISSUE THREAD

**Issue by kevin199011** [CGATOxford/UMI-tools#274]
Hi, I'm wondering if it's possible to remove singleton UMIs that only have 1 read, which are more likely to be from errors, when doing umi_tools count. I think currently, all of the methods (directional, adjacency) retains singleton UMIs. Also, percentile might not necessarily remove singleton UMIs. It would be great if can add such a threshold option. Thank you!

Kevin

**Comment by TomSmithCGAT** [comment]
Hi Kevin. I'm not sure we would want to include this as an option in `umi_tools` but it should be very easy to perform if you switch to `umi_tools group`, keep all the options the same as you are currently using for `umi_tools dedup`, and include `--output-bam --group-out=[GROUP_OUT_FILENAME.tsv]`. This will output a BAM file containing **all** reads with additional tags `UG` and `BX` which detail the UMI group the read was in. UG=Unique ID. BX=UMI (after correction). The tsv file will contain all reads in a tab separated format, with columns for read id, alignment position, UMI pre and post correction, the UMI group ID, and the number of reads in the UMI group. Using these files is should be straightforward to filter out reads which are in a UMI groups containing just a single read as you wish.

**Comment by TomSmithCGAT** [comment]
I'm closing this as I don't think we want to add the option to remove singleton UMIs and it's possible for users to do so themselves as described above.
