### ISSUE TITLE
Degenerate base UMI

### ISSUE THREAD

**Issue by wangjiawen2013** [CGATOxford/UMI-tools#275]
Dear,
here is my bc+umi sequence from smart-seq2.
**GATAGACA**_DDDDDDDDttttttttttttttttttttttttt_
The first eight bases is cell barcode, the left 33 bases is umi, D is degenerate base (A/G/T).
Does bc-pattern supports this format ?

**Comment by wangjiawen2013** [comment]
This single cell RNAseq is executed with smart-seq2, each cell is in a micro-well, then a specific cell barcode and umi was added. there are 24 cells (24 wells) in total.

**Comment by IanSudbery** [comment]
What is it you would like to do with your degenerate bases? Are they part of the UMI?

**Comment by wangjiawen2013** [comment]
> What is it you would like to do with your degenerate bases? Are they part of the UMI?

yes, they are UMI, D (not N) is optimized design and work better

**Comment by IanSudbery** [comment]
I'm assuming that when you say there is a 33 base UMI, you mean 8 degenerate bases, followed by 25 `t` bases.

Should work fine just specificying barcode as: `CCCCCCCCNNNNNNNN`. This will leave the 25 `t` bases on the read. You'll probably need to trim before mapping.  If you wanted to discard reads that had `C` in one of the degenerate positions, you could use:

`--bc-pattern="(?P<cell_1>.{8})(?P<umi_1>[AGT]{8})(?P<discard_1>t{25})"` filter out any reads that have `C` in one of the D positions and that don't have 25 `t` bases. The `t` bases will be removed from the read.

**Comment by TomSmithCGAT** [comment]
Hi @wangjiawen2013 - Have you tested out @IanSudbery's suggestions and did this achieve what you wanted?

**Comment by wangjiawen2013** [comment]
I have not tested it, because it does not matter whether it is D or N, the information of position and length of UMI  is sufficient to confirm the UMI and it works better, In another word, there is no need to change UMI-tools rule.

**Comment by wangjiawen2013** [comment]
> I'm assuming that when you say there is a 33 base UMI, you mean 8 degenerate bases, followed by 25 `t` bases.
> 
> Should work fine just specificying barcode as: `CCCCCCCCNNNNNNNN`. This will leave the 25 `t` bases on the read. You'll probably need to trim before mapping. If you wanted to discard reads that had `C` in one of the degenerate positions, you could use:
> 
> `--bc-pattern="(?P<cell_1>.{8})(?P<umi_1>[AGT]{8})(?P<discard_1>t{25})"` filter out any reads that have `C` in one of the D positions and that don't have 25 `t` bases. The `t` bases will be removed from the read.

Hi, 
If the barcode-umi-polyT is in R1, will it discard reads in R2 that don't have this barcode-pattern ? I mean, some reads in R1 don't have polyT, then R2 reads corresponding these R1 reads can be considered as unvalid reads, I want to discard them.
