### ISSUE TITLE
How to discard reads without UMI?

### ISSUE THREAD

**Issue by WT215** [CGATOxford/UMI-tools#284]
Hello,

In a dataset, the UMI pattern is: `NNNNNGGG`. 

For some reads which do not have exactly three `G` at the end of the first 8 bps, I would like to treat them as not having UMI attached, and discard them  (This procedure was described in the paper Tung et al 2017, Read mapping part, but I am not sure how to achieve that using `umi_tools`).

It seems that I can achieve that using `umi_tools extract --extract-method=regex --bc-pattern=`, but I am not sure how to specify the `--bc-pattern`.

Thanks a lot!

Wenhao

**Comment by IanSudbery** [comment]
Hi Wenhao,

Sure this is possible. You are right about specifying the method as regex. The pattern would be `(?P<umi_1>.{5})(?<discard_1>G{3})`. This specifies that the first 5 bases can be anything and should be kept as the umi, the next three should be G and should be discarded. Note that this will allow 4 or more Gs, of only 3 would be discarded. Let me know if this is not what you want.

**Comment by TomSmithCGAT** [comment]
Hi Wenhao, 

If I understand correctly, you should be able to acheive this using the following:
`--bc-pattern="(?P<umi_1>.{5})GGG"`

The codebase for `umi_toolsIf in doubt with python regexes

**Comment by WT215** [comment]
@TomSmithCGAT Thank you for your quick reply! I am not familiar with regex. 

So suppose that there is a read with the first 8 bases: NNNNNGGC, will that command guarantee that this read will be discarded? (I guess this read should be treated as read without UMI, because the last three bases are not all G)

Is it a common way to tell and discard reads without UMI?

Thanks a lot!
Wenhao

**Comment by WT215** [comment]
@TomSmithCGAT Hi, I tested the code on a fastq data, it indeed achieved what I expected. 

Thank you very much!
Wenhao

**Comment by TomSmithCGAT** [comment]
Yes, that read will be rejected. The number of rejected reads will be logged as well. 

You can use an online regex checker when you're unsure (e.g https://pythex.org/) but in this case, it's also important to note the documentation: `umi_tools extract --help` (copied below). @IanSudbery actually beat me to the response and surprised me into clicking close and comment before I'd finished my comment. Hence, I deleted mine and reopened the issue. Sounds like everything's good so I'll close this now.

```
-'regex'
       This method allows for more flexible barcode extraction and
       should be used where the cell barcodes are variable in
       length. Alternatively, the regex option can also be used to
       filter out reads which do not contain an expected adapter
       sequence.

       The expected groups in the regex are:

       umi_n = UMI positions, where n can be any value (required)
       cell_n = cell barcode positions, where n can be any value (optional)
       discard_n = positions to discard, where n can be any value (optional)

       UMI positions and cell barcode positions will be extracted and
       added to the read name. The corresponding sequence qualities
       will be removed from the read. Discard bases and the
       corresponding quality scores will be removed from the read. All
       bases matched by other groups or components of the regex will be
       reattached to the read sequence

       For example, the following regex can be used to extract reads
       from the Klein et al inDrop data:

       (?P<cell_1>.{8,12})(?P<discard_1>GAGTGATTGCTTGTGACGCCTT)(?P<cell_2>.{8}
)(?P<umi_1>.{6})T{3}.*

       Where only reads with a 3' T-tail and GAGTGATTGCTTGTGACGCCTT in
       the correct position to yield two cell barcodes of 8-12 and 8bp
       respectively, and a 6bp UMI will be retained.

       You can also specify fuzzy matching to allow errors. For example if
       the discard group above was specified as below this would enable
       matches with up to 2 errors in the discard_1 group.

       (?P<discard_1>GAGTGATTGCTTGTGACGCCTT){s<=2}

       Note that all UMIs must be the same length for downstream
       processing with dedup, group or count commands

```

**Comment by WT215** [comment]
@IanSudbery @TomSmithCGAT Thank you both!
