### ISSUE TITLE
Dedup function 

### ISSUE THREAD

**Issue by sinhaeti** [CGATOxford/UMI-tools#287]
Hello, 

The dedup function document states the following: "the purpose of this command is to deduplicate BAM files based on the first mapping co-ordinate and the UMI attached to the read" 

Is it possible to deduplicate based on just the UMI attached to the read? What is the logic behind using the co-ordinates?

Best,

**Comment by IanSudbery** [comment]
Hi,

Traditionally PCR duplication is done purely on the basis of mapping positions. UMIs add additional information to this, allowing for the possibility that two reads from genuinely independent molecules might have the same mapping co-ordinates. 

In the case of most protocols that use UMIs, the UMI alone simply isn't unique enough to uniquely identify a pre-PCR molecule. Consider: For deduplicating only on a UMI to work, it has to be far more likley that two reads with the same UMI are PCR duplicates than that two independent molecules got the same UMI. With a 10nt UMI there are 1 million different possible UMI sequences. A standard RNAseq library, for example, might contain around 30 million reads. But the situation is worst than this: UMIs can containing sequencing errors, thus UMI-tools doesn't just assume that two reads with the same sequences are duplicates, but that two reads with *similar* sequences are duplicates. Finally usage of supposedly random UMI sequences is not actually random: some sequences are more likely to be used than others. Thus to distinguish duplicates from two reads that just happen to have got the same UMI sequence, we need more information.

What information is appropriate depends on the protocol that created the data. Simply put, if PCR happens after fragmentation, then reads with different mapping co-ordinates are likely to have come from different molecules. This applies to techniques like iCLIP, 4C, ChIP-seq and standard RNA-seq. 

In other cases fragmentation comes after PCR. In this case in this case two reads from the same original molecule can have different mapping co-ordinates, but there are limits: in 3' end tagging RNA seq (e.g. droplet based single cell RNA seq) two reads coming from different genes cannot be PCR duplicates. In amplicon sequencing, two reads from different amplicons cannot be from the same molecule.

One can readily see in these data sets reads that cannot possibly be PCR duplicates of each other, yet share the same UMI.

Thus we provide three modes: 
**default mode** uses the read mapping position.  Use this for iCLIP, 4C, ChIP-seq, normal RNAseq, miRNA-seq etc, etc,
**--per-gene** uses the gene assigned to the read, usually by something like featureCounts, and stored in a BAM tag.
**--per-contig** uses the only the contig part of the mapping position. This is for where reads have been mapped to a transcriptome, or a custom genome where each contig is an amplicon. 

There is no mode where no positional information is used.  The closet would be to use --per-contig, but with reads mapped to the standard genome. Be aware though that this is likely to lead to very high memory usage and be very slow.

**Comment by sinhaeti** [comment]
Thank you so much for the quick and detailed reply!

**Comment by TomSmithCGAT** [comment]
Hi @sinhaeti. Can we close this issue?

**Comment by sinhaeti** [comment]
Yes

**Comment by sinhaeti** [comment]
Hello, 

I used featureCounts to assign genes to each read and then dedup --per-gene to deduplicate. However, there are a few cellbarcode-UMI pairs that occur more than once. Why might this be the case?

Best
Eti

**Comment by IanSudbery** [comment]
Are these within the same gene?

**Comment by IanSudbery** [comment]
would you be able to post an example?

**Comment by sinhaeti** [comment]
Can I email you instead?
