### ISSUE TITLE
Whitelist for Split-seq

### ISSUE THREAD

**Issue by jentiger82** [CGATOxford/UMI-tools#288]
I have a question regarding the creation of whitelists for the Split-seq single-cell sequencing method. In this sequencing method RNAs/cDNAs are barcoded several times and Read2 is the barcode read, which looks like this: --bc-pattern="(?P<umi_1>.{10})(?P<cell_3>.{7,8})(?P<discard_1>GTGGCCGCTGTTTCGCATCGGCGTACGACT){s<=5}(?P<cell_2>.{7,8})(?P<discard_2>ATCCACGTGCTTGAGAGGCCAGAGCATTCG){s<=5}(?P<cell_1>.{7,8}).*". Using this pattern I was able to create a whitelist. However the whitelist only has a length of 14, when I expect up to 48*96*96, as this is the number of barcodes used in each of the three barcoding rounds. And the output itself stated that it found over 3 million unique cell barcodes. I attached the whitelist for you to take a look. So I am wondering if the whitelist should not be longer and what the problem might be?
[whitelist.txt](https://github.com/CGATOxford/UMI-tools/files/2459701/whitelist.txt)

Thanks, Jenny

**Comment by TomSmithCGAT** [comment]
Hi @jentiger82 - Could you re-run with the command `--plot-prefix=whitelist_debug_plots` (if you haven't already included this in your command) and post the full log file here. I suspect that `whitelist` has incorrectly estimated the number of true barcodes.

**Comment by TomSmithCGAT** [comment]
Hi @jentiger82. Have you managed to resolve this?

**Comment by TomSmithCGAT** [comment]
I'm going to close this due to low activity. Please re-open if this issue hasn't been resolved
