### ISSUE TITLE
Problems when only pattern2 is specified

### ISSUE THREAD

**Issue by fa-vio** [CGATOxford/UMI-tools#290]
Hello,
I have been working on paired-end targets where the UMI is placed at the 5' end, but only on read 2. I tried to extract the barcode using the following command
`umi_tools extract --extract-method=string --bc-pattern2=NNNNNNNNNN -I infile_R1.fq.gz --read2-in=infile_R2.fq.gz -S outfile_R1.fq --read2-out=outfile_R2.fq`

but the execution stops because of a Type Error: 

>  TypeError: cannot concatenate 'str' and 'list' objects

the error seems to be related to the instruction `umi_quals += umi_quals2`: when the first pattern is not given, `umi_quals` is set to an empty string, and gets updated with a list afterwards, in case pattern2 is given. (line 752, in _getBarcodesString)

I don't know if it is just an unhandled event or the intended behaviour. If the latter is the case, I'd like to know how I could possibly extract a UMI placed only on read 2.

Thanks for your time

**Comment by IanSudbery** [comment]
Sorry, this is an unhelpful error message. 

To extract UMIs only from read2, simple pass read2 to `-I` and read1 to --read2-in, thus:

```
umi_tools extract --extract-method=string \
                            --bc-pattern=NNNNNNNNNN \
                            --read2-in infile_R1.fq.gz \
                             -I infile_R2.fq.gz \
                            -S outfile_R2.fq \
                            --read2-out=outfile_R1.fq
```

**Comment by fa-vio** [comment]
Hi, I understand the error message wasn't much helpful, but it was all I could post, as it was just a python exception on that exact line. I'm sorry for that. And I just realize I didn't mention the source file where the exception was caught: it was on `umi_methods.py`.
The error happens because  `umi_quals` (and  `umi_quals2`) are list objects when a UMI pattern is specified, but are set to empty strings when a pattern is missing.

Before I could read your reply, I applied a quick edit to the source code in  `umi_methods.py:736`, where a number of variables, including `umi_quals`, are set to empty string: in that case,  I set `umi_quals` to an empty _list_
```
    cell, umi, new_seq, new_quals = ("",)*4 # umi_quals
    umi_quals = [ ]
```
which does solve the above error and does not seem to require any further adjustment to the code.

Anyway, thanks for your reply, I now see there is a way to extract UMIs only from read2: I didn't actually think about swapping input files. I find a little awkward.

I tried both ways and output files are identical.

**Comment by TomSmithCGAT** [comment]
Hi @fa-vio - Good to hear @IanSudbery's suggestion has resolved the issue. 

I think @IanSudbery was actually apologising that `umi_tools` didn't capture the incorrect input and provide a useful warning. Thus, you ended up with the python `TypeError` which which you had to trace back to the lines in the code to work out what it meant. Thanks for taking the time to identify the source of the error.

**Comment by IanSudbery** [comment]
Yeah, absolutely no need to apologise - I was apologising to you that we didn't output a more useful error message.
