### ISSUE TITLE
dedup works on all bam?

### ISSUE THREAD

**Issue by arnoldliaoILMN** [CGATOxford/UMI-tools#30]
What is the requirement for a bam file for umi_tools to take in?  I am encountering some error on some generic bam.  http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwRepliSeq/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam 

dedup -I wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam -S wgEncodeUwRepliSeqBg02esG1bAlnRep1.dedup.bam

  File "/usr/local/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/umi_tools/umi_tools.py", line 42, in main
    module.main(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/umi_tools/dedup.py", line 924, in main
    options.stats, options.further_stats)
  File "/usr/local/lib/python2.7/dist-packages/umi_tools/dedup.py", line 443, in __call__
    min(len_umis), max(len(umis))))
TypeError: 'int' object is not iterable

**Comment by IanSudbery** [comment]
umi_tools was designed to work on BAM files that include a UMI sequence in the read name, separated from the body of the name by an underscore, such as those produced by umi_tools extract. 

It is possible to use dedup on BAM files that do not contain UMI sequences by specifying the `--ignore-umi` switch on the commandline, but other tools such as picard's `MarkDuplicates` or `samtools rmdup`  might be more suitable/efficient for this use case.
