### ISSUE TITLE
UMI only read2

### ISSUE THREAD

**Issue by amufaamo** [CGATOxford/UMI-tools#300]
Hi,

How can I use "umi_tools extract" for data which has UMI only at 5' of read2.

I got error below
```
umi_tools extract -I head_1.fastq --bc-pattern2=NNN --read2-
in=head_2.fastq --stdout=processed1.fastq --read2-out=processed2.fastq
```

Should I use the command like this?
`umi_tools extract -I head_2.fastq --bc-pattern=NNN --read2-in=head_1.fastq --stdout=processed2.fastq --read2-out=processed1.fastq`

**Comment by TomSmithCGAT** [comment]
Hi @amufaamo, you can simply provide the read2 alone:
```
umi_tools extract -I head_2.fastq --bc-pattern=NNN --stdout=processed2.fastq
```

**Comment by IanSudbery** [comment]
@TomSmithCGAT This is wrong, no? If you do this then you will not get the UMI on the read name of the read1s?

I think @amufaamo 's second command is correct.

**Comment by TomSmithCGAT** [comment]
Very sorry. Shouldn't reply to issues before my morning coffee. Yes, the second command was perfect!

**Comment by amufaamo** [comment]
Dear @TomSmithCGAT and @IanSudbery 

Thank you so much. I use the command.

**Comment by rseraphin** [comment]
Hi,
We're working on marsSEQ data which has cell barcodes and UMIs only at 5' of read 2.

We can easily work around the issue encoutered with umi_tools whitelist and extract with a command similar to the second command of the first comment ( by using read2 as read1 in input).

However, this does not make things clear in pipelines.
Could it be possible to use extract and whitelist with only "--bc-pattern2" ?
