### ISSUE TITLE
UMI-tools count: output read number does not match with input read number

### ISSUE THREAD

**Issue by GabrielBaldissera** [CGATOxford/UMI-tools#314]
Hello, guys! I am analyzing some drop-seq data following your protocol for single-cell and my goal is to get a count table per gene and per cell.

I have used UMI-tools extract to move the cell barcode + UMI into the read name. Then, I aligned using STAR (multimapping reads not allowed) and assigned the genes using featureCounts:

featureCounts -a /path/.gtf -o Path/Alignment/Sample_R2_extracted_gene_assigned -R BAM -T 16 path/Alignment/Sample_R2_extracted_Aligned.sortedByCoord.out.bam

The successfully assigned reads number was around 70%. This is my sorted BAM after featureCounts. It seems the tags were properly added.

NS500422:152:HF52VBGXX:1:13305:9347:6088_AATGGACACTTT_TCTAACCT	0	1	17157031	255	60M	*	0	0	TCTTGACTCCTTGCCAATGGATGCTTACACACATGGCTGCATTTTGCATCCTGAGCTCAC	AAAAAEEEEEEEEEE/AEEE//EE6A/EAE/EEEEAAAEEAAAE/AEE<EEA<E/EAE/A	NH:i:1	HI:i:1	AS:i:59	nM:i:0	XS:Z:Assigned	XN:i:1	XT:Z:ENSMUSG00000025777
NS500422:152:HF52VBGXX:1:13311:12194:11024_AAAACGACTCAG_TCGCTTCT	0	1	17157031	255	60M	*	0	0	TCTTGACTCCTTGCCAATGGATGCTTACACACATGGCTGCATTTTGCATCCTGAGCTCACAAAAAEEEAEAE/EE/AEEEEE6E6<EEAEEE///A/AAAEE<A/A/EEE/<A/AE<//<	NH:i:1	HI:i:1	AS:i:59	nM:i:0	XS:Z:Assigned	XN:i:1	XT:Z:ENSMUSG00000025777
NS500422:152:HF52VBGXX:1:22202:1210:7655_GAGCCTTTCGGT_TTAGGCTT	0	1	17157031	255	60M	*	0	0	TCTTGACTCCTTGACAATGGATGCTTACACACATGGCTGCATTTTGCATCCTGAGCTCAC	AA/AAEEEEEEEA/<EE</AEE/EEE//AEEA6A/<EEEEA<AE<<E/AE</6/6AA/AA	NH:i:1	HI:i:1	AS:i:57	nM:i:1	XS:Z:Assigned	XN:i:1	XT:Z:ENSMUSG00000025777

Then I used UMI-tools count to get the number of counts for each gene in each cell barcode:

umi_tools count --wide-format-cell-counts --per-gene --gene-tag=XT --assigned-status-tag=XS --per-cell -I sample_assigned_sorted.bam -S Sample.tsv

When running, the # umi_tag : RX is set automatically. Is that right, considering that the UMI is the last part of the read name, is that considered a tag?

What I am not getting is why the number of input reads, skipped and counted do not match.
2019-01-31 17:54:22,180 INFO Input Reads: 113693559
2019-01-31 17:54:22,180 INFO Read skipped, no tag: 40356101
2019-01-31 17:54:22,180 INFO Number of reads counted: 14006936

I understand that the "Read skipped" refers to the reads that were classified as ambiguous. However, the number of reads counted is extremely low. What could have happened to the other reads? I am afraid that I am losing much information.

Sorry for the long message, I hope it was clear enough.
All the best, 
Gabriel

**Comment by IanSudbery** [comment]
Hi Gaberiel,

You are counting only a small number of reads because most reads are being discarded as duplicates. This is completely normal in single-cell sequencing, and is the whole reason behing using UMIs in the first place.

**Comment by TomSmithCGAT** [comment]
Yes, we should perhaps log "Number of *deduplicated* reads counted" to make this clearer.

**Comment by GabrielBaldissera** [comment]
Thanks a lot for replying, guys!

I had in mind it could be caused by duplicates but I was not sure and not aware its number could be so high.
I think that  "Number of deduplicated reads counted" would be very informative! 
I really appreciate your help and I should say I like a lot the tools and the tutorial.

Thanks!
