### ISSUE TITLE
Estimating barcode number: Extrmelly low threshold values

### ISSUE THREAD

**Issue by GabrielBaldissera** [CGATOxford/UMI-tools#315]
Hello, guys.
I've read the previous posts regarding the issues with the Knee method and I'm having a hard time deciding on how to proceed with the barcode identification of some samples. I could really use your expertise and some advice. 

I am analyzing the dataset  by [Campbell](https://portals.broadinstitute.org/single_cell/study/a-molecular-census-of-arcuate-hypothalamus-and-median-eminence-cell-types) and using the `whitelist` function to get the real CB. I have the estimated dropseq input cell number in the sequencing I used those values with `--expect-cell-number` to identify the CBs for all the samples.
eg:
`umi_tools whitelist --stdin $campbell/Samples/SampleFasted_R1.fastq --bc-pattern=CCCCCCCCCCCCNNNNNNNN --expect-cells=9800 --plot-prefix=$campbell/Samples/SampleFasted --log2stderr > $campbell/Samples/SampleFasted_whitelist.txt`

It turns out that the `whitelist` function identified CB numbers close to the ones identified at the reference study for half of the samples.  I compared my CB numbers with the ones from the reference study [here](https://imgur.com/a/Ji1X7gp).

For 2 samples (Chow10 and HFD), the  `--expect-cell-number` ran without error but the selected thresholds seem to be a little off from the knee curve point ([plots](https://imgur.com/a/boHcjBo)). So my question here is:  Should I use `--set-cell-number` to select the higher thresholds, which will also give me higher CB numbers?

For others samples ([Fasted](https://imgur.com/a/xFwl2P2), [Refed](https://imgur.com/a/1nW1m5b), [M_Fed](https://imgur.com/a/GAublOb), [M_Fasted](https://imgur.com/a/cCEE9Vm)), I got the error output saying to manually set the values using  `--set-cell-number`. I tried using several different values for `--expect-cell-number` both above and below the estimated cell number and the thresholds were usually the same low values,  even when I did not use any cell number arguments. The only thing that changed was the selected threshold values that were always extremely low (around 30-140). 

The FastQC analysis of the samples does not indicate that they are worst than the others.

I am not inclined to think that I have around 40 cells in an entire sample.  Given that I have tried several values for `--expect-cell-number`, I thought of using -`-set-cell-number` to provide the number of cells identified by the reference study as a direction of the barcode number that could be accepted.

What do you think the problem with those samples might be?
Thanks in advance and please let me know if I can provide any additional information.

All the best, 
Gabriel

**Comment by IanSudbery** [comment]
How well would alevin whitelisting perform here? Could a very lax primary threshold be specified and then be refined with the classifier?

**Comment by TomSmithCGAT** [comment]
It's a good question. @k3yavi - Do you think `alevin` would handle the CB distributions shown in the links (e.g [Fasted](https://imgur.com/a/xFwl2P2)) OK?

Another option would be to implement a different method for knee detection in `umi_tools whitelist` and combine this with the new options to detect error barcodes above the knee. Updating the knee detection has long been on the to-do list. In particular, an approach suggested in a comment on the CGAT blog looks worth testing out: https://dataplatform.cloud.ibm.com/analytics/notebooks/54d79c2a-f155-40ec-93ec-ed05b58afa39/view?access_token=6d8ec910cf2a1b3901c721fcb94638563cd646fe14400fecbb76cea6aaae2fb1

**Comment by k3yavi** [comment]
It's hard to say, but if it's `dropseq` it can be easily tested given we have the `fastqs`.

**Comment by GabrielBaldissera** [comment]
Hey guys, thank you for the answers!

I followed the first suggestion and extracted the barcodes from the available expression tables. I skipped the first step and then followed with the tutorial. The results improved a lot.

Thanks!!!

**Comment by TomSmithCGAT** [comment]
Glad to hear it! Thanks for getting back to us
