### ISSUE TITLE
umi_tools whitelist --help: ImportError: No module named Utilities

### ISSUE THREAD

**Issue by madaojjc** [CGATOxford/UMI-tools#321]
I installed umi_tools by 

git clone https://github.com/CGATOxford/UMI-tools.git
pip install -r requirements.txt
python setup.py install

and after that, when I run umi_tools , there was no problem, but when run umi_tools whitelist --help, it showed:

UMI-Tools: Version 1.0.0
Traceback (most recent call last):
  File "/usr/local/bin/umi_tools", line 11, in <module>
    load_entry_point('umi-tools==1.0.0', 'console_scripts', 'umi_tools')()
  File "/home/shen/.local/lib/python2.7/site-packages/umi_tools-1.0.0-py2.7-linux-x86_64.egg/umi_tools/umi_tools.py", line 58, in main
    module = importlib.import_module("umi_tools." + command, "umi_tools")
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/shen/.local/lib/python2.7/site-packages/umi_tools-1.0.0-py2.7-linux-x86_64.egg/umi_tools/whitelist.py", line 205, in <module>
    import umi_tools.Utilities as U
ImportError: No module named Utilities

**Comment by madaojjc** [comment]
I tried pip install and conda, but there was still such a problem...

**Comment by IanSudbery** [comment]
Hi,

As of this new version, 1.0.0 we no longer support python 2.7. Try creating a new python 3 conda environment and installing UMI-Tools with:

    conda create -n umi_tools_env -c bioconda python=3.7 umi_tools 
    source activate umi_tools_env

Alternatively, if you really need to install UMI-Tools in a python 2 enviornment, please install version 0.5.5 with `conda install umi_tools==0.5.5` or `pip install umi_tools==0.5.5`

**Comment by madaojjc** [comment]
> Hi,
> 
> As of this new version, 1.0.0 we no longer support python 2.7. Try creating a new python 3 conda environment and installing UMI-Tools with:
> 
> ```
> conda create -n umi_tools_env -c bioconda python=3.7 umi_tools 
> source activate umi_tools_env
> ```
> Alternatively, if you really need to install UMI-Tools in a python 2 enviornment, please install version 0.5.5 with `conda install umi_tools==0.5.5` or `pip install umi_tools==0.5.5`

Creating a new python 3 conda environment sovled my problem! THANKS A  LOT!

**Comment by madaojjc** [comment]
It works! THANKS A LOT





At 2019-02-17 22:39:02, "Ian Sudbery" <notifications@github.com> wrote:


Hi,

As of this new version, 1.0.0 we no longer support python 2.7. Try creating a new python 3 conda environment and installing UMI-Tools with:

conda create -n umi_tools_env -c bioconda python=3.7 umi_tools 
source activate umi_tools_env


Alternatively, if you really need to install UMI-Tools in a python 2 enviornment, please install version 0.5.5 with conda install umi_tools==0.5.5 or pip install umi_tools==0.5.5

**Comment by IanSudbery** [comment]
Your welcome.

**Comment by qicaibiology** [comment]
> Hi,
> 
> As of this new version, 1.0.0 we no longer support python 2.7. Try creating a new python 3 conda environment and installing UMI-Tools with:
> 
> ```
> conda create -n umi_tools_env -c bioconda python=3.7 umi_tools 
> source activate umi_tools_env
> ```
> 
> Alternatively, if you really need to install UMI-Tools in a python 2 enviornment, please install version 0.5.5 with `conda install umi_tools==0.5.5` or `pip install umi_tools==0.5.5`

conda install umi_tools==0.5.5 also works!
