### ISSUE TITLE
Question about UMI-tools in QUICK.md

### ISSUE THREAD

**Issue by xxtxi** [CGATOxford/UMI-tools#323]
Hi
thank you for your great tool,I found a question when I have installed this tools. I used the tools with QUICK_START.md.For the first time,I downloaded the example.bam directly,the example.bam was about 20M.But when I use bowtie  to map the reads to the mouse genome and then use samtools to create a BAM file from the results,the bam file I made was about 178M that wasNot the same as before.I don't know which bam file is right.
Ps:the mouse genome index download from pre-built-index in the bowtie Official website .
Thanks
Xi

**Comment by TomSmithCGAT** [comment]
Hi @xxtxi - It looks like this issue got missed. Sorry about that. I hope you got to the bottom of this discrepancy OK. I'll close this issue for now but please re-open if this still needs to be resolved
