### ISSUE TITLE
old umi_methods.getCellWhitelist not accessible anymore?

### ISSUE THREAD

**Issue by Hoohm** [CGATOxford/UMI-tools#324]
Hello,

I want to use v1.0.0 but I can't access a function that I was using before.
I should be able to get it from whitelist_methods but I can't import it.

Not sure why.

**Comment by Hoohm** [comment]
Sorry, It works properly.

**Comment by TomSmithCGAT** [comment]
Hi @Hoohm - Sorry, the module files were re-factored as they were getting very busy and too generic. Can you search for the function in the repo and re-find it?

**Comment by Hoohm** [comment]
Yeah I found it. I was navigating the module using ipython and for some reason it didn't find the "whitelist_methods". I tried to use it regardless and it worked properly.
