### ISSUE TITLE
not finding a module

### ISSUE THREAD

**Issue by dauss75** [CGATOxford/UMI-tools#329]
Hi,

I am having an issue of not finding a module although I can import it interactively via python interpreter.  It's installed in Centos 7 via pip install umi_tools. Any though on this problem?  

$ umi_tools extract --help
^[[AUMI-Tools: Version 1.0.0
Traceback (most recent call last):
  File "/isilon/prod/apps/bcbio-data/anaconda/bin/umi_tools", line 11, in <module>
    load_entry_point('umi-tools==1.0.0', 'console_scripts', 'umi_tools')()
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/umi_tools-1.0.0-py2.7-linux-x86_64.egg/umi_tools/umi_tools.py", line 58, in main
    module = importlib.import_module("umi_tools." + command, "umi_tools")
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/umi_tools-1.0.0-py2.7-linux-x86_64.egg/umi_tools/extract.py", line 158, in <module>
    import umi_tools.extract_methods as extract_methods
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/umi_tools-1.0.0-py2.7-linux-x86_64.egg/umi_tools/extract_methods.py", line 7, in <module>
    import umi_tools.Utilities as U
ImportError: No module named Utilities

**Comment by IanSudbery** [comment]
This error occurs if you try to run UMI-tools in a python2 environment, as of version 1.0.0 UMI-tools is python 3 only.

**Comment by dauss75** [comment]
Thanks.  Could you let me know which version would work with python2.7?

**Comment by IanSudbery** [comment]
0.5.5 should work with python27, its the last version before 1.0.0

**Comment by dauss75** [comment]
Thank you.  Do you maintain a different version of the tool here or somewhere else? I don't seem to find a link to 0.5.5.

**Comment by IanSudbery** [comment]
You can find 0.5.5 on the releases page https://github.com/CGATOxford/UMI-tools/releases, or install with pip (`pip install umi_tools=0.5.5`) or conda (`conda install umi_tools=0.5.5 -c bioconda`)

**Comment by dauss75** [comment]
awesome.   Thanks for the quick reply! 
I have one more question which might be more technical and not relevant here.

I want to take umi (12nt) from R2 and also remove following common sequence (11nt).  Could I do that with "umi_tools extract"?
I tried and it carries the 11 nt in R2 as expected:

 umi_tools extract -I R2.fastq.gz --bc-pattern=NNNNNNNNNNNNXXXXXXXXXXX --read2-in=R1.fastq.gz  --stdout=proc2.fastq.gz --read2-out=proc1.fastq.gz

Thanks again for all your help and I will be closing this thread.

**Comment by IanSudbery** [comment]
You want the 11nt common sequence to be removed?

You can do this with the regex barcode finding

`--extract-method=regex --bc-pattern='(?<umi_1>.{12})(?<discard_1>.{11})'`

**Comment by dauss75** [comment]
Thanks!
