### ISSUE TITLE
Counting without gtf/gff

### ISSUE THREAD

**Issue by tbarbier** [CGATOxford/UMI-tools#333]
Hi,

My question might be naive but I thought I might as well ask. I am trying to use UMI-tools to count RNA molecules from a targeted RNA-seq experiment. I did a couple of reverse transcription reactions with gene-specific oligos which contained UMIs, that I then amplified and sequenced.
I managed to:

1. extract the UMI sequences (with a --extract-method=regex), 
2. align to a multifasta file containing only the subset of sequences I am interested in quantifying with Bowtie2, 
3. generate an indexed sorted bam,
4. deduplicate the indexed sorted  bam.

But now, I would like to retrieve the number of UMIs per gene and therefore need to use umi-tools count, itself requiring pre-processing with HTseq or FeatureCount which themselves require a gff or gtf file. I do not have however have such file since I am not working on a whole transcriptome/genome but only on a subset of genes.

Is there any workaround? From the alignment with Bowtie2, the gene to which each read is mapping is saved in the RNAME field from the .sam files, can we somehow use that?

I apologize if my question is not clear and/or non-relevant and thank you for any help you could provide!

**Comment by IanSudbery** [comment]
Am I right in thinking that the identify of the sequences you are aligning to are contained in the FASTA header/contig name in the BAM?

If so, then all you need to do at this point, is extract the `idxstats` from the BAM file:

```
$ samtools idxstats deduplicated.bam | cut -f1,3 > counts.tsv
```

In general you would only run one of  `dedup` or `count`. If you have already run `dedup`, then you would run count afterwards.

You should pay attention to whether the positional information is relevant for your samples: If fragmentation happens after amplification, then the precise position of the read is not meaningful, only the identify of the amplicon it comes from. In this case you would have wanted to run `dedup` with the `--per-gene` swtich, specifying that you want to identify the amplicon from the contig with `--per-contig`.

Hope this helps.

**Comment by tbarbier** [comment]
You're correct indeed, the identify of my sequences are contained in the FASTA header. 
And yes I forgot about idxstats (thought about it and then forgot), that's an easy solution!

Now regarding the positional information, all my amplicons map the exact same region of my targeted transcripts. Therefore, as you say, the precise position of the read is not meaningful and I will therefore re-run umi-tools dedup with the 2 flags --pe-gene and --per-contig beforehand.

Thanks a lot for the quick and clear answer!
