### ISSUE TITLE
Extract is not outputting counts

### ISSUE THREAD

**Issue by sgerety** [CGATOxford/UMI-tools#335]
Hi, I'm running extract on a fastq with 15mer UMIs.  It successfully moved the UMI to the readname, and the log file ends: 
"2019-05-03 15:39:10,461 INFO Reads output: 553785"

However in the methods, you state that the log file will have counts of everyUMI encountered:
_> A log file is saved containing the parameters with which extract was run and the frequency of each UMI encountered._

I cannot see any counts of umis.  Am I misunderstanding the instructions?

Thanks!

[pairedUMI.log](https://github.com/CGATOxford/UMI-tools/files/3142442/pairedUMI.log)

**Comment by IanSudbery** [comment]
hmmm.... the code that did this appears to have been lost along the way. How  important is this output to you?

**Comment by sgerety** [comment]
No worries.  I have found alternate arrangements.  Cheers!

sg
