### ISSUE TITLE
Specifying patterns for MARS-seq

### ISSUE THREAD

**Issue by magali** [CGATOxford/UMI-tools#336]
Thank you very much for your package.
I am trying to use if for MARS-seq data, using the following command:

umi_tools whitelist --stdin Undetermined_S0_R2_001.fastq.gz \
                    --bc-pattern='(?P<cell_1>.{7})(?P<umi_1>.{8})' \
                    --read2-in Undetermined_S0_R1_001.fastq.gz \
                    --bc-pattern2='(?P<discard_1>.{3})(?P<cell_2>.{4}).*' \
                    --extract-method=regex \
                    --set-cell-number=192 \
                    --log2stderr > whitelist.txt \
                    --plot-prefix plot

I get an error with barcode_regex2 (see below). Any idea how to fix it? Did I make a mistake in my patterns?

Thanks a lot for your help,
Magali

> output generated by whitelist --stdin Undetermined_S0_R2_001.fastq.gz --bc-pattern=(?P<cell_1>.{7})(?P<umi_1>.{8}) --read2-in Undetermined_S0_R1_001.fastq.gz --bc-pattern2=(?P<discard_1>.{3})(?P<cell_2>.{4}).* --extract-method=regex --set-cell-number=192 --log2stderr --plot-prefix plot
>  job started at Tue May 14 10:59:00 2019 on risoe-r08-cn275 -- b77a3b3b-da7d-4b54-9bd6-d5faeb27c379
>  pid: 20098, system: Linux 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64
>  blacklist_tsv                           : None
>  cell_number                             : 192
>  compresslevel                           : 6
>  error_correct_threshold                 : 1
>  expect_cells                            : False
>  extract_method                          : regex
>  filter_cell_barcodes                    : False
>  log2stderr                              : True
>  loglevel                                : 1
>  method                                  : reads
>  pattern                                 : (?P<cell_1>.{7})(?P<umi_1>.{8})
>  pattern2                                : (?P<discard_1>.{3})(?P<cell_2>.{4}).*
>  plot_prefix                             : plot
>  prime3                                  : None
>  random_seed                             : None
>  read2_in                                : Undetermined_S0_R1_001.fastq.gz
>  short_help                              : None
>  stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='ANSI_X3.4-1968'>
>  stdin                                   : <_io.TextIOWrapper name='Undetermined_S0_R2_001.fastq.gz' encoding='ascii'>
>  stdlog                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='ANSI_X3.4-1968'>
>  stdout                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='ANSI_X3.4-1968'>
>  subset_reads                            : 100000000
>  timeit_file                             : None
>  timeit_header                           : None
>  timeit_name                             : all
>  whitelist_tsv                           : None
> Traceback (most recent call last):
>   File "/services/tools/anaconda3/4.4.0/lib/python3.6/site-packages/umi_tools/whitelist.py", line 227, in main
>     options.pattern2 = regex.compile(options.barcode_regex2)
> AttributeError: 'Values' object has no attribute 'barcode_regex2'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/services/tools/anaconda3/4.4.0/bin/umi_tools", line 11, in <module>
>     sys.exit(main())
>   File "/services/tools/anaconda3/4.4.0/lib/python3.6/site-packages/umi_tools/umi_tools.py", line 50, in main
>     module.main(sys.argv)
>   File "/services/tools/anaconda3/4.4.0/lib/python3.6/site-packages/umi_tools/whitelist.py", line 228, in main
>     except regex.Error:
> AttributeError: module 'regex' has no attribute 'Error'

**Comment by IanSudbery** [comment]
Hi Magali,

Could you check which version of UMI-Tools you are using? I think you are not using the most recent, which would be version 1.0.0. You should be able to tell with `umi_tools --version` (unless the version is VERY old).

**Comment by magali** [comment]
Thanks for your quick reply. I guess it's an old version then..  

Here is what I get with umi_tools --version:

> Traceback (most recent call last):
>   File "/services/tools/anaconda2/4.4.0/bin/umi_tools", line 11, in <module>
>     sys.exit(main())
>   File "/services/tools/anaconda2/4.4.0/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 46, in main
>     (file, pathname, description) = imp.find_module(command, [path, ])
> ImportError: No module named --version

And if I do umi_tools whitelist --version

> whitelist version: $Id$

What's the best way to upgrade? Thanks.

**Comment by IanSudbery** [comment]
Since you appear to be using (ana)conda, then `conda install
umi_tools=1.0.0` should do the trick.

**Comment by magali** [comment]
I tried that, without success. Do you have a pip install?

 conda install umi_tools=1.0.0

> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - umi_tools=1.0.0
> 
> Current channels:
> 
>   - https://repo.anaconda.com/pkgs/main/linux-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/free/linux-64
>   - https://repo.anaconda.com/pkgs/free/noarch
>   - https://repo.anaconda.com/pkgs/r/linux-64
>   - https://repo.anaconda.com/pkgs/r/noarch
>   - https://repo.anaconda.com/pkgs/pro/linux-64
>   - https://repo.anaconda.com/pkgs/pro/noarch
>

**Comment by IanSudbery** [comment]
Ah, you need bioconda on your channel list:
`conda install umi_tools=1.0.0 -c bioconda`

We do have a pip `pip install umi_tools==1.0.0` should do it, but given you
are already using anaconda, I strongly advise against mixing package
management systems.

**Comment by magali** [comment]
Great, thank you! I now have an environment with UMI-tools version: 1.0.0. I will see if it solves my problems. Let you know. :-)

**Comment by magali** [comment]
Problem solved!! Thank you so much!! :-)

**Comment by IanSudbery** [comment]
Glad with could help.
