### ISSUE TITLE
bug testing `is_spliced` with bitwise operator `&`

### ISSUE THREAD

**Issue by bowhan** [CGATOxford/UMI-tools#337]
There appears to be a bug testing whether a read is spliced given option `--spliced-is-unique`.
https://github.com/CGATOxford/UMI-tools/blob/master/umi_tools/sam_methods.py#L503
it should have been `self.options.spliced and is_spliced` instead of `self.options.spliced & is_spliced` as any even number of `is_spliced` will give a 0, such as `True & 100`.

Test input:
```
@HD	VN:1.6	SO:coordinate
@SQ	SN:chr1	LN:248956422
@PG	ID:bwa	PN:bwa	VN:0.7.17-r1188	CL:bwa
M0_GGAGGGGG	0	chr1	689250	0	262M	*	0	0	*	*	NM:i:0
M1_GGAGGGGG	0	chr1	689250	0	69M193S	*	0	0	*	*	NM:i:0
M2_GGAGGGGG	0	chr1	689250	0	70M192S	*	0	0	*	*	NM:i:0
M3_GGAGGGGG	0	chr1	689250	0	71M191S	*	0	0	*	*	NM:i:0
```

Output, with `--spliced-is-unique`
```
M2_GGAGGGGG	0	chr1	689250	0	70M192S	*	0	0	*	*	NM:i:0
M3_GGAGGGGG	0	chr1	689250	0	71M191S	*	0	0	*	*	NM:i:0
```

After changing `&` to `and`:
```
M0_GGAGGGGG	0	chr1	689250	0	262M	*	0	0	*	*	NM:i:0
M1_GGAGGGGG	0	chr1	689250	0	69M193S	*	0	0	*	*	NM:i:0
M2_GGAGGGGG	0	chr1	689250	0	70M192S	*	0	0	*	*	NM:i:0
M3_GGAGGGGG	0	chr1	689250	0	71M191S	*	0	0	*	*	NM:i:0
```

**Comment by IanSudbery** [comment]
Thanks for catching this! We appreciate your contribution.
