### ISSUE TITLE
Issue in grouping UMIs by alignment coordinates

### ISSUE THREAD

**Issue by Daniel-Liu-c0deb0t** [CGATOxford/UMI-tools#343]
Assume that UMI-tools dedup is used with default settings except for `-I`, `-S`, and `--umi-separator=:`. I am using example data which is available at https://cibiv.github.io/trumicount/kv_1000g.bam

When deduplicating the following two reads:
```
HWUSI-EAS1683_0035_FC:2:51:2198:5988#0:GAGTGTTAAC	0	FBtr0331927-M	1920	60	33M	*	0	0	GATATCGTTTAAATTAACCTTTATACTTTGATA	_\_`ffffffffffffffffffffffffffffc	AS:i:330	NM:i:0	XI:f:1	X0:i:1	XE:i:21	XR:i:33	MD:Z:33
HWUSI-EAS1683_0035_FC:2:91:3370:3599#0:GAGTGTTGAC	0	FBtr0415465-M	1928	2	8S4M1I17M3S	*	0	0	GGATTTGAATTTGGCTTATTTGCATAACGACCA	hhgdhhhghhhhgghhhhgfc]Kddddddfhhg	AS:i:165	NM:i:2	XI:f:0.9091	X0:i:1	XE:i:4	XR:i:22	MD:Z:5T15
```
they should end up at the same exact alignment position right? From what I can tell, the reads with the same strand (forwards), the same alignment coordinate (1920, accounting for soft clipping), and similar UMIs (GAGTGTTAAC and GAGTGTTGAC are apart by only one edit) are grouped together. However, the output of UMI-tools consists of both of the aforementioned reads. Shouldn't they be grouped together, so the output only consists of one of those two reads? Or am I missing an extra criteria that separates these two reads into different groups?

Thanks for your hard work on making UMI-tools!

**Comment by IanSudbery** [comment]
Thanks for you question Daniel. This took me a while to spot. 

This two reads are aligned to different contigs (different transcripts in this case, but of course UMI-tools can't tell this).  Transcript [FBtr0331927](http://flybase.org/reports/FBgn0284245.html) is part of the gene eEF1α1 and the transcript [FBtr0415465](http://flybase.org/reports/FBtr0415465.html) is part of the gene Abd-B-RJ. It is just co-incidence that that happen to come from base 1920 in each of these transcripts.

**Comment by Daniel-Liu-c0deb0t** [comment]
Just to confirm, that means that UMI-tools separates reads mapped to different contigs? So that implies that UMI-tools looks at the reference sequence in addition to alignment coordinate, Hamming distance, and strand?

**Comment by IanSudbery** [comment]
Yes. Genomic position is the composed of both the contig and alignment coordinate within the contig. This might not be immediately obvious from the code because contig is not part of the key to the read dictionary (I don't think), but rather the read dictionary is empty when the contig changes. I admit that this has got hard to see since the code has got so complex (used to be much simpler not so long ago), but have a look at [sam_methods.get_bundles.check_output()](https://github.com/CGATOxford/UMI-tools/blob/e8c2b47fd4e4cca144a6657c398dbeb5795c0cb7/umi_tools/sam_methods.py#L274)

**Comment by Daniel-Liu-c0deb0t** [comment]
Ah thanks. I looked over the code multiple times, but I could not see any other criteria, which was confusing. This issue is now resolved.

**Comment by IanSudbery** [comment]
Yes, the code has got difficult to read in the last few releases. If you got back to, say, v0.3.0, then the logic of get_bundles is much more obvious. E.g. https://github.com/CGATOxford/UMI-tools/blob/7805eaf51384bcbf8f8ca7bae3e202a6f6eeec56/umi_tools/umi_methods.py#L217
