### ISSUE TITLE
umi_tools count: unexpected end of file

### ISSUE THREAD

**Issue by WilliamSalvidge** [CGATOxford/UMI-tools#344]
Hey,

I'm currently trying to use UMI tools at the final stage of my single cell RNA-seq experiment to collapse my UMI reads.

My sequencing was carried out on a NextSeq, which had 4 lanes on the flow cell. I used all the lanes and there was only 1 sample so lanes are exact copies of each other.

I get 4 Read-1 and 4 Read-2 files back which I then merged so I have 1 Read-1 and 1 Read-2. I can then extract the barcode and umi's from the R1 read to the R2 header.

For some reason STAR is not able to align this merged data (giving me an error that limitOutSJcollapsed has been exceeded which I cannot solve even by setting this value very high). However, I can align the 4 R2 files if I treat them separately. I'm then able to merge my 4 BAM outputs from the alignment using samtools, put them through feature counts and then sort + index the output from that (as per the tutorial). Finally I run the umi_tool count command as per below.

**umi_tools count --wide-format-cell-counts --per-gene --gene-tag=XT --assigned-status-tag=XS --per-cell -I /path/to/input.bam -S /path/to/output.tsv.gz**

The program runs but then I when I attempt to open the output count file I get the following message.

**/path/to/file.tsv.gz: unexpected end of file**

Just wondering if there was any obvious reason why this might be? I should mention that I have been able to run the umi_tools count command successfully if I just take one aligned R2 file, run feature counts on that, sort + index the results and then run umi_tools count.

Thanks for any help!

Will

**Comment by IanSudbery** [comment]
It sounds like the command didn't successfully complete. Do you have the log file or output of the command? 

One possibility is that you are running out of memory and the job is being killed by either your operating system, or by your cluster management daemon before it finishes.

**Comment by WilliamSalvidge** [comment]
Hey, thanks for the quick reply. Find the output file attached. I can see that it only parsed up to 76 million reads when there should be about 400 million so perhaps you are right. Although I do normally get an error message saying that I've exceeded my memory when that's the case. I can try try re-running with more memory allotted see if that helps.   

[UMI_TOOLS_o7521567.txt](https://github.com/CGATOxford/UMI-tools/files/3321953/UMI_TOOLS_o7521567.txt)

**Comment by IanSudbery** [comment]
What is the output of UMI_TOOLS_e7521567.txt. 

Another possbility is that you are running up against a time limit. Which queue manager are you using. If its SGE you should be able to get the exit state of the job from `qacct -j 7521567`.

**Comment by IanSudbery** [comment]
Unfortunately the time and memory usage of UMI-tools do not scale linearly with the number of cells and reads. Working out how it does scale is difficult, but roughly speaking, it scales worst than quadratic in terms of the positions with the highest number of UMIs. Thus a 20-fold increase in the number of UMIs at the most densely populated positions is expected to lead to a worst than 400-fold increase in time and memory usage at that position. This is definitely one of the biggest draw backs to the UMI-tools algorithm. One thing I'll note is that at 400 million reads for 1300 cells, you are almost definitely over-sequencing. Over sequencing makes error correction more difficult, but also more important. 

If you are doing dropseq or 10X I definately recommend you check out `alevin` which is faster and uses less memory than UMI tools.

**Comment by TomSmithCGAT** [comment]
I'm closing this issue down due to inactivity.
