### ISSUE TITLE
turn off minimum UMI count filtering for whitelist?

### ISSUE THREAD

**Issue by scholzmb** [CGATOxford/UMI-tools#345]
So, I am using umi_tools for a purpose that's a little out of the box.  I am running umi_tools whitelist on a "representative" sequencing run, and trying to use the whitelist information to estimate the total number of UMIs in the whole pool.

The problem is that it appears that the min_threshold cannot be manually forced.  In other words, when I KNOW that I am below the sampling threshold to have >4 UMIs per barcode, umi_tools whitelist still sets min_threshold at 4 or above, and there are no options to modify that from the command line.  If I am missing something, please let me know.  If not, is there a quick set of code I can modify to output all barcodes with a manually input threshold?

**Comment by IanSudbery** [comment]
@TomSmithCGAT Is probably best placed to answer this, but my guess would be that the line you want is
https://github.com/CGATOxford/UMI-tools/blob/e8c2b47fd4e4cca144a6657c398dbeb5795c0cb7/umi_tools/whitelist_methods.py#L47

However, I wonder if whitelist is quite the tool you want for this job, and whether it might not be better solved via `extract` and then a few lines of custom code.

**Comment by TomSmithCGAT** [comment]
I'd agree with @IanSudbery that `umi_tools whitelist` is probably not the best way to address this question since it's explicitly designed to identify the most abundant cell barcodes. 

If you just want to obtain the list of UMIs across all your reads, and their counts, this can be done like so (with the required arguments passed to `extract`.
```bash
$ umi_tools extract -I infile_fastq.gz -S extract_out.gz [EXTRACT ARGUMENTS]
$ zcat extract_out.gz | paste - - - - | cut -f1 | cut -d"_" -f2 | sort | uniq -c
```

**Comment by TomSmithCGAT** [comment]
I'm closing this issue down due to inactivity.
