### ISSUE TITLE
Extracted barcode always 8 bp?

### ISSUE THREAD

**Issue by KeelyDulmage** [CGATOxford/UMI-tools#351]
I have a raw fastq dataset that I'm trying to extract barcodes from. Just doing grep I know that at least 1 million reads have my adapter/barcode on them.  

I run the following:
`umi_tools whitelist -I test_R1.fastq --bc-pattern='NNNNNAGATCGGAAGAGCACACGTCTGAACTCC' --set-cell-number 1000 --log2stderr > whitelist.txt`
And get: 
> 2019-07-16 14:35:57,987 INFO 2522464 reads matched the barcode pattern
2019-07-16 14:35:57,988 INFO Found 26188 unique cell barcodes
2019-07-16 14:35:57,988 INFO Found 1608969 total reads matching the selected cell barcodes
2019-07-16 14:35:57,988 INFO Found 123065 total reads which can be error corrected to the selected cell barcodes

However, if I look at the whitelist I see this:
> GCAAAAAA        ACAAAAAA,CCAAAAAA,GAAAAAAA,GGAAAAAA,GTAAAAAA,TCAAAAAA   3543    4,17,201,170,37,4
GCAAAAAC        ACAAAAAC,CCAAAAAC,GAAAAAAC,GGAAAAAC,GTAAAAAC    1111    4,2,143,42,33
GCAAAAAG        ACAAAAAG,CCAAAAAG,GAAAAAAG,GGAAAAAG,GTAAAAAG,TCAAAAAG   2665    2,4,71,34,4,3
GCAAAAAT        ACAAAAAT,CCAAAAAT,GAAAAAAT,GGAAAAAT,GTAAAAAT    1106    2,2,74,28,40
GCAAAACA        ACAAAACA,CCAAAACA,GAAAAACA,GGAAAACA,GTAAAACA    1819    4,4,90,9,89
GCAAAACC        CCAAAACC,GAAAAACC,GGAAAACC,GTAAAACC     622     2,82,27,50

Where all of the barcodes are 8 bp.  If I run umi_tools extract on this dataset the barcodes in the headers all look something like this: 
>CTCTATTC_GCTGAAG 

where the second part is invariant

In real life my barcode is actually N5-N7.  I can't seem to get the regex extract working at all, I get all sorts of fun errors.  But I _was_ able to run: 
`umi_tools whitelist -I MU4_R1.fastq --bc-pattern='N{5,7}AGATCGGAAGAGCACACGTCTGAACTCC' --set-cell-number 1000 --log2stderr > whitelist.txt`

-which seemed to work - I'm interested if the hybrid string is kosher or not.  In any case, even with the number of Ns designated as 5-7 I was still getting 8 bp barcodes.  

I'm running version 1.0.0 and have updated all of the dependencies.

So why are the barcode outputs 8 bp?

Thanks,

-Keely

**Comment by IanSudbery** [comment]
Hi Keely,

In string mode, for barcode pattern definition, and N stands for a UMI position, a C for a Cell barcode position and all other characters are ignored. 

The sequence you are passing to bc-pattern has 8 Cs in it, and so these are being extracted and used as cell barcode nucleotides. Another way of putting this is that your pattern is equivalent to:

```
NNNNNNXXXXXCXXXXXXXCXCXCXXCXXXXCXCC

```

So you have 6 UMI bases and 8 cell barcode bases scatter amongst the rest of the sequence.

**Comment by KeelyDulmage** [comment]
Ah! I somehow didn't catch this in the documentation, thank you!
