### ISSUE TITLE
group/dedup by position not gene

### ISSUE THREAD

**Issue by laurapspector** [CGATOxford/UMI-tools#352]
I would like to group reads with the same UMI that align to roughly the same position on the same chromosome, within some reasonable distance. I'm not using the --per-gene/featureCounts options because I'm interested in any and all positions to which my reads align. Is there a way to do this?

**Comment by IanSudbery** [comment]
If you just leave off the `--per-gene` option, then this is what UMI-tools does. The only difference from what you are asking is that start positions must be identical, rather than roughly the same.

**Comment by laurapspector** [comment]
Is there a recommended tool for merging reads within a certain distance that also have the same UMI?

**Comment by IanSudbery** [comment]
As far as I know, no such tool exists.
