### ISSUE TITLE
inDrop scRNAseq low % of reads with cell barcodes 

### ISSUE THREAD

**Issue by BhaktiDwivedi** [CGATOxford/UMI-tools#353]
Thank you for this great tool! I have using it to analyze inDrop (1CellBio) scRNA-seq data (35 bp) with raw yield of ~100 million reads per sample (I have 4 samples total).

### I run umi-tools 'whitelist' to identify the correct cell barcodes:
`umi_tools whitelist --extract-method=regex --bc-pattern="(?P<cell_1>.{8,12})(?P<discard_1>GAGTGATTGCTTGTGACGCCTT){s<=2}(?P<cell_2>.{8})(?P<umi_1>.{6})T{3}.*" --stdin s1_read2.fq --expect-cells=3000 --plot-prefix s1 --log2stderr`

With this, I have 23% of reads matching rgex & 77% reads that do not. Is this % really low? I tried to increase the number of mismatches but that didn't help much. Is this an acceptable range for inDrop scRNAseq data? From this I have about ~445 cells / sample

### Then I run extract barcodes and UMIs and add to read names
`umi_tools extract --extract-method=regex --bc-pattern="(?P<cell_1>.{8,12})(?P<discard_1>GAGTGATTGCTTGTGACGCCTT){s<=2}(?P<cell_2>.{8})(?P<umi_1>.{6})T{3}.*" --error-correct-cell 1 --stdin s1_read2.fq --stdout extracted_s1_read2.fq --read2-in s1_read1.fq --read2-out=extracted_s1_read2.fq --filter-cell-barcode --whitelist=s1_whitelist.txt -L s1_extract_log.txt`

With this, I am further down to ~14% of reads with cell barcode. Although, it is almost ~60% of 23% reads with matching regex that have cell barcode, but am wondering is 10-15% expected?

Then I map these 14% reads with STAR and have almost 70% of them uniquely mapped, remaining mapping to too many loci (of course it is short read length). So this seemed to be alright.

### Lastly I counted UMI's per gene per cell
`umi_tools count --per-gene --gene-tag=XT --assigned-status-tag=XS --per-cell -I s1_Aligned.sortedByCoord.out.bam.assigned_sorted.bam -S s1_counts.tsv.gz --wide-format-cell-counts --log=s1_count_log.txt`

This results in a considerable amount of reads (~75%) not counted. Only About 7% of reads are counted towards, and ~18% of reads skipped, without tag. This really concerned me. Is this really correct? Hope I am not missing something here.

I would greatly appreciate your help and any suggestions. 

Thank you so much.

**Comment by IanSudbery** [comment]
I don't personally have much experience with inDrop, although I believe @TomSmithCGAT has run some inDrop samples before.  However, I am surprised by how many of your reads do not match the regex. Did you get that regex from our FAQ? Is it possible that 1CellBio uses a slightly different sequence/configuration? 

I'm not particularly worried about the number of reads that match to selected cells given the number of reads that match the barcode. 

For your last point about the counting - if by the 7% you are referring to the post-deduplication outputs, then this is also normal - scRNA samples are generally heavily duplicated, hence the need for UMI-tools. In our test set for example, we keep 11% of reads.

So the thing that worries me here is the number of reads not matching to the regex at the start.

**Comment by BhaktiDwivedi** [comment]
Thank you so much for your quick response. Yes the regex is from the FAQs and I double checked it. In fact majority of the reads that do not match regex have no polyT sequence at the end or may be one or two instead of three in the pattern. So I ran the below just to see..

`umi_tools whitelist --extract-method=regex --bc-pattern="(?P<cell_1>.{8,12})(?P<discard_1>GAGTGATTGCTTGTGACGCCTT){s<=2}(?P<cell_2>.{8})(?P<umi_1>.{6}).*" --stdin s1_read2.fq --expect-cells=3000 --plot-prefix s1 --log2stderr`
###With this, I almost get 60% reads matching the bc pattern. Is this correct to do it this way?

Also, I do have the 384 barcode 1 and barcode 2 sequences from 1CellBio (
[Barcode.seqs.txt](https://github.com/CGATOxford/UMI-tools/files/3406577/Barcode.seqs.txt). Do you think this can make a difference? If so, is there a way I can input this in the `umi-tools extract` instead of using '`whitelist'` to identify more cell barcodes from the data? 

The 7% is not post-duplication. I didn't run de-duplication yet. Is that really necessary? I wonder how much data I will be left with.

Again Thanks!

**Comment by IanSudbery** [comment]
If most of your reads don't have the polyT at the end, then I guess you should leave that out. You might also consider changing the `{s<=2}` to `{e<=2}`, which would allow indel errors in the discard sequence as well as substitution errors. 

If you want to use your own list of barcodes in `extract` rather than the `whitelist` determined one, then you can provide these to `extract` white list option of extract. To do that, you'd need to build all pairwise combinations of the two lists of barcodes. The python for that might look like:

```
import itertools
bc1s = list()
bc2s = list()

for line in open("Barcore.seqs.txt"):
    fields = line.strip().split()
    bc1s.append(fields[0])
    bc2s.append(fields[1])

with open("allowed_barcodes.txt", "w") as outf:
    for bc1, bc2 in itertools.product(bc1s, bc2s):
        outf.wirte(bc1 + bc2 + "\n")

```

If you got the 7% from the output of `umi_tools count` then that is post-deduplication as `count` automatically deduplicates as it goes.

**Comment by BhaktiDwivedi** [comment]
Thank you for all your help! I am excluding the polyT from the regex pattern. That seems to be making a big difference in this data set. Including both substitutions and indel errors allowed only a subtle increase of ~0.002%. Using all pairwise comparisons (384 x 384) of 1CellBio barcodes in `extract` didn't give any different results from `whitelist `regardless of changes in the bc pattern, but still good to know. Thank you for the clarification on the `count` post-deduplication.

**Comment by IanSudbery** [comment]
Hi Bhakti, I'm closing this issue for now. Feel free to reopen if you need.
