### ISSUE TITLE
how to extract UMI barcode from .FASTQ file(GSM3139597)?

### ISSUE THREAD

**Issue by modarzi** [CGATOxford/UMI-tools#356]
Hi, I need to remove degenerate sequence (N4) at the 5' and 3' of the reads. my target is GSM3139597. So for extracting UMI from .fastq, I install UMI tools. Now, I have to extract GSM3139597 from UMI barcode. based on [instruction](https://umi-tools.readthedocs.io/en/latest/reference/extract.html), for the single-end read, I have to use the below code:

`umi_tools extract --extract-method=string --bc-pattern=[PATTERN] -L extract.log [OPTIONS]`.

I need a guide for handling GSM3139597 as input in that code. In other words, I don't know how can I use that code for solving my problem. I don't know how can I prepare arguments of that code relate to my GSM?

**Comment by IanSudbery** [comment]
Probably the easiest way to do this would be to use the `regex` method to specify the read layout. 

Thus the `extract-method` would be regex, and your pattern would look like:

`(?P<umi_1>.{4}).+(?P<umi_2>.{4})`

**Comment by modarzi** [comment]
Dear @IanSudbery , Thanks for your comment. based on your comment I have to run below code:

`umi_tools extract --extract-method=regex --bc-pattern=(?P<umi_1>.{4}).+(?P<umi_2>.{4})  -L extract.log `
my main question is how can I find this pattern for other GSMs?my data sets are in GSE114330 and GSE114366.

**Comment by IanSudbery** [comment]
In general there is no standard way to find the pattern from the GSM record. Here I looked at the record and saw that they used the NEXTFLEX small RNA prep library and when and read the manual for this. I was that each read has 4Ns on the end of each read and composed the regular expression to find this. 

There are many guides on how to create regular expressions on the internet. The basics are explained on the documenation here:
https://umi-tools.readthedocs.io/en/latest/regex.html#regex-regular-expression-mode

**Comment by modarzi** [comment]
Dear @IanSudbery I also found [NEXTflex™ Small RNA-Seq Kit v3](https://perkinelmer-appliedgenomics.com/wp-content/uploads/marketing/NEXTFLEX/miRNA/5132-05-NEXTflex-Small-RNA-Seq-v3-18-07.pdf) that in the data analysis section has been written:

>  The 3' and 5' adapters included in this kit both contain 4 random bases that will appear immediately 5' and 3' to the insert in sequencing data. The presence of these random bases should be considered when choosing an alignment strategy. When using the “end-to-end” alignment, we recommend processing data in the following manner: 
> 1. Clip the 3' adapter sequence (TGGAATTCTCGGGTGCCAAGG). 
> 2. Trim the first and last 4 bases from the adapter-clipped reads. 
> 3. Perform alignments as normal.

and I think it has a conflict with https://umi-tools.readthedocs.io/en/latest/regex.html#regex-regular-expression-mode

I am confused. could you please share your comment with me

**Comment by IanSudbery** [comment]
I'm not sure I see any conflict. The post to the umi-tools documentation is instructions for how to craft a regex to deal with any library. The instructions for the NEXTFlex library are for that specific library and were written without any knowledge of UMI-tools. 

You should process the reads to trim the 3' adaptor sequence using your favourity adaptor trimmer. For example `cutadapt` is used by the the depositors of your GSE. (This is step one in the process outlined above).

The second step of the process in the NEXTflex data analysis section is to trim the first and last 4 bases of the adaptor clipped reads. In this protocol those bases are discarded. However, it looks like the depositors of the GSE you quote realised that as these bases were random bases, they could be used as a UMI, and used UMI-tools to remove them from the ends of the read and put them on the read name. To do this it is neccessary to tell UMI-tools that the "UMI" is the first and last 4 bases of the read.

In regex we specify any 4 bases as `.{4}`. In UMI-tools we specify bases to be captured by creating a named capture group, so a named capture group that captures 4 bases as the first part of a UMI would be `(?P<umi_1>.{4})`. We start our pattern with this to specify that we want to capture the first 4 bases of the read. If we wanted to make sure this was anchored at the start of the read, we can make doubly sure by adding a `^` to the start. `^(?P<umi_1>.{4})` We then need a similar capture group at the end of the read to capture the last 4 bases of the read as the second part of the UMI `(?P<umi_2>.{4})`. We can make doubly sure that is anchored at the end of the read by adding a `$`: `(?P<umi_2>.{4})$`. All we need now is to connect the the two together by any number of other bases to give:

`^(?P<umi_1>.{4}).+(?P<umi_2>.{4})$`

Interestingly while the depositors of the GSE use UMI-tools to grab the first and last 4 bases of the read as a "UMI", they don't appear to actually use that UMI for anything in their downstream pipeline. Unless they have an `umi_tools dedup` step that they have forgotten to include in their methods.

**Comment by modarzi** [comment]
Dear @IanSudbery I run below code for extracting UMI barcode from  _GSM3139598_  :
` umi_tools extract --extract-method=regex --bc-pattern="(?P<umi_1>.{4}).+(?P<umi_2>.{4})" --stdin=SRR7155063_1.fastq.gz --stdout=SRR7155063_1_Extract.fastq -L SRR7155063_1_extract.log`

but I got below error:
```
Traceback (most recent call last):
  File "/usr/local/bin/umi_tools", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/umi_tools/umi_tools.py", line 58, in main
    module = importlib.import_module("umi_tools." + command, "umi_tools")
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/umi_tools/extract.py", line 158, in <module>
    import umi_tools.extract_methods as extract_methods
  File "/usr/local/lib/python2.7/dist-packages/umi_tools/extract_methods.py", line 7, in <module>
    import umi_tools.Utilities as U
ImportError: No module named Utilities
```
can you give me any suggestions for solving this error?

**Comment by IanSudbery** [comment]
Hi @modarzi : You are running `UMI-tools` in python 2.7. As of version 1.0.0 we only support python 3.

**Comment by modarzi** [comment]
Dear @IanSudbery: Ok,I had python3 and now l link to that but I got below error:
```
Traceback (most recent call last):
  File "/usr/local/bin/umi_tools", line 6, in <module>
    from umi_tools.umi_tools import main
ImportError: No module named 'umi_tools'

```
Could you please give me your comment?

**Comment by IanSudbery** [comment]
Once you have python3, you need to install umi_tools in the python3 environment. You can do this with either pip or conda. We usually recommend conda, but since you are working with a system install python, try pip.

**Comment by TomSmithCGAT** [comment]
I'm closing this due to low activity. Please re-open if this issue still needs to be resolved
