### ISSUE TITLE
dedup determinisitc - use a seed?

### ISSUE THREAD

**Issue by RichardCorbett** [CGATOxford/UMI-tools#362]
Hi there,

When I run this command multiple times:
{code}
umi_tools dedup -I myBam.bam --extract-umi-method=tag --umi-tag=RX --read-length -S myBam.umi_tools.bam
{code}

I get the same number of reads returned each time, but the exact reads returned each time are different.  Is there a way to get the same reads with each run?

thanks
RIchard

**Comment by IanSudbery** [comment]
To use a seed with `umi-tools`, use the `--random-seed=` option. 

You might also find you need to set the `PYTHONHASHSEED=` environment variable as well to make sure hashes are returned in the same order, although I think the sorts should take care of that these days....

This is how we run our tests:

```
#!/use/bin/env bash
export PYTHONHASHSEED=0
umi_tools dedup --random-seed=123456789 .......
```

**Comment by RichardCorbett** [comment]
Perfect. Thanks.  Sorry I somehow missed this myself.

**Comment by IanSudbery** [comment]
I'm closing this. Please reopen if you need more advice.
