### ISSUE TITLE
How to keep UMI barcode in read1 when using extract command?

### ISSUE THREAD

**Issue by ianyfchang** [CGATOxford/UMI-tools#364]
Hi, 
When I use UMI-tools extract to identify a set of white-list barcode from FASTQ files, the extract command will cut the barcodes from read1 and put them to their corresponding read names.
Does it have any option in extract command to report original reads instead of trimmed ones?
Thank you.

**Comment by TomSmithCGAT** [comment]
There is a hidden argument for `extract` to retain the UMI in the read sequence: `--retain-umi`. You will also need to use `--extract-method=regex` to enable the UMIs to be retained.

This argument is currently hidden as it's not covered by tests.

**Comment by IanSudbery** [comment]
TIL

**Comment by TomSmithCGAT** [comment]
@IanSudbery - Yeah sorry, that ones been in there for a while for personal use 😉 (#218)

**Comment by ianyfchang** [comment]
Wow, I should also search closed pull request next time. 🤣
Thank you for the information, it really helped.
