### ISSUE TITLE
Keeping unassigned reads with umi-tools group

### ISSUE THREAD

**Issue by alex-d13** [CGATOxford/UMI-tools#369]
Hello everyone,

is there a way to keep the unassigned reads in the output bam-file, when starting umi_tools group with --per-gene? I only found the --skip-tags option, which I changed to "^[__]", but i still do not get them in my output.
Can anybody help me here?

Cheers, 
Alex

**Comment by TomSmithCGAT** [comment]
Hi @alex-d13 - Sorry that your question didn't get a response.

No, there's no option currently to retain reads without an assigned gene when using `--per-gene`
