### ISSUE TITLE
Failed to install with pip

### ISSUE THREAD

**Issue by KaiyangZ** [CGATOxford/UMI-tools#37]
Hi,

I was trying to install umi-tools with "pip install umi_tools", but it failed with the error "IOError: [Errno 2] No such file or directory: 'requirements.txt'", do you have an idea how to fix it? 

Thanks!

--Kaiyang

**Comment by IanSudbery** [comment]
Hi @TomSmithCGAT - looks like requirements.txt is missing from the latest pypy version. Also, its downloading and installing 0.10.0 rather (which I think is a typo and should be 0.0.10?) rather than 0.2.0. I don't have the credentials for pypy, so I wonder if you could fix this?

Ian
---

**Comment by TomSmithCGAT** [comment]
Hi @IanSudbery. This is odd. I'll have a look at this tomorrow.

**Comment by TomSmithCGAT** [comment]
Hi @KaiyangZ This should be fixed in the latest version (0.2.3). Please can you use pip install umi-tools==0.2.3 and let me know if you have any problems

**Comment by TomSmithCGAT** [comment]
@IanSudbery You're right about the misnaming. Pypi wouldn't update the version name so I've deleted this release entirely

**Comment by KaiyangZ** [comment]
Hi @TomSmithCGAT , it works fine now, thanks a lot!
