### ISSUE TITLE
umi tools count in bins

### ISSUE THREAD

**Issue by vivekbhr** [CGATOxford/UMI-tools#373]
Hi umi_tools team

It would be great to able able to count in bins, or count using a given bed file, resolving the UMI and cell barcode. Would you consider adding this feature?

Thanks,
Vivek

**Comment by IanSudbery** [comment]
At the moment UMI-tools doesn't do any assigning of reads to features - we leave that to third party tools. However, you could do this by using featureCounts to assign reads to your bins, and then use UMI-tools in `--per-gene` mode to collapse within these assignments.
