### ISSUE TITLE
Update docs to indicate Python 3 requirement

### ISSUE THREAD

**Issue by mluypaert** [CGATOxford/UMI-tools#375]
The docs need some updates to indicate the current version requires Python 3(.5+ I estimate) and does no longer support python 2.7 (currently is states the tool requires 2.7+ and mention the use of `pip`(2) instead of `pip3`)

**Comment by IanSudbery** [comment]
Thats for noticing that! Should now be corrected. Note that `pip3` isn't a standard name, and on most systems with python 3, `pip` should point to the version that uses python 3 (where `pip3` is available, i think its generally just a soft link to `pip` in the python3 bin directory).  I've added a note that if `pip` doesn't work, users might like to try `pip3`.
