### ISSUE TITLE
cell barcode question

### ISSUE THREAD

**Issue by skytguuu** [CGATOxford/UMI-tools#376]
Hi,

Recently I tried to analyze scRNA-seq data produced by mcSCRB-seq. Because I have valid cell barcode file, so I did not need to identify the cell barcode in step2. Is any possible your tool could use the reference barcode file to extract the reads? I tried use " umi_tools extract" with --whitelist=MY_REF_INDEX, however it still failed.
Could you give me some suggestions?

Thank you!

**Comment by IanSudbery** [comment]
If the files is the correct format, then this should have worked. Can you expand a bit further on "failed"?

**Comment by skytguuu** [comment]
Hi,
My input "MY_REF_INDEX" file is as followed:
######
CATGAG
TCGAAG
CTGTAC
TGCATG
AGTGAG
TCCTCA
#######
After I finished the extract step with the previous command, the result of fastq file contained nothing reads. So, I am curious about this problem.

**Comment by IanSudbery** [comment]
By "nothing reads", do you mean it contained no reads, or that it contained reads with nothing in them. 

Can you should me the command you ran and an example of a read?

**Comment by skytguuu** [comment]
Thanks for your help. This problem I think I fixed with used old version 0.5.5, perhaps my python is 2.7. But, I am confused about the final result ("counts.csv.gz"). Because I tried to use my python script to split the index from my fastq file, then use star to mapping reads and featurecounts to count. However, I found the result is different with "umi_tools". It seemed umi_tools has less count in each genes (all paramenters are the same). I think the only different is in the process of counting molecules. My own step is finished at the featurecounts step, while your further to use aligned again. Is that meaning my step is including many pcr duplicates, while your removed those duplicates?
Could you give me some suggestion?

Thank you!

**Comment by IanSudbery** [comment]
Yes, the main role of UMI-tools in the single cell analsysis pipeline is to deal with the PCR duplicates using the UMIs. For mcSCRB-seq, you assign reads to genes, and then count in per gene mode.

UMI-tools will look at all the reads that map to a particular gene in a particular cell and group together all those with the same UMI. It will then examine those UMIs and group together those UMIs that are likely to have arisen from another UMI by a PCR or sequencing error, finally, if you are using `count`, then the number of remaining groups associated with each gene is counted.

**Comment by skytguuu** [comment]
Thanks for your explaination. It makes me sense.

Thank you!
