### ISSUE TITLE
regex syntax

### ISSUE THREAD

**Issue by morellr** [CGATOxford/UMI-tools#379]
I'm having trouble running extract-method=regex. Specifically, I've tried many different ways of writing the syntax, but they all give me the same error message:  
" bash: syntax error near unexpected token `(' "
For example,
$ umi_tools extract --extract-method=regex --bc-pattern=(?P<umi_1>.{13}TCCTGAGCGAAG).+$ -I Lib4rcv2.fastq -S Lib4rcv2UMI.fastq -L extract.log
 
Can you tell me what I'm doing wrong?

**Comment by IanSudbery** [comment]
You need quotes (probably single quotes) around your regex.

**Comment by morellr** [comment]
Thanks for your quick reply, and sorry to have bothered you with a trivial error.

**Comment by IanSudbery** [comment]
No worries, glad to have helped.
