### ISSUE TITLE
AssertionError: not all umis are the same length(!):  57 - 58

### ISSUE THREAD

**Issue by TendoLiu** [CGATOxford/UMI-tools#380]
Hi I am using working on UMI collapsing of illumina DNAseq data. The fastq file has UMI info in the read name like 
"@NS500211:808:HW27KAFXY:1:11101:12228:1057:TATGTNC+NNGAGCA 1:N:0:TCCGGAGA"
 but when I tried to run dedup, 
umi_tools dedup \
-I $bam1 \
--output-stats=deduplicated -S deduplicated.bam

there came an error : AssertionError: not all umis are the same length(!):  57 - 58

**Comment by TomSmithCGAT** [comment]
Hi @TendoLiu - The UMI lengths (57-58) sound too long. How are you extracting the UMIs prior to alignment? Could you post a couple of lines from the BAM here as well please.

**Comment by TendoLiu** [comment]
Another question: according to documentation: 
"It is assumed that the FASTQ files were processed with umi_tools extract before mapping and thus the UMI is the last word of the read name.”
"If you have used an alternative method which does not separate the read id and UMI with a “_”, such as bcl2fastq which uses “:”, you can specify the separator with the option --umi-separator=<sep>, replacing <sep> with e.g “:”.  "
If the read name is "@NS500211:808:HW27KAFXY:1:11101:12228:1057:TATGTNC+NNGAGCA 1:N:0:TCCGGAGA", which part will dedup recognize as the last word of the read name? "TATGTNC+NNGAGCA" or "TCCGGAGA"?

**Comment by TendoLiu** [comment]
> Hi @TendoLiu - The UMI lengths (57-58) sound too long. How are you extracting the UMIs prior to alignment? Could you post a couple of lines from the BAM here as well please.

Thank you so much for the quick reply. I should have included "--umi-separator=":" " option. Now I figured this out. Could you please have a look at the second question?

**Comment by TomSmithCGAT** [comment]
The read name above appears to be from the fastq (based on the `@` prefix). In the BAM, I expect the read name will be `@NS500211:808:HW27KAFXY:1:11101:12228:1057:TATGTNC+NNGAGCA`, since aligners normally remove any characters after the first whitespace. In this case, `umi_tools dedup --umi-separator="+"` should correctly extract `NNGAGCA`as the UMI.

**Comment by TomSmithCGAT** [comment]
I'm closing this issue due in inactivity. Please re-open if the above has not been resolved
