### ISSUE TITLE
API example returns error on edit_distance calls

### ISSUE THREAD

**Issue by matandro** [CGATOxford/UMI-tools#383]
Run the simple example code:
```
from umi_tools import UMIClusterer
umis = {"ATAT": 10,
        "GTAT": 5,
        "CCAT": 3}

clusterer = UMIClusterer(cluster_method="directional")
clustered_combos = clusterer(dict(umis), threshold=1)
```

The following exception is given for each call to edit distance:
```
Exception ignored in: 'umi_tools._dedup_umi.edit_distance'
TypeError: expected bytes, str found
```

I ran the code on a docker container with python 3.6. umi_tools was installed using pip install.
Obviously even though the exception is ignored the response is all the sequences in the same cluster

**Comment by shuyuzheng** [comment]
I met the same issue by using python 3.7.1 on a CentOS Linux machine. UMI-tools was installed by pip.

**Comment by IanSudbery** [comment]
Sorry, I think this is a problem in updating the code without updating the documentation. 

The keys on the umi dict need to be byte strings (i.e. type `byte`), rather than decoded strings (type `str`). You can do this as follows:

```
from umi_tools import UMIClusterer
umis = {b"ATAT": 10,
        b"GTAT": 5,
        b"CCAT": 3}

clusterer = UMIClusterer(cluster_method="directional")
clustered_combos = clusterer(umis, threshold=1)
```

I'll update the documentation

Ian

**Comment by shuyuzheng** [comment]
Thanks for replying. My problem solved. It works well now for me.
