### ISSUE TITLE
Use within python script

### ISSUE THREAD

**Issue by peterch405** [CGATOxford/UMI-tools#39]
Not really an issue, more of a question. I am trying to run umi_tools with a python script and instead of using `subprocess` I just imported it:

```
from umi_tools import extract
extract.main(['-I', '/path/to/input.fastq', 
              '-S', path/to/output.fastq', 
              '-p', 'NNNNNNXXXXXXX', 
              '-L', '/path/to/log', 
              'read2_in', '/path/to/input_2.fastq', 
              'read2_out', 'path/to/output_2.fastq'])
```

But it only outputs an empty file. Any suggestions on what I am doing wrong? Thank you.

**Comment by TomSmithCGAT** [comment]
Hi again Peter. I've not tried running umi_tools in this way - I'll have a look and see what's going on.

**Comment by TomSmithCGAT** [comment]
@peterch405 Sorry for the very delayed response to this!

It looks like the issue is that the Utilities.Start() function removes the first option for correct option parsing when running on the command line so you need to add in a dummy argument like so:

```from umi_tools import extract
extract.main([' ', ' ', 
              '-I', '/path/to/input.fastq', 
              '-S', path/to/output.fastq', 
              '-p', 'NNNNNNXXXXXXX', 
              '-L', '/path/to/log', 
              'read2_in', '/path/to/input_2.fastq', 
              'read2_out', 'path/to/output_2.fastq'])
```
