### ISSUE TITLE
How I can get the UMI extraction

### ISSUE THREAD

**Issue by yueli711** [CGATOxford/UMI-tools#390]
Hello, 

Thank you so much for developing so nice UMI_tools software!

I followed the https://umi-tools.readthedocs.io/en/latest/QUICK_START.html.

Right now, I have files:

processed.fastq.gz, example.bam,  example.bam.bai, deduplicated.bam, deduplicated_edit_distance.tsv, deduplicated_per_umi.tsv, deduplicated_per_umi_per_position.tsv.

How I can get the UMI extraction file?

Thanks in advance!

Best,

Yue

UMI extraction file:

@HISEQ:87:00000000_GGTT read1
TGATTGGATGGGCTAG
1AFGGCG01DFH00B1FF0B
+

**Comment by IanSudbery** [comment]
The `processed.fastq.gz` contains the the reads with the UMIs extracted. What you included in the above is an example of a single read from an imaginary example file with the UMI removed from the read sequence and added to the read name.

**Comment by yueli711** [comment]
Hello, lanSudbery,

Thank you so much for your response! This quick start guide uses an iCLIP dataset as an example.

Best,

Yue

**Comment by IanSudbery** [comment]
If you are interested in analysing single cell data, I recommend the single cell guide.  https://umi-tools.readthedocs.io/en/latest/Single_cell_tutorial.html
