### ISSUE TITLE
How to specify --umi-tag in dedup

### ISSUE THREAD

**Issue by yh154** [CGATOxford/UMI-tools#392]
Hi, 
I have a bam contains 10x reads uniquely mapped to genome from Starsolo. The cell barcodes and UMI were not added to reads' names before mapping, rather kept in bam under tags: "CB" and "UB". I want to get a deduplicated bam using umi-tools dedup, but having difficulties to tell umi-tools where and how to find the cell barcode and UMI. I tried a number of ways to specify "-umi-tag", "umi-tag-split" and "umi-tag-delimiter" without success. I will appreciate it very much if you could provide some help.

**An alignment record looks like:** 
NS500269:884:HK2TNBGXC:4:22509:23646:18423	0	1	23199	255	9M36064N16M	*	0	0	AAAATAATTCTATCGGTTAGCTGAA	EEEE6EEEEAEEE6EE/E////</E	NH:i:1	HI:i:1	AS:i:19	nM:i:1	RE:A:I	xf:i:0	li:i:0	CR:Z:CCTAACACACCAAATG	CY:Z:/AA/AEEAE//EEA6/	UR:Z:TATGTAAACTAT	UY:Z:EEE6E66E//E/	UB:Z:TATGTAAACTAT	RG:Z:Sample1:0:1:HK2TNBGXC:4

**command** 
$umi_tools dedup --extract-umi-method=tag  --cell-tag=CB --umi-tag=UB -I Input.bam --output-stats=deduplicated -S output.bam 

**Error**:
File "pysam/libcalignedsegment.pyx", line 2437, in pysam.libcalignedsegment.AlignedSegment.get_tag
KeyError: "tag 'UB' not present"

**Comment by TomSmithCGAT** [comment]
Hi,

Is there any possibility that you have reads without UMIs? 

The calls to `get_tag` for the UMIs are wrapped in a `try except` so I'm surprised to see the above error message. Could you post the full traceback which should indicate where the error arises within UMI-tools.

Thanks

**Comment by yh154** [comment]
Traceback (most recent call last):
  File "/Users/opt/anaconda3/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/umi_tools/umi_tools.py", line 61, in main
    module.main(sys.argv)
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/umi_tools/dedup.py", line 257, in main
    barcode_getter=bundle_iterator.barcode_getter)
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/umi_tools/umi_methods.py", line 152, in __init__
    self.fill()
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/umi_tools/umi_methods.py", line 172, in fill
    self.umis[self.barcode_getter(read)[0]] += 1
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/umi_tools/sam_methods.py", line 53, in get_barcode_tag
    umi = read.get_tag(umi_tag)
  File "pysam/libcalignedsegment.pyx", line 2395, in pysam.libcalignedsegment.AlignedSegment.get_tag
  File "pysam/libcalignedsegment.pyx", line 2437, in pysam.libcalignedsegment.AlignedSegment.get_tag
KeyError: "tag 'UB' not present"

**Comment by TomSmithCGAT** [comment]
Ah, so the `try except` only catches `IndexError`s for a start so that's why you get the error message from `pysam` rather than an error message from UMI-tools. I'll come back with a patch which will output the offending read shortly. I suspect it doesn't have a UB tag.

**Comment by yh154** [comment]
You are right! I just realized that uniquely mapped read could have no UB tag in my case, which is not expected. Do you suggest to filter out these reads before running umi-tools dedup, or you think the new patch can handle it on the run, i.e. discard these reads in the dedup-ed bam output?

**Comment by TomSmithCGAT** [comment]
Personally, I would favour the filtering to be performed prior to running dedup. Thoughts @IanSudbery?

**Comment by TomSmithCGAT** [comment]
Correction to what I said earlier. We already handle reads without UMI cell tags and these are indeed just skipped and this is noted in the log file:

https://github.com/CGATOxford/UMI-tools/blob/6945f6ae5a9a7c56fdac22f2caddec4246442bc2/umi_tools/sam_methods.py#L410-L427

The traceback above indicates the issue is when parsing the input for the stats. This should also be wrapped in a `try except` to avoid issues with a `keyError` though, so I'm not sure why this error occurs:

 https://github.com/CGATOxford/UMI-tools/blob/e256083c9c82614f71c636ba43ca6f4c584b03e8/umi_tools/umi_methods.py#L173-L176

Can you confirm which version of UMI-tools you are using as it looks like you may be using 1.0.0. Updating to 1.0.1 should resolved this issue

**Comment by yh154** [comment]
I am using 1.0.0. will update to the newer version. Thanks a million for all the help!

**Comment by TomSmithCGAT** [comment]
P.s it looks like the latest version of bioconda is still 1.0.0 so you will need to install from github for 1.0.1. This is a good reminder to myself to update the bioconda version!

**Comment by TomSmithCGAT** [comment]
Pypi version has been updated. Just waiting on the review and merge for bioconda: https://github.com/bioconda/bioconda-recipes/pull/19759

**Comment by TomSmithCGAT** [comment]
1.0.1 is available via bioconda now too. If updating version doesn't resolve this issue, please re-open
