### ISSUE TITLE
Feature request- allow UMI groups to be extracted but not removed from read

### ISSUE THREAD

**Issue by ijhoskins** [CGATOxford/UMI-tools#394]
Hello,

There may be a way to do this already that I am not aware of, but I am wondering if it is possible to extract a portion of the read to the qname but also keep it in the read. For example, to increase UMI complexity, one could incorporate the initial part of the start site sequence (fragmentation/ligation site) along with a canonical UMI randomer to generate a longer and more complex molecular barcode. However, with the current logic, such start site sequence would also be removed from the read, causing loss of coverage. Is there a way to construct the regex to not discard such a pattern group?

**Comment by IanSudbery** [comment]
As far as i'm aware there is no current way to do this (although @TomSmithCGAT might correct me, sometimes there are hidden options even I'm not aware of). It wouldn't be that hard to do, but I'd question your suggested use case:

Deduplication proceeds in two ways in UMI tools - either (position + UMI) or (gene + UMI). If position + UMI, then all reads mapping to a particular location are going to have the same initial part of the read anyway, and so you would not be increasing complexity. (gene + UMI) is usually used when analysing data from a protocol where you have one or more rounds of PCR before fragmentation, and thus two copies of the same original molecule could have the same initial part of the read. In neither of these cases would including the 5' end of the read in the UMI improve deduplication.

**Comment by ijhoskins** [comment]
Thanks for the response @IanSudbery . My libraries were produced with anchored multiplex PCR https://www.nature.com/articles/nm.3729

With AMP data, we can have R2s that map to different locations with corresponding R1s that share the same UMI and position. So this seems similar to the (gene + UMI) approach you describe, yet differs from typical "opposing primer" PCR.

I planned to deal with this property by including the originating primer (start of R2) in the qname. But perhaps I don't need this modification prior to umitools and can just used the (gene + UMI) approach?

**Comment by ijhoskins** [comment]
To answer my question above: use of the fragment length along with the position (https://github.com/CGATOxford/UMI-tools/issues/357) ensures successful deduplication of libraries prepped with AMP chemistry (where multiple R2s mapping to different coordinates can pair with the same R1 UMI and start coordinate). However, if the --ignore-tlen option is used, then the user would need to deal with manually incorporating discriminatory information for R2 into the read id.
