### ISSUE TITLE
Docs request: more detailed description of outputs with dedup --output-stats option

### ISSUE THREAD

**Issue by ijhoskins** [CGATOxford/UMI-tools#395]
I took a look at the manual regarding the three output files generated with this option, but looking at the files some things are still not clear to me. The manual describes a little more in detail what the "_stats_edit_distance.tsv" columns mean, but the others are less clear.

For example, the name of the "_stats_per_umi_per_position.tsv" file suggests we should see read counts pre- and post- dedup for each [position x UMI] combination. But there are no columns that report coordinate position or UMI identity.

Similarly, for the "_stats_per_umi_per.tsv" file, it is not entirely clear the difference between the "times_observed" and "total_counts". Is the difference that the former is counts for the originating UMI whereas the latter is the total counts for the originating UMI and all variants within the cluster?

Any elaboration on the nature of these values would be much appreciated!

**Comment by TomSmithCGAT** [comment]
Hi @ijhoskins. Apologies for the delay responding to your query.

I agree the name for these files is a bit confusing. The `_stats_per_umi_per_position.tsv` file simply tabulates the counts for unique combinations of UMI and position. E.g if prior to deduplication, we have two positions in the BAM (POSa, POSb), at POSa we have observed 2*UMIa, 1*UMIb and at POSb: 1*UMIc, 3*UMId, then the stats file is populated thus

| counts  | instances_pre|
| ------------- | ------------- |
| 1  | 2  |
| 2| 1 |
| 3| 1 |

If post deduplication, UMIb is grouped with UMIa such that POSa: 3*UMIa, then the `instances_post` column is populated thus:

**Comment by TomSmithCGAT** [comment]
Hi @ijhoskins. Apologies for the delay responding to your query.

I agree the name for these files is a bit confusing. The `_stats_per_umi_per_position.tsv` file simply tabulates the counts for unique combinations of UMI and position. E.g if prior to deduplication, we have two positions in the BAM (POSa, POSb), at POSa we have observed 2*UMIa, 1*UMIb and at POSb: 1*UMIc, 3*UMId, then the stats file is populated thus

| counts  | instances_pre|
| ------------- | ------------- |
| 1  | 2  |
| 2| 1 |
| 3| 1 |

If post deduplication, UMIb is grouped with UMIa such that POSa: 3*UMIa, then the `instances_post` column is populated thus:

| counts  | instances_pre|instances_post|
| ------------- | ------------- |------------- |
| 1  | 2  |1|
| 2| 1 |0|
| 3| 1 |2|

 The `_stats_per_umi_per.tsv` provides UMI-level summary statistics. Keeping in mind that each unique UMI sequence can be observed at [0-many] times across multiple positions in the BAM, 

`times_observed` = how many positions the UMI was observed at
`total_counts` = the total number of times the UMI was observed across all positions
`median_counts` = the median for the distribution of how often the UMI was observed at each position (excluding zeros)

Hence, whenever `times_observed`=1, `total_counts`==`median_counts`.

Hopefully that clears up the confusion?

Either way, we should update the documentation to make this clearer

**Comment by ijhoskins** [comment]
Hi @TomSmithCGAT that helps lot. Thank you!

**Comment by ijhoskins** [comment]
Feel free to close at will.

**Comment by TomSmithCGAT** [comment]
Thanks! I'm just updating documentation now. Do you mind checking over the updated explanation to see that it makes sense from a user perspective?

**Comment by ijhoskins** [comment]
Sure thing, let me know when it's ready.

**Comment by TomSmithCGAT** [comment]
You should be able to view the updated documentation here: https://umi-tools.readthedocs.io/en/ts-update_docs_stats/

If you have any suggestions for edits/amendments, you should be able to make them here:  #401
