### ISSUE TITLE
xGen Dual Index UMI Adapters

### ISSUE THREAD

**Issue by snenish03** [CGATOxford/UMI-tools#396]
Hello,

I have paired end reads with UMI next to i7 index (image below)
![image](https://user-images.githubusercontent.com/31145376/74270375-f7518200-4cbf-11ea-996b-3bbf8d0d52ca.png)

I tried 4 ways to deal with this - 
1. treating UMI is on 5 prime of read 1
2. treating UMI is on 5' of either read
3. treating UMI is on 3 prime
4. treating UMI is on 3' of either read.

Each time I get separate results. Do you have any specific parameters to deal with UMI next to i7 index?

My workflow is - 
a. Umi_tools extract
b. bbmerge
c. bwa for merged reads
d. bwa for unmerged reads
e. picard sort for (c) and repeat for (d)
f. picard merge aligned.merged and aligned.unmerged
g. umi_tools dedup

**Comment by IanSudbery** [comment]
My understanding is that in this case the UMI should be on the 3' end of what is effectively read3, as the indexes are sequenced using a third sequencing primer, and you will need a third fastq to recover these UMIs.

**Comment by snenish03** [comment]
According to my understanding of the data, I have 2 fastq files and the UMI is on the 3' end of the i7 index.
![image](https://user-images.githubusercontent.com/31145376/74272640-d5f29500-4cc3-11ea-977e-d7153451c8a7.png)

**Comment by IanSudbery** [comment]
So in each of these figures, you have more than 2 sequencing reads.

In a) Read 1 reads into the insert 5'-> 3' from the sequencing primer, read
2 reads into the insert 3' -> 5' (i.e. away from the i7 Index). The i7 read
using the reverse complement of the read2 sequencing primer and reads the
i7 Index.

In b) you have all of the above, but in addition you have two additional
reads: a primer reverse complement to the read1 primer reads the i5 index
3'->5' and a primer matching the P5 sequence reads the i5 index 5' -> 3'.

Finally in c) you have everything in b (should be 5 reads in total), but
the i7 read is read for additional cycles and adds the UMI to the end of
the i7 read.

You need to ask your sequencing provider for the sequence of the i7 read.
Hopefully they will have read far enough to include the UMI sequence.

For more details, see the IDT xGen application note:
https://sfvideo.blob.core.windows.net/sitefinity/docs/default-source/user-guide-manual/demultiplexing-data-containing-unique-molecular-indexes-(umis).pdf

**Comment by snenish03** [comment]
Thanks for your response!

I do have the index which looks like this - XXXXXXXXNNNNNNNNN

So, would this be the best way to use UMI_tools?
` umi_tools extract -I ../../Data/6U4_S4_L001_R1_001.fastq --extract-method string --bc-pattern=XXXXXXXXNNNNNNNNN --bc-pattern2=XXXXXXXXNNNNNNNNN --read2-in=../../Data/6U4_S4_L001_R2_001.fastq --stdout=processed.1.fastq.gz --read2-out=processed.2.fastq.gz --3prime`

**Comment by IanSudbery** [comment]
Your pattern is correct, but the index won't be in either read 1 (unless your insert is much shorter than your read length) or read2 (the primer is reading away from the index). You need a file that contains your i7 sequences. Then you would do something like:

```
umi_tools extract -I i7index.fastq --bc-pattern=XXXXXXXXNNNNNNNNN --read2-in=read1.fastq --read2-stdout --stdout=processed.1.fastq.gz
umi_tools extract -I i7index.fastq --bc-pattern=XXXXXXXXNNNNNNNNN --read2-in=read2.fastq --read2-stdout --stdout=procsesed.2.fastq.gz
```

Often, the i7 indexes are in a file marked "R3", so in your case the file might be called something like `6U4_S4_L001_R3_001.fastq`

**Comment by snenish03** [comment]
Ah, I do not have that. All I got were 2 fastq files for each sample. I will ask for them but there is no way to go about the analysis without R3?

**Comment by IanSudbery** [comment]
Its possible that they have put the i7 index read sequence into the fastq read name.

**Comment by snenish03** [comment]
No, they didnt :(

**Comment by snenish03** [comment]
Hey! Thanks for your help. I now have a 3rd fastq file with 8 bases (i7 index) and 9Ns. 

Can you please help me understand what exactly are we doing with the following commands?
`umi_tools extract -I i7index.fastq --bc-pattern=XXXXXXXXNNNNNNNNN --read2-in=read1.fastq --read2-stdout --stdout=processed.1.fastq.gz`
`umi_tools extract -I i7index.fastq --bc-pattern=XXXXXXXXNNNNNNNNN --read2-in=read2.fastq --read2-stdout --stdout=procsesed.2.fastq.gz`

**Comment by IanSudbery** [comment]
In paired end mode, UMI-tools takes reads from the input, finds their UMIs and adds it to the read header of both read1 (usually sent to stdout), and read2 (usually to a specified file). 

If you have three files, you need to add the UMI from read 3 to both read 1 and read 2. 

Each of the commands above, takes the UMI and adds it to the corresponding header of the read specified as read2. `--read2-stdout` tells UMI tools to discard the read from the input (`-I`) and instread send the output from read2 to the standard output stream.  It will also add the UMI to the header of read3 - but because this is discarded, it doesn't matter.

So the first command takes the UMI from read3 and adds it to read1 and the second command takes the UMI from read3 and adds it to read2.

**Comment by snenish03** [comment]
Perfect! Thank you :)
