### ISSUE TITLE
Failure in running the nosetests

### ISSUE THREAD

**Issue by Aanchal85** [CGATOxford/UMI-tools#397]
Ran 53 tests in 0.673s

FAILED (failures=51)

a0malh01@user1$ nosetests tests/test_umi_tools.py.
I ran the following after installation of the umi-tools. 
A part of the error is:

FAIL: umi_tools.py/whitelist_scrb_seq
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/local/python/3.5.2/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/scratch/home/a0malh01/UMI-tools-1.0.1/tests/test_umi_tools.py", line 202, in check_script
    ok_(not fail, msg)
AssertionError: error in statement: /bin/bash -c 'umi_tools whitelist --bc-pattern=CCCCCCNNNNNNNNNN  -L test.log --plot-prefix=knee_plots --stdin=/scratch/home/a0malh01/UMI-tools-1.0.1/tests/scrb_seq_fastq.1.gz > /scratch/global/a0malh01/tmpv8d9oupl/stdout'; stderr=b'/bin/bash: umi_tools: command not found\n'

There was no error during the time of installation. However when I run umi_tools whitelist it gives an error no such file or directory. That is when I checked the installation and it failed as specified above.

**Comment by Aanchal85** [comment]
Any help??

**Comment by IanSudbery** [comment]
How did you install? Was it with `setup.py install --local`?

**Comment by Aanchal85** [comment]
Yes I used that and then I went through the issues with the setup.py. I was finally able to run it after export$Path solution you had suggested in one of the posts.
But now I have another question. When I use the umi_tools whitelist function and direct the output by :--log2stderr > whitelist.txt , I get an output file with the log on top and the actual file beginning after the log ends. But when i try to separate the log and the output file, I get empty files. I use the command : --stdlog > progress.txt --stdout > whitelist.txt

**Comment by IanSudbery** [comment]
You need that to be:

`--stdlog progress.txt --stdout whitelist.txt`, i.e. no redirects (`>`)

**Comment by Aanchal85** [comment]
I have tried the above without redirects but it gave me empty files. I will run again and and send you the resulting files. In the mean time I started with the whitelist file created as redirected to stderr. 
Now I am facing the issue with the count function option of umi_tools. I give the command:

umi_tools count --per-gene --gene-tag=XT --assigned-status-tag=XS --per-cell -I home/a0malh01/assigned_sorted.bam -S counts.tsv.gz 

and I get the following error:


Traceback (most recent call last):
  File "/home/a0malh01/.local/bin/umi_tools", line 11, in <module>
    load_entry_point('umi-tools==1.0.1', 'console_scripts', 'umi_tools')()
  File "/scratch/home/a0malh01/UMI-tools-1.0.1/umi_tools/umi_tools.py", line 58, in main
    module = importlib.import_module("umi_tools." + command, "umi_tools")
  File "/usr/local/python/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/scratch/home/a0malh01/UMI-tools-1.0.1/umi_tools/count.py", line 48, in <module>
    import umi_tools.network as network
  File "/scratch/home/a0malh01/UMI-tools-1.0.1/umi_tools/network.py", line 14, in <module>
    from umi_tools._dedup_umi import edit_distance
ImportError: No module named 'umi_tools._dedup_umi'

I dont get what is going on now.
Thanks.

**Comment by IanSudbery** [comment]
This seems like umi_tools failed to install correctly, as it is not able to import the compiled c library. How did you install umi_tools?

**Comment by Aanchal85** [comment]
$ python setup.py install --user 

I used this to install as I have permission issues. This happens after that:

running install
running bdist_egg
running egg_info
writing dependency_links to umi_tools.egg-info/dependency_links.txt
writing top-level names to umi_tools.egg-info/top_level.txt
writing umi_tools.egg-info/PKG-INFO
writing requirements to umi_tools.egg-info/requires.txt
writing entry points to umi_tools.egg-info/entry_points.txt
reading manifest file 'umi_tools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'umi_tools.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/Documentation.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/Utilities.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/__init__.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/count.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/count_tab.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/dedup.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/extract.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/extract_methods.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/group.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/network.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/sam_methods.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/umi_methods.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/umi_tools.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/version.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/whitelist.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/whitelist_methods.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/_dedup_umi.c -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/_dedup_umi.pyx -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.5/umi_tools/_dedup_umi.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/umi_tools
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/Documentation.py to Documentation.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/Utilities.py to Utilities.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/count.py to count.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/count_tab.py to count_tab.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/dedup.py to dedup.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/extract.py to extract.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/extract_methods.py to extract_methods.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/group.py to group.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/network.py to network.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/sam_methods.py to sam_methods.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/umi_methods.py to umi_methods.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/umi_tools.py to umi_tools.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/version.py to version.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/whitelist.py to whitelist.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/whitelist_methods.py to whitelist_methods.cpython-35.pyc
creating stub loader for umi_tools/_dedup_umi.cpython-35m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/_dedup_umi.py to _dedup_umi.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/umi_tools-1.0.1-py3.5-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing umi_tools-1.0.1-py3.5-linux-x86_64.egg
removing '/scratch/home/a0malh01/.local/lib/python3.5/site-packages/umi_tools-1.0.1-py3.5-linux-x86_64.egg' (and everything under it)
creating /scratch/home/a0malh01/.local/lib/python3.5/site-packages/umi_tools-1.0.1-py3.5-linux-x86_64.egg
Extracting umi_tools-1.0.1-py3.5-linux-x86_64.egg to /scratch/home/a0malh01/.local/lib/python3.5/site-packages
umi-tools 1.0.1 is already the active version in easy-install.pth
Installing umi_tools script to /home/a0malh01/.local/bin

Installed /scratch/home/a0malh01/.local/lib/python3.5/site-packages/umi_tools-1.0.1-py3.5-linux-x86_64.egg
Processing dependencies for umi-tools==1.0.1
Searching for matplotlib==1.5.3
Best match: matplotlib 1.5.3
Adding matplotlib 1.5.3 to easy-install.pth file

Using /scratch/local/python/3.5.2/lib/python3.5/site-packages
Searching for scipy==0.18.0
Best match: scipy 0.18.0
Adding scipy 0.18.0 to easy-install.pth file

Using /scratch/local/python/3.5.2/lib/python3.5/site-packages
Searching for regex==2020.1.8
Best match: regex 2020.1.8
Processing regex-2020.1.8-py3.5-linux-x86_64.egg
regex 2020.1.8 is already the active version in easy-install.pth

Using /scratch/home/a0malh01/.local/lib/python3.5/site-packages/regex-2020.1.8-py3.5-linux-x86_64.egg
Searching for future==0.16.0
Best match: future 0.16.0
Adding future 0.16.0 to easy-install.pth file
Installing futurize script to /home/a0malh01/.local/bin
Installing pasteurize script to /home/a0malh01/.local/bin

Using /scratch/local/python/3.5.2/lib/python3.5/site-packages
Searching for pandas==0.18.1
Best match: pandas 0.18.1
Adding pandas 0.18.1 to easy-install.pth file

Using /scratch/local/python/3.5.2/lib/python3.5/site-packages
Searching for numpy==1.12.1
Best match: numpy 1.12.1
Adding numpy 1.12.1 to easy-install.pth file

Using /scratch/local/python/3.5.2/lib/python3.5/site-packages
Searching for setuptools==35.0.2
Best match: setuptools 35.0.2
Adding setuptools 35.0.2 to easy-install.pth file
Installing easy_install script to /home/a0malh01/.local/bin
Installing easy_install-3.6 script to /home/a0malh01/.local/bin

Using /scratch/local/python/3.5.2/lib/python3.5/site-packages
Searching for pyparsing==2.2.0
Best match: pyparsing 2.2.0
Adding pyparsing 2.2.0 to easy-install.pth file

Using /scratch/local/python/3.5.2/lib/python3.5/site-packages
Searching for python-dateutil==2.5.3
Best match: python-dateutil 2.5.3
Adding python-dateutil 2.5.3 to easy-install.pth file

Using /scratch/local/python/3.5.2/lib/python3.5/site-packages
Searching for pytz==2016.6.1
Best match: pytz 2016.6.1
Adding pytz 2016.6.1 to easy-install.pth file

Using /scratch/local/python/3.5.2/lib/python3.5/site-packages
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Adding cycler 0.10.0 to easy-install.pth file

Using /scratch/local/python/3.5.2/lib/python3.5/site-packages
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /scratch/local/python/3.5.2/lib/python3.5/site-packages
Searching for packaging==16.8
Best match: packaging 16.8
Adding packaging 16.8 to easy-install.pth file

Using /scratch/local/python/3.5.2/lib/python3.5/site-packages
Searching for appdirs==1.4.3
Best match: appdirs 1.4.3
Adding appdirs 1.4.3 to easy-install.pth file

Using /scratch/local/python/3.5.2/lib/python3.5/site-packages
Finished processing dependencies for umi-tools==1.0.1
a0malh01@user1$ um
umask          umount         umount.hal     umount.nfs     umount.nfs4    umount.udisks  
a0malh01@user1$ umi_tools
-bash: umi_tools: command not found

**Comment by Aanchal85** [comment]
After that I do this:
$ export PATH=$PATH:~/.local/bin

a0malh01@user1$ umi_tools count --help
UMI-Tools: Version 1.0.1
Traceback (most recent call last):
  File "/home/a0malh01/.local/bin/umi_tools", line 11, in <module>
    load_entry_point('umi-tools==1.0.1', 'console_scripts', 'umi_tools')()
  File "/scratch/home/a0malh01/UMI-tools-1.0.1/umi_tools/umi_tools.py", line 58, in main
    module = importlib.import_module("umi_tools." + command, "umi_tools")
  File "/usr/local/python/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/scratch/home/a0malh01/UMI-tools-1.0.1/umi_tools/count.py", line 48, in <module>
    import umi_tools.network as network
  File "/scratch/home/a0malh01/UMI-tools-1.0.1/umi_tools/network.py", line 14, in <module>
    from umi_tools._dedup_umi import edit_distance
ImportError: No module named 'umi_tools._dedup_umi'
a0malh01@user1$

**Comment by IanSudbery** [comment]
For some reason, your `$ python setup.py install --user` is installing `umi_tools` to `/scratch/home/a0malh01/.local/lib/python3.5/site-packages/umi_tools-1.0.1-py3.5-linux-x86_64.egg`, but then when you run `umi_tools`, its trying to load it from `/scratch/home/a0malh01/UMI-tools-1.0.1/umi_tools/`.

I can think of two reasons that this might happen:

1. `/scratch/home/a0malh01/UMI-tools-1.0.1/umi_tools/` is on your `$PYTHONPATH`. 

2. Some how you've managed to get two copies installed. Note this line in the install log: 
    > umi-tools 1.0.1 is already the active version in easy-install.pth

    I guess this might happen if a failed install happened first? Perhaps with `python setup.py --develop`. What is the result of
     `$ ls /scratch/home/a0malh01/.local/lib/python3.5/site-packages/umi*`
     What happens if you delete the source directory after installing?

**Comment by Aanchal85** [comment]
a0malh01@user1$ ls /scratch/home/a0malh01/.local/lib/python3.5/site-packages/umi*
EGG-INFO  umi_tools

**Comment by IanSudbery** [comment]
what is the content of `/scratch/home/a0malh01/.local/lib/python3.5/site-packages/easy-install.pth`?

**Comment by Aanchal85** [comment]
a0malh01@user2$ ls /scratch/home/a0malh01/.local/lib/python3.5/site-packages/
easy-install.pth  regex-2020.1.8-py3.5-linux-x86_64.egg  setuptools.pth  umi_tools-1.0.1-py3.5-linux-x86_64.egg
a0malh01@user2$ ls /scratch/home/a0malh01/.local/lib/python3.5/site-packages/easy-install.pth 
/scratch/home/a0malh01/.local/lib/python3.5/site-packages/easy-install.pth
a0malh01@user2$ 

I just deleted the UMI_tools.1.0 directory in my home space and it started working!

But I have a question, when I do another dataset, will I have to install and setup that directory again? Will I do export $Path again?

 umi_tools count --per-gene --gene-tag=XT --assigned-status-tag=XS --per-cell -I assigned_sorted.bam -S counts.tsv.gz 
# UMI-tools version: 1.0.1
# output generated by count --per-gene --gene-tag=XT --assigned-status-tag=XS --per-cell -I assigned_sorted.bam -S counts.tsv.gz
# job started at Thu Feb 27 13:30:42 2020 on user1 -- d26ca331-fa51-45b0-839f-9845eba6462a
# pid: 16141, system: Linux 2.6.32-642.6.2.el6.x86_64 #1 SMP Wed Oct 26 06:52:09 UTC 2016 x86_64
# assigned_tag                            : XS
# cell_tag                                : None
# cell_tag_delim                          : None
# cell_tag_split                          : -
# chimeric_pairs                          : use
# chrom                                   : None
# compresslevel                           : 6
# gene_tag                                : XT
# gene_transcript_map                     : None
# get_umi_method                          : read_id
# ignore_umi                              : False
# in_sam                                  : False
# log2stderr                              : False
# loglevel                                : 1
# mapping_quality                         : 0
# method                                  : directional
# no_sort_output                          : False
# out_sam                                 : False
# output_unmapped                         : False
# paired                                  : False
# per_cell                                : True
# per_contig                              : False
# per_gene                                : True
# random_seed                             : None
# read_length                             : False
# short_help                              : None
# skip_regex                              : ^(__|Unassigned)
# soft_clip_threshold                     : 4
# spliced                                 : False
# stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='ANSI_X3.4-1968'>
# stdin                                   : <_io.TextIOWrapper name='assigned_sorted.bam' mode='r' encoding='ANSI_X3.4-1968'>
# stdlog                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='ANSI_X3.4-1968'>
# stdout                                  : <_io.TextIOWrapper name='counts.tsv.gz' encoding='ascii'>
# subset                                  : None
# threshold                               : 1
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# tmpdir                                  : None
# umi_sep                                 : _
# umi_tag                                 : RX
# umi_tag_delim                           : None
# umi_tag_split                           : None
# unmapped_reads                          : discard
# unpaired_reads                          : use
# wide_format_cell_counts                 : False

**Comment by IanSudbery** [comment]
UMI-tools is now permanently installed in `~/.local' (unless you remove it). You don't need to setup/install again. But you will need `~/.local` to be on your `$PATH` any time you want to use it, yes. The same applies to any other python package installed with `pip install --local` or `python setup.py --user` that has a command line executable. Thus, I recommend putting the export command in your `.bashrc` so that it is executed every time you log in.

**Comment by TomSmithCGAT** [comment]
I'm closing this issue since it appears to have been resolved. For related problems, please open a new issue and reference this one.
