### ISSUE TITLE
Install error on CentOS7

### ISSUE THREAD

**Issue by ARW-UBT** [CGATOxford/UMI-tools#398]
Hello, when I install UMI-tools by the following pip command, I get the note that python2.7 is deprecated...
pip install umi_tools

If I install it by pip3, I get the following error (and continued as shown below that error): 
[weig@btbbx3 UMI-tools-1.0.1]$ pip3 install umi_tools
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting umi_tools
  Using cached umi_tools-1.0.1.tar.gz (77 kB)
Requirement already satisfied: setuptools>=1.1 in /usr/local/lib/python3.6/site-packages (from umi_tools) (45.2.0)
Requirement already satisfied: numpy>=1.7 in /home/weig/.local/lib/python3.6/site-packages (from umi_tools) (1.18.1)
Requirement already satisfied: pandas>=0.12.0 in /home/weig/.local/lib/python3.6/site-packages (from umi_tools) (1.0.1)
Requirement already satisfied: future in /home/weig/.local/lib/python3.6/site-packages (from umi_tools) (0.18.2)
Requirement already satisfied: regex in /home/weig/.local/lib/python3.6/site-packages (from umi_tools) (2020.2.20)
Requirement already satisfied: scipy in /home/weig/.local/lib/python3.6/site-packages (from umi_tools) (1.4.1)
Requirement already satisfied: matplotlib in /home/weig/.local/lib/python3.6/site-packages (from umi_tools) (3.1.3)
Requirement already satisfied: pytz>=2017.2 in /home/weig/.local/lib/python3.6/site-packages (from pandas>=0.12.0->umi_tools) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /home/weig/.local/lib/python3.6/site-packages (from pandas>=0.12.0->umi_tools) (2.8.1)
Requirement already satisfied: cycler>=0.10 in /home/weig/.local/lib/python3.6/site-packages (from matplotlib->umi_tools) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/weig/.local/lib/python3.6/site-packages (from matplotlib->umi_tools) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/weig/.local/lib/python3.6/site-packages (from matplotlib->umi_tools) (2.4.6)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.6/site-packages (from python-dateutil>=2.6.1->pandas>=0.12.0->umi_tools) (1.11.0)
Installing collected packages: umi-tools
    Running setup.py install for umi-tools ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1um_wbi2/umi-tools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1um_wbi2/umi-tools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ipa1n5dh/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/weig/.local/include/python3.6m/umi-tools
         cwd: /tmp/pip-install-1um_wbi2/umi-tools/
    Complete output (43 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/Documentation.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/Utilities.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/__init__.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/count.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/count_tab.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/dedup.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/extract.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/extract_methods.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/group.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/network.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/sam_methods.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/umi_methods.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/umi_tools.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/version.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/whitelist.py -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/whitelist_methods.py -> build/lib.linux-x86_64-3.6/umi_tools
    running egg_info
    writing umi_tools.egg-info/PKG-INFO
    writing dependency_links to umi_tools.egg-info/dependency_links.txt
    writing entry points to umi_tools.egg-info/entry_points.txt
    writing requirements to umi_tools.egg-info/requires.txt
    writing top-level names to umi_tools.egg-info/top_level.txt
    reading manifest file 'umi_tools.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'umi_tools.egg-info/SOURCES.txt'
    copying umi_tools/_dedup_umi.c -> build/lib.linux-x86_64-3.6/umi_tools
    copying umi_tools/_dedup_umi.pyx -> build/lib.linux-x86_64-3.6/umi_tools
    running build_ext
    building 'umi_tools._dedup_umi' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/umi_tools
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c umi_tools/_dedup_umi.c -o build/temp.linux-x86_64-3.6/umi_tools/_dedup_umi.o
    umi_tools/_dedup_umi.c:8:22: schwerwiegender Fehler: pyconfig.h: Datei oder Verzeichnis nicht gefunden
     #include "pyconfig.h"
                          ^
    Kompilierung beendet.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1um_wbi2/umi-tools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1um_wbi2/umi-tools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ipa1n5dh/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/weig/.local/include/python3.6m/umi-tools Check the logs for full command output.

###################
I tried: 
python3 -m pip install umi_tools 
completes without errors, but a test run was not seccessful:

umi_tools dedup --stdin=/GenomAnalytik_misc/Weig-VL2/UMI-tools-raw/VL2-C1-raw.bam --log=LOGfile > outC1.bam
Traceback (most recent call last):
  File "/home/weig/.local/bin/umi_tools", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/weig/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/home/weig/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/weig/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/weig/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/weig/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/weig/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.7.1 (/usr/lib64/python2.7/site-packages), Requirement.parse('numpy>=1.8.2'), set(['scipy']))

Any idea what might has gone wrong?
Thanks

**Comment by IanSudbery** [comment]
Your install problems are because when we built 1.0.1, it seems we failed to build the wheels. @TomSmithCGAT: did you do this for previous versions, is it something you do quickly? I can take a look, but I'm a little busy this week, so it might be later

As for your problems running.... 
This is because for some reason, despite installing with python 3, umi_tools appears to be trying to load libraries from python2. 

See: 

from pkg_resources import load_entry_point
File "/home/weig/.local/lib/**python2.7**/site-packages/pkg_resources/init.py", line 3251, in
@_call_aside

What is the response if you do:
```
$ echo $PYTHONPATH
```

**Comment by ARW-UBT** [comment]
Hi,
The response for echo $PYTHONPATH is an empty lane (or nothing)

I have the following in /usr/bin/:
/usr/bin/python -> /usr/bin/python2.7
/usr/bin/python3 -> python3.6

Best regards
Alfons

Von: Ian Sudbery <notifications@github.com>
Gesendet: Montag, 24. Februar 2020 16:26
An: CGATOxford/UMI-tools <UMI-tools@noreply.github.com>
Cc: Weig, Alfons <A.Weig@uni-bayreuth.de>; Author <author@noreply.github.com>
Betreff: Re: [CGATOxford/UMI-tools] Install error on CentOS7 (#398)


Your install problems are because when we built 1.0.1, it seems we failed to build the wheels. @TomSmithCGAT<https://github.com/TomSmithCGAT>: did you do this for previous versions, is it something you do quickly? I can take a look, but I'm a little busy this week, so it might be later

As for your problems running....
This is because for some reason, despite installing with python 3, umi_tools appears to be trying to load libraries from python2.

See:

from pkg_resources import load_entry_point
File "/home/weig/.local/lib/python2.7/site-packages/pkg_resources/init.py", line 3251, in
@_call_aside

What is the response if you do:

$ echo $PYTHONPATH

**Comment by IanSudbery** [comment]
What about

    $ cat `which umi_tools`

**Comment by ARW-UBT** [comment]
Nothing...

File or Folder not found...


I'm afraid UMI-Tools were not installed.


Best

Alfons


PD Dr. Alfons Weig
Genomanalytik & Bioinformatik
Universität Bayreuth
Universitätsstrasse 30
95447 Bayreuth

Phone: +49-(0)921-552457,
Fax: +49-(0)921-55842457
www.genomics.uni-bayreuth.de
________________________________
Von: Ian Sudbery <notifications@github.com>
Gesendet: Montag, 24. Februar 2020 17:32:18
An: CGATOxford/UMI-tools
Cc: Weig, Alfons; Author
Betreff: Re: [CGATOxford/UMI-tools] Install error on CentOS7 (#398)


What about

$ cat `which umi_tools`

**Comment by IanSudbery** [comment]
Hmmm... something is not right here....

When you typed `umi_tools dedup --stdin=/GenomAnalytik_misc/Weig-VL2/UMI-tools-raw/VL2-C1-raw.bam --log=LOGfile > outC1.bam`, you got a python error right? Not file not found?

What you need to fix the error you got on `$ pip3 install umi_tools` is the  `python-dev` system library, which you can get with `sudo apt install python-dev` if you have the appropriate rights, but the fact you are installing to `~/.local` suggests you don't?

**Comment by ARW-UBT** [comment]
Hi Ian,

That was the problem, I had to install python3-devel …

Best regards
Alfons

Von: Ian Sudbery <notifications@github.com>
Gesendet: Montag, 24. Februar 2020 17:55
An: CGATOxford/UMI-tools <UMI-tools@noreply.github.com>
Cc: Weig, Alfons <A.Weig@uni-bayreuth.de>; Author <author@noreply.github.com>
Betreff: Re: [CGATOxford/UMI-tools] Install error on CentOS7 (#398)


Hmmm... something is not right here....

When you typed umi_tools dedup --stdin=/GenomAnalytik_misc/Weig-VL2/UMI-tools-raw/VL2-C1-raw.bam --log=LOGfile > outC1.bam, you got a python error right? Not file not found?

What you need to fix the error you got on $ pip3 install umi_tools is the python-dev system library, which you can get with sudo apt install python-dev if you have the appropriate rights, but the fact you are installing to ~/.local suggests you don't?

**Comment by TomSmithCGAT** [comment]
It sounds like this issue was resolved.
