### ISSUE TITLE
got these from dedup: ValueError: reference_id -1 out of range 0<=tid<359

### ISSUE THREAD

**Issue by Evelyn2579** [CGATOxford/UMI-tools#404]
Here are my error:
2020-03-04 17:31:44,554 WARNING Unpaired read pairs are being used. Some read pair UMIs may be grouped/deduplicated using just the mapping coordinates from read1.This may also increase the run time and memory usage. Consider --unpared-reads==discard to discard these reads or --unpared-reads==output (group command only) to output them without grouping
2020-03-04 17:31:44,554 INFO command: dedup -I test_B10-1.either.sorted.bam --chimeric-pairs=discard --paired -S test_B10-1.either.sorted.deduplicated.bam
2020-03-04 17:31:44,554 INFO command: dedup -I test_B10-1.either.sorted.bam --chimeric-pairs=discard --paired -S test_B10-1.either.sorted.deduplicated.bam
Traceback (most recent call last):
  File "/public/home/syli/software/miniconda3/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/public/home/syli/software/miniconda3/lib/python3.6/site-packages/umi_tools/umi_tools.py", line 61, in main
    module.main(sys.argv)
  File "/public/home/syli/software/miniconda3/lib/python3.6/site-packages/umi_tools/dedup.py", line 262, in main
    for bundle, key, status in bundle_iterator(inreads):
  File "/public/home/syli/software/miniconda3/lib/python3.6/site-packages/umi_tools/sam_methods.py", line 375, in __call__
    read.reference_name != read.next_reference_name):
  File "pysam/libcalignedsegment.pyx", line 965, in pysam.libcalignedsegment.AlignedSegment.next_reference_name.__get__ (pysam/libcalignedsegment.c:12545)
  File "pysam/libcalignmentfile.pyx", line 1609, in pysam.libcalignmentfile.AlignmentFile.getrname
  File "pysam/libcalignmentfile.pyx", line 672, in pysam.libcalignmentfile.AlignmentFile.get_reference_name
ValueError: reference_id -1 out of range 0<=tid<359

Here are my code from trim to dedup:
`java -jar ~/software/Trimmomatic-0.36/trimmomatic-0.36.jar PE -threads 10 -phred33 B10-1_L2_1.fq.gz B10-1_L2_2.fq.gz test_B10-1_1_paired.fastq.gz test_B10-1_1_unpaired.fastq.gz test_B10-1_2_paired.fastq.gz test_B10-1_2_unpaired.fastq.gz ILLUMINACLIP:~/software/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa:2:30:10 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36`
`umi_tools extract --extract-method=regex --bc-pattern='(?P<discard_1>AAGCAGTGGTATCAACGCAGAGTGAAT){s<=1}(?P<umi_1>.{10}).*'   --stdin test_B10-1_1_paired.fastq.gz  --stdout test_B10-1.extract.1.fastq.gz --read2-in test_B10-1_2_paired.fastq.gz --read2-out test_B10-1.either.2.fastq.gz -L test_B10-1.either.extract.log`
`reformat.sh in1=test_B10-1.extract.1.fastq.gz in2=test_B10-1.extract.2.fastq.gz out1=test_B10-1.bbmap.1.fastq.gz out2=test_B10-1.bbmap.2.fastq.gz minlen=25`
`~/software/STAR-2.6.1b/bin/Linux_x86_64/STAR --runThreadN 10 --genomeDir ~/genome/ --readFilesIn test_B10-1.bbmap.1.fastq.gz test_B10-1bbmap.2.fastq.gz --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outBAMsortingThreadN 10 --outFilterMultimapNmax 1 --outFileNamePrefix test_B10-1.`
`samtools sort test_B10-1.Aligned.sortedByCoord.out.bam -o test_B10-1.sorted.bam`
`samtools index test_B10-1.sorted.bam`
` umi_tools dedup -I test_B10-1.sorted.bam --chimeric-pairs=discard --paired -S test_B10-1.sorted.deduplicated.bam`

And for the same pipeline, only change STAR to bowtie2, the umi-tools dedup can work.I don't know how to figure out this, it's so confusing and frustrating.I appreciate any help.

**Comment by IanSudbery** [comment]
In a BAM file, the contig/chromosome to which a read is mapped is stored a numeric value. The BAM header then stores the which chromosome that number corresponds to. Valid numbers for this are 0-359. For some reason, one of your reads has managed to get the reference_id -1, which shouldn't be possible. Try a bisection search of your BAM file to find the offending read: break the bam file in half with `samtools view -h test_B10-1.sorted.bam | head -nXXXX | samtools view -hb > test.bam` where XXX is half the reads in the file, and see if that file works. If it does, take the second half and try. If it doesn't divde test.bam in half and test the too halfs and so on until you find the duff read. Post it here so we can look what is going on.

**Comment by Evelyn2579** [comment]
Thanks a lot for your reply!
Based on your advice, i tried to break my bam file in half, and `test_B10-1.sorted.56695.bam` could run umitools dedup, but `test_B10-1.sorted.56696.bam` couldn't. so i checked the last line in `test_B10-1.sorted.56696.bam`.   `samtools view test_B10-1.sort.56696.bam | tail -n 1` and here is what i got:
`A00153:563:H2LVHDSXY:2:1368:12581:28228_GGATTCGGGT      89      ERCC-00002      945     255     111M    *       0       0       TTGCTCGGCAATCAGTAATGGTAGGCGTTAGACCCCGTGACTCGTGGCTGAACGGCCGTACAACTCTACAGCCGGTGCTTGCGTTTTACCCTTAAAAAAAAAAAAAAAAAA   F:FF,,FFFFFFFFFF,,FF:FFFFF:FF,::FF:FF:FFF:,F,FFFF,FF:FFFF:FF,F:,F:,,FF:F:F,F,,FFFF:F,FFFF::FFFFF,FFFFFFFFFFFFFF   NH:i:1  HI:i:1  AS:i:105        nM:i:2`
although i thought the reference-id was a reasonable value, i tried to exclude all ERCC_00002 reads, `samtools view -h test_B10-1.sort.bam |grep -v "ERCC-00002" |samtools view -hb > test_B10-1.sort.exER02.bam`,then built index and did the umitools dedup, but it still couldn't work, i wondered if there were something else that caused such strange output.
waiting for your help.

**Comment by TomSmithCGAT** [comment]
@IanSudbery - Havent't had a chance to properly look over this issue but thought it was mentioning that according to section 4.2 of SAM format document (https://samtools.github.io/hts-specs/SAMv1.pdf),  for BAM format refID, `-1 for a read without a mapping position`

**Comment by IanSudbery** [comment]
What's happening here is that the mate of this read is unmapped, and we are asking for the *name* of the chromosome it is mapped to. The question is - why hasn't this read been discarded because its mate is unmapped?

The key lines are

https://github.com/CGATOxford/UMI-tools/blob/2f380afe78033f8ca98179e56d6b0bc95137f006/umi_tools/sam_methods.py#L363..L375

            if self.options.paired and read.mate_is_unmapped:
                if not read.is_unmapped:
                    self.read_events['Read 2 unmapped'] += 1


                # if paired end input and read2 is unmapped, skip unless
                # options.unmapped_reads == "use", in which case TLEN will be 0
                if self.options.unmapped_reads != "use":
                    if self.return_unmapped:
                        yield read, None, "single_read"
                        continue


            if read.is_paired and (
                    read.reference_name != read.next_reference_name):

We shouldn't ever get to line 375 if unmapped reads is anything other than "use" and read2 is unmapped.

**Comment by TomSmithCGAT** [comment]
With hindsight, this is because of the typo rectified here by @Daniel-Liu-c0deb0t: #443
