### ISSUE TITLE
warning in 'dedup'

### ISSUE THREAD

**Issue by ZhenyiWangTHU** [CGATOxford/UMI-tools#405]
Hi developers,
When I run this command:
'umi_tools dedup --extract-umi-method=tag --umi-tag=UB --method unique --mapping-quality 255 -I ./sampleA.bam --output-stats=deduplicated -S ./sampleA.deduplicated.bam
'
I get the deduplicated bam file, but warnings are returned. Is there anything wrong?  I worry something wrong in the deduplicated file. Please notify me if you know the causes. Thanks!  

Here are the warnings:
2020-03-05 14:23:23,115 INFO Written out 83600000 reads
.../lib/python3.6/site-packages/pandas/core/series.py:1024: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[key] = value
.../lib/python3.6/site-packages/umi_tools/umi_tools.py:61: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  module.main(sys.argv)
2020-03-05 14:41:14,869 INFO Reads: Input Reads: 157152991, < MAPQ threshold: 21988627, Read skipped, missing umi and/or cell tag: 10953
2020-03-05 14:41:14,869 INFO Number of reads out: 83692332
2020-03-05 14:41:14,869 INFO Total number of positions deduplicated: 38036268
2020-03-05 14:41:14,869 INFO Mean number of unique UMIs per position: 2.20
2020-03-05 14:41:14,869 INFO Max. number of unique UMIs per position: 99364
job finished in 21492 seconds at Thu Mar  5 14:41:14 2020 -- 20826.17 619.36  0.00  0.00 -- c1ca4b64-384c-479c-9288-f892064e648c

**Comment by TomSmithCGAT** [comment]
Hi @ZhenyiWang - Just to put you at ease, the error above will only relate to the stats output, not the deduplicated BAM. I'll need to look into why the error occurs though and whether the stats output will be correct. Would you mind posting the stats outfiles here just so I can sanity check them. Cheers

**Comment by ZhenyiWangTHU** [comment]
> Hi @ZhenyiWangTHU - Just to put you at ease, the error above will only relate to the stats output, not the deduplicated BAM. I'll need to look into why the error occurs though and whether the stats output will be correct. Would you mind posting the stats outfiles here just so I can sanity check them. Cheers

Sure, 
thank you for quick reply. Please find the stat files attached. Cheers!

Because  'deduplicated_per_umi.tsv' is too large, I post screenshots of its headers and tail here. And the other two files are attached. 
![image](https://user-images.githubusercontent.com/35716168/75975589-bd1c7e80-5f13-11ea-8626-a9fb41e45645.png)
![image](https://user-images.githubusercontent.com/35716168/75975719-fe149300-5f13-11ea-8198-36775021fd54.png)
[dedupstat.zip](https://github.com/CGATOxford/UMI-tools/files/4292550/dedupstat.zip)
