### ISSUE TITLE
format of whitelist for extract with paired reads having independent umi bases

### ISSUE THREAD

**Issue by SolKatzman** [CGATOxford/UMI-tools#408]
umi_tools 1.0.1

I have paired-end reads. BioO library prep creates 8bp UMI in read1 and read2.

Each 8bp sequence is restricted to 96 possible values.

The **combination** of the two 8bp sequences is thus restricted to 9216 (=96x96) values.

I presume the command I want is this:

`extract --bc-pattern=NNNNNNNN --bc-pattern2=NNNNNNNN 
--filter-cell-barcode --whitelist=WHITELIST`

In what format do I specify the allowed values in the WHITELIST file?

a) all 9216 values? if so, underscore-separated 8bp_8bp?
b) something else?

Note that the extract command should be testing the total 16bp (8 from read1 and 8 from read2)
before including/excluding both the read1 and read2 entries in the output fastq files.

Thanks for your attention,
/Sol Katzman
UC Santa Cruz Genomics Institute

**Comment by SolKatzman** [comment]
Ok. I think I misunderstood the use of whitelist in umi_tools.
Apparently it is for single-cell results, to select "valid" cell barcodes.
I thought it had something to do with a whitelist of valid umi barcodes, as are generated in the BioO qRNA library kit.
So this issue can be ignored unless there is an upgrade to umi_tools to support whitelists of umi barcodes.

**Comment by TomSmithCGAT** [comment]
Hi Sol. 

I actually had a similar need to filter UMIs against a whitelist myself a while ago and added this functionality to UMI-tools but this remains on the {TS}-UMI_whitelist branch. See also #327. If you're happy to install from the branch it would be great to have someone else test out this functionality and maybe this will spur me on to finally merge this back into the master branch.

Using this branch, one can add the following options to filter UMIs against a whitelist the allowed 9216 UMIs thus:

`umi_tools extract --filter-umi --umi-whitelist=[read1_UMIs] --umi-whitelist-paired=[read2_UMIs]`, where `read1_UMIs` and `read2_UMIs` are filepaths for the lists of allowed UMIs in read 1 and read 2 (one per line).

In addition, the option `--correct-umi-threshold` controls the number of substition errors allowed (defualt=0) and `--umi-correct-log` can be used to output a log of the UMI corrections. 

The branch also enables alternative filtering of UMIs against a whitelist at the `dedup` stage but I won't describe that unless it is of interest.

**Comment by TomSmithCGAT** [comment]
This functionality is now available on the master branch and will be included in the next release
