### ISSUE TITLE
--error-correct-cell behaviour

### ISSUE THREAD

**Issue by mbahin** [CGATOxford/UMI-tools#411]
Hi,

Thanks for the tool.
I have a problem with --error-correct-cell, I don't know if I misunderstood something.

So first I do a whitelist:
`umi_tools whitelist --extract-method=regex --bc-pattern='(?P<discard_1>TTCG){s<=1}(?P<cell_1>.{15,17})(?P<discard_2>TGCTTACGCTACGGAACGA){s<=3}(?P<umi_1>.{9})' --stdin=input.fastq -S BBC.txt`
Which give me in particular this line in the whitelist output file:
CTGTTGATCACCCGTA	CTGTTGATCACCCGTAT
And then I do an extract:
`umi_tools extract --extract-method=regex --bc-pattern='(?P<discard_1>TTCG){s<=1}(?P<cell_1>.{15,17})(?P<discard_2>TGCTTACGCTACGGAACGA){s<=3}(?P<umi_1>.{9})' --whitelist BBC.txt --error-correct-cell --stdin=input.fastq -S input.BBC.fastq`
And in the output FASTQ file, I have this read header:
@M05218:191:000000000-D7R5H:1:1102:14341:19429_CTGTTGATCACCCGTAT_CCTCAAACG 1:N:0:2
where I was expecting the BC to be corrected to "CTGTTGATCACCCGTA" but it actually has the uncorrect form (that was actually found in the read).
Is it the expected behaviour? Did I misunderstand something?

Cheers,
Mathieu

**Comment by IanSudbery** [comment]
I think you need `--filter-cell-barcode` as well. Sorry, that isn't well documented.

**Comment by mbahin** [comment]
Yes it works with this additional option, thanks! :)

**Comment by mbahin** [comment]
Actually I don't understand why "--filter-cell-barcode" and "whitelist" are not one unique option?

**Comment by TomSmithCGAT** [comment]
There is indeed a redundancy between `--whitelist` and `filter-cell-barcode`, where the former is a path to a whitelist file and the later a switch to filter against this. `error-correct-cell` is a separate option however since one might wish to only retain cells than perfectly match the whitelist
