### ISSUE TITLE
Problem with UMICollapser Module

### ISSUE THREAD

**Issue by gamabunta313** [CGATOxford/UMI-tools#414]
I Am using network.py module to cluster UMIs. Boh read1 and read2 have 15nt UMI and I am trying to handle them separately ( R1 first, then R2). Since directional seems too "aggressive" I decided usying adjacency algorithm. The problem observed  for both reads is that UMIs with hamming distance >=2 are grouped in different clusters despite the Hamming distance threshold set at 2.
I read another issue with a similar problem, but I cannot find a solution.
Despite I quite understand the algorithm functioning, I cannot understand why it gives me such results.
I am missing something?
Since I have both reads with UMIs, do you think that would be better to analyze them as one (i.e. merging barcodes and handling as single 30 nt UMI) or deal with them separately?
Thank in advance for your help

**Comment by IanSudbery** [comment]
Can you post an example? Are you sure two reads greater than 2nt apart are not being merged because there is a UMI that is less that 2nt from both?

For example:

AAAAA: 50 
TTAAA: 30
TTATT: 10

would be merged into one cluster with threshold 2, even though AAAAA and TTATT are 4 apart, because TTAAA is edit distance 2 from both.

**Comment by gamabunta313** [comment]
The most represented sequence is:
CCTTCTTCCAATTTT:4500
and the sequence erroneously clustered is:
CCTTCTTCCACTTTT:15

**Comment by IanSudbery** [comment]
Oh sorry, I miss-read your original post. 

The way the adjecency algorithm works is to remove the highest frequency UMI, and check if removing the immediate neighbours of that UMI accounts for the whole network, and if it doesn't removing the highest and the second highest (even if the second highest is a neighbour of the highest). 

You can see this in action figure 1E in the paper. 
![image](https://user-images.githubusercontent.com/5391758/84133823-8e94cf00-aa3f-11ea-9589-eccc43f696a2.png)

ACGT is the most frequent, but removing it does not account for all UMIs in the network
AAAT is the next more frequent, but removing ACGT and AAAT still leaves ACAG unaccounted for. 
So finally ACGT, ACAT and AAAT are set as the "real" UMIs, even though ACGT is only one edit from ACAT and ACAT is only 1 edit from AAAT.

The assumption underlying this method was that if you had three UMIs in a chain, with the highest frequency UMI being on one end,  it was more likely this arose from two UMIs than it did from two nested mutation events. 

The realisation that this might not be the case, and that we could tell using the counts was what drove the creation of the directional algorithm.

**Comment by gamabunta313** [comment]
I have to edit my previous answer since also the directional method gave me same results. Most of the clusters generated are correct, probably, due to the algorithm itself, some low-frequency sequences are wrongly assigned.

**Comment by IanSudbery** [comment]
Can you post (or link) the full list of UMIs and counts for that position/bundle. 

If there are only those two UMIs then the definately should be grouped together.  However if there is a third sequence, it is possible that the questionable read could be group with it, rather than the one you have shown. 

Take the example

ACGT: 100
ACGA: 40
TCGA: 100
(with edit distance threshold=1)

ACGA could be grouped with either ACGT or TCGA, but you would want to group ACGT with TCGA, so ACGA will be grouped with one of the other two at random.

**Comment by gamabunta313** [comment]
Please find enclosed the .tab file used for the task. The Umi of interest were:
CCTTCTTCCAATTTT (the most represented) and CCTTCTTCCACTTTT. 
[file_R2_UMI_count.txt](https://github.com/CGATOxford/UMI-tools/files/4752493/file_R2_UMI_count.txt)

**Comment by IanSudbery** [comment]
Okay, so I've taken a look. 

Firstly, in my hands, these two sequences cluster in the same cluster under "directional".

Under "adjacency", the situation is very much like that in the figure I posted - CCTTCTTCCAATTTT  is analogous to ACGT and CCTTCTTCCACTTTT is analogous to ACAT in that figure. 

Both these umis sit in a network component with ~2000 umis in it. Removing CCTTCTTCCAATTTT  and its neighbours does not explain all 2000 UMIs, so CCTTCTTCCAATTTT's neighbours are returned, and CCTTCTTCCAATTTT   and the next most frequent UMI and their neighbours are removed. This still doesn't explain the 2000 UMIs, so the neighbours are returned, and the three most abundant UMIs and their neighbours are returned .... and so on, until CCTTCTTCCACTTTT and its neighbours are removed. 

A final word. If you have UMIs on both read1 and read2, you should merge them into a single long UMI and process them together.

**Comment by gamabunta313** [comment]
Thank you very much for such a precious help!
Bests
