### ISSUE TITLE
Tutorial Link doesn't work

### ISSUE THREAD

**Issue by barkasn** [CGATOxford/UMI-tools#416]
wget https://github.com/CGATOxford/UMI-tools/releases/download/v0.2.3/example.fastq.gz

doesn't work get a permission denied from amazon, please check the permissions

**Comment by IanSudbery** [comment]
hmmm.... works for me? We have no control over the permissions for this as it is simply hosted on the github releases page, which should be public access. Can you check again to see if it was just a temporary thing?

**Comment by TomSmithCGAT** [comment]
Can confirm this works for me to. @barkasn - Could you please post the complete error message

**Comment by barkasn** [comment]
It works fine now! Maybe it was a transient error. Thank you for your response. I'll close this.
