### ISSUE TITLE
added UMI-tools to bioconda

### ISSUE THREAD

**Issue by matthdsm** [CGATOxford/UMI-tools#42]
Hi

I've taken the liberty of adding the latest release of your tool to the bioconda repository.
I'm also working on a wrapper to be able to use the tool inside Galaxy

Hope you don't mind!

Cheers
M

**Comment by TomSmithCGAT** [comment]
@matthdsm Thanks very much! I had given it a go getting UMI-Tools into Bioconda but came up with errors and never got around to debugging.

Let us know if there's anything we can do to help.

Cheers
