### ISSUE TITLE
dedup option for 10x data

### ISSUE THREAD

**Issue by Vivianstats** [CGATOxford/UMI-tools#420]
Dear UMI-tools develop,

The bam files for 10x Genomics data (which I downloaded from a public database) do not contain gene tags. Can I run umi_tools dedup without the --per-gene option? Will this significantly impact the accuracy of results?

Thanks!

**Comment by IanSudbery** [comment]
Hi,

Yes, running without the `--per-gene` option will have a substainal (and negative) effect on the accuracy of the quantitation. This is because in the 10X protocol, fragmentation of the reads happens after PCR. This means that two copies of the same biological molecule can end up with different mapping locations. Unless `--per-gene` is used, two reads with the same UMI, but at different locations would be regarded as independent, but that would be incorrect in 10X data. 

You need to add the gene tag to the BAM file. You can do this with the `featureCounts` tool, as described in step 5 of the single cell tutorial in the documents:
https://umi-tools.readthedocs.io/en/latest/Single_cell_tutorial.html#step-5-assigning-reads-to-genes

**Comment by Vivianstats** [comment]
Thank you very much for the information!
I was able to obtain updated Bam files with gene tags, but I have one additional questions regarding the read numbers after the dedup step.

The original Bam files from treatment and control have similar cell numbers and similar sizes (767 million vs 838 million reads), but the retained reads after dedup differ a lot (80 million vs 145 million). I'd like to understand whether this difference is biological or technical artefact. 
I checked the summary information output by umi_tools (see below) and the total number of positions deduplicated were also very different between the two BAM files. I wonder according to your experience, is this common for two samples prepared using the sample procedure?

treatment:
> INFO Reads: Input Reads: 767468200, Read skipped, no tag: 257513051, Read skipped, missing umi and/or cell tag: 10474282
> INFO Number of reads out: 80253692
> INFO Total number of positions deduplicated: 16006539
> INFO Mean number of unique UMIs per position: 5.29
> INFO Max. number of unique UMIs per position: 95706

control:
> INFO Reads: Input Reads: 838664309, Read skipped, no tag: 273299226, Read skipped, missing umi and/or cell tag: 11722703
> INFO Number of reads out: 145393528
> INFO Total number of positions deduplicated: 26719528
> INFO Mean number of unique UMIs per position: 5.62
> INFO Max. number of unique UMIs per position: 102299

**Comment by TomSmithCGAT** [comment]
Hi @Vivianstats - From the summary in the log file, the number of positions deduplicated seems surprisingly high as this should be equal to the number of genes if you have used the `--per-gene` option. Could you please confirm the exact command used?

**Comment by Vivianstats** [comment]
Hi, thank you for your reply. 

I did use the --per-gene option. Here is the exact command:

`umi_tools dedup --extract-umi-method=tag --cell-tag=CB --umi-tag=UB --per-cell --per-gene --gene-tag=GX  -I C05.bam.1  -S normal.dedup.bam`

I'm also attaching an example read from the BAM file:

`J00159:16:HL5G3BBXX:4:2115:26636:18212	1040	chr1	3647500	255	101M	*	0	CTTCCTACCGACCCTTGTGTTTACCCTGTGCCAAAATACACTTTTCCTTTTCAAGTCCACTCTAGCCGGCTTAAGTGAGAATGATTTAGTGCATGATATTT	-JA7-F7JJF7FJFFJA7-F77-AA<JJJ<FJJ-77-<A-FJF7AF<7-77A7-JJJJFF<7-7-A7FA-A7A7FAJF7-<FFA7A-7JA-<A-FF<F-AA	NH:i:1	HI:i:1	AS:i:95	nM:i:2	TX:Z:ENSMUST00000192692,+2967,101M	GX:Z:ENSMUSG00000102331	GN:Z:Gm19938	fx:Z:ENSMUSG00000102331	RE:A:E	li:i:0	BC:Z:CGACTTGQT:Z:AAFFFJFJ	CR:Z:ACGATGTGTCTAGTCA	CY:Z:-AAF<FAJFJFJF7AJ	CB:Z:ACGATGTGTCTAGTCA-1	UR:Z:GTGGGGGTCA	UY:Z:FFJ7JJJFJJ	UB:Z:GTGGGGGTCA	xf:i:17	RG:Z:normal:0:1:HL5G3BBXX:4`

Are there any issues with the command I'm using? 
Really appreciate your help!

**Comment by IanSudbery** [comment]
My guess is that one file has more CBs than the other.  The deduplicated positions will be the produce of the number of genes and the number of cells. I notice that you arn't providing a CB whitelist? There is a standard 10X whitelist that contains all the CBs they put into their experiments.

**Comment by Vivianstats** [comment]
Just to confirm if I understand correctly, you mean there is an option to provide CB whitelist when running umitools dedup? Can you explain what's the advantage of adding this information?

**Comment by IanSudbery** [comment]
Oops. Sorry, I'm misremembering. Did you say these were BAMs you got from
the 10X website? I wonder if they are filtered to only real CBs?
