### ISSUE TITLE
errors in making whitelist

### ISSUE THREAD

**Issue by ayusyarif** [CGATOxford/UMI-tools#422]
Hi Ian,

I'd like to make a whitelist of single-end reads from bulk RNA sequencing. There are 2 fastq files for each sample (read 1 is the actual read, and read 2-A_R2.fastq- is the UMI sequence). 

when I submit this :
### umi_tools whitelist --stdin /Volumes/Backup\ Plus/Alignment_STAR/A_R2.fastq --bc-pattern='(?P<umi_1>.{8})' --extract-method=regex --set-cell-number=1 --log2stderr > whitelist.txt;

I got errors. 

### # UMI-tools version: 1.0.1
# output generated by whitelist --stdin /Volumes/Backup Plus/Alignment_STAR/A_R2.fastq --bc-pattern=(?P<umi_1>.{8}) --extract-method=regex --set-cell-number=1 --log2stderr
# job started at Mon Jul  6 07:39:37 2020 on Ayus-Air -- e9dbe620-237e-4fbb-89b6-ab38fe2e9987
# pid: 3173, system: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64
# allow_threshold_error                   : False
# blacklist_tsv                           : None
# cell_number                             : 1
# compresslevel                           : 6
# ed_above_threshold                      : None
# error_correct_threshold                 : 1
# expect_cells                            : False
# extract_method                          : regex
# filter_cell_barcodes                    : False
# knee_method                             : distance
# log2stderr                              : True
# loglevel                                : 1
# method                                  : reads
# pattern                                 : (?P<umi_1>.{8})
# pattern2                                : None
# plot_prefix                             : None
# prime3                                  : None
# random_seed                             : None
# read2_in                                : None
# short_help                              : None
# stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
# stdin                                   : <_io.TextIOWrapper name='/Volumes/Backup Plus/Alignment_STAR/A_R2.fastq' mode='r' encoding='UTF-8'>
# stdlog                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
# stdout                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
# subset_reads                            : 100000000
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# tmpdir                                  : None
# whitelist_tsv                           : None
Traceback (most recent call last):
  File "/Users/ayuhutamisyarif/miniconda3/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/Users/ayuhutamisyarif/miniconda3/lib/python3.7/site-packages/umi_tools/umi_tools.py", line 61, in main
    module.main(sys.argv)
  File "/Users/ayuhutamisyarif/miniconda3/lib/python3.7/site-packages/umi_tools/whitelist.py", line 348, in main
    options.pattern, options.pattern2))
TypeError: 'str' object is not callable

How do I solve this? do you have any suggestions? would that be possible to only use UMI without cell barcode?

**Comment by ayusyarif** [comment]
Hi ian,

so I changed the command to be like this:

> umi_tools whitelist --stdin /Volumes/Backup\ Plus/Alignment_STAR/A_R2.fastq --bc-pattern="(?P<umi_1>.{8})" --extract-method=regex --set-cell-number=1 --log2stderr > whitelist.txt;

and the errors I got:

> # UMI-tools version: 1.0.1
> # output generated by whitelist --stdin /Volumes/Backup Plus/Alignment_STAR/A_R2.fastq --bc-pattern=(?P<umi_1>.{8}) --extract-method=regex --set-cell-number=1 --log2stderr
> # job started at Mon Jul  6 08:04:57 2020 on Ayus-Air -- 9ebb0b23-4b2c-49fa-934e-01a5732e792a
> # pid: 3424, system: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64
> # allow_threshold_error                   : False
> # blacklist_tsv                           : None
> # cell_number                             : 1
> # compresslevel                           : 6
> # ed_above_threshold                      : None
> # error_correct_threshold                 : 1
> # expect_cells                            : False
> # extract_method                          : regex
> # filter_cell_barcodes                    : False
> # knee_method                             : distance
> # log2stderr                              : True
> # loglevel                                : 1
> # method                                  : reads
> # pattern                                 : (?P<umi_1>.{8})
> # pattern2                                : None
> # plot_prefix                             : None
> # prime3                                  : None
> # random_seed                             : None
> # read2_in                                : None
> # short_help                              : None
> # stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
> # stdin                                   : <_io.TextIOWrapper name='/Volumes/Backup Plus/Alignment_STAR/A_R2.fastq' mode='r' encoding='UTF-8'>
> # stdlog                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
> # stdout                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
> # subset_reads                            : 100000000
> # timeit_file                             : None
> # timeit_header                           : None
> # timeit_name                             : all
> # tmpdir                                  : None
> # whitelist_tsv                           : None
> Traceback (most recent call last):
>   File "/Users/ayuhutamisyarif/miniconda3/bin/umi_tools", line 11, in <module>
>     sys.exit(main())
>   File "/Users/ayuhutamisyarif/miniconda3/lib/python3.7/site-packages/umi_tools/umi_tools.py", line 61, in main
>     module.main(sys.argv)
>   File "/Users/ayuhutamisyarif/miniconda3/lib/python3.7/site-packages/umi_tools/whitelist.py", line 348, in main
>     options.pattern, options.pattern2))
> TypeError: 'str' object is not callable

**Comment by ayusyarif** [comment]
Hi Ian,

 I changed the command to be like this:
`umi_tools whitelist --stdin /Volumes/Backup\ Plus/Alignment_STAR/A_R2.fastq --bc-pattern='(?P<umi_1>.{8})' --extract-method=regex --set-cell-number=1 --log2stderr > whitelist.txt;`

It still gave an error as follows:

```
# UMI-tools version: 1.0.1
# output generated by whitelist --stdin /Volumes/Backup Plus/Alignment_STAR/A_R2.fastq --bc-pattern=(?P<umi_1>.{8}) --extract-method=regex --set-cell-number=1 --log2stderr
# job started at Mon Jul  6 07:59:28 2020 on Ayus-Air -- 3f0e3956-0a6a-44c6-91bc-4438c2af3c42
# pid: 3389, system: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64
# allow_threshold_error                   : False
# blacklist_tsv                           : None
# cell_number                             : 1
# compresslevel                           : 6
# ed_above_threshold                      : None
# error_correct_threshold                 : 1
# expect_cells                            : False
# extract_method                          : regex
# filter_cell_barcodes                    : False
# knee_method                             : distance
# log2stderr                              : True
# loglevel                                : 1
# method                                  : reads
# pattern                                 : (?P<umi_1>.{8})
# pattern2                                : None
# plot_prefix                             : None
# prime3                                  : None
# random_seed                             : None
# read2_in                                : None
# short_help                              : None
# stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
# stdin                                   : <_io.TextIOWrapper name='/Volumes/Backup Plus/Alignment_STAR/A_R2.fastq' mode='r' encoding='UTF-8'>
# stdlog                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
# stdout                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
# subset_reads                            : 100000000
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# tmpdir                                  : None
# whitelist_tsv                           : None
Traceback (most recent call last):
  File "/Users/ayuhutamisyarif/miniconda3/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/Users/ayuhutamisyarif/miniconda3/lib/python3.7/site-packages/umi_tools/umi_tools.py", line 61, in main
    module.main(sys.argv)
  File "/Users/ayuhutamisyarif/miniconda3/lib/python3.7/site-packages/umi_tools/whitelist.py", line 348, in main
    options.pattern, options.pattern2))
TypeError: 'str' object is not callable
```

**Comment by IanSudbery** [comment]
Hi ayusyarif,

I'm not entirely sure what you are trying to do. The whitelist command is designed to take the cell barcodes from a single-cell sequencing experiment, and identify which are real barcodes coming from droplets with exactly one cell in them. As such it is not applicable to bulk sequencing experiments, and the command won't work without a cell barcode being specified in the `bc-pattern` option.

**Comment by ayusyarif** [comment]
Hi Ian, 

Many thanks for your kind response. My next question would be is there any way for UMI-tools to tag fastq files only with UMI read? In my case, I have a bulk RNA sequencing data, which have UMI sequence in the read 2.

**Comment by IanSudbery** [comment]
Yes, this is what `extract` does. If your UMI is at the start of read2, you want a command that looks like:

`umi_tools extract --bc-pattern='(?P<umi_1>.{8})' --extract-method=regex -I read2.fastq.gz --read2-in=read1.fastq.gz -S read2.extracted.fastq --read2-out=read1.extracted.fastq`

**Comment by ayusyarif** [comment]
Hi Ian,

thank you very much for the script. I did exactly as same as you did with this command:

`umi_tools extract --bc-pattern='(?P<umi_1>.{8})' --extract-method=regex -I A_R2.fastq --read2-in=A_R4res.fastq -S read2.extracted.fastq --read2-out=read1.extracted.fastq`

However, it still gave me an error. 
`# UMI-tools version: 1.0.1
# output generated by extract --bc-pattern=(?P<umi_1>.{8}) --extract-method=regex -I A_R2.fastq --read2-in=A_R4res.fastq -S read2.extracted.fastq --read2-out=read1.extracted.fastq
# job started at Mon Jul  6 20:40:08 2020 on Ayus-Air -- 9b390585-0ff5-4ed4-bed9-aa9035da0061
# pid: 8267, system: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64
# blacklist                               : None
# compresslevel                           : 6
# either_read                             : False
# either_read_resolve                     : discard
# error_correct_cell                      : False
# extract_method                          : regex
# filter_cell_barcode                     : None
# filter_cell_barcodes                    : False
# log2stderr                              : False
# loglevel                                : 1
# pattern                                 : (?P<umi_1>.{8})
# pattern2                                : None
# prime3                                  : None
# quality_encoding                        : None
# quality_filter_mask                     : None
# quality_filter_threshold                : None
# random_seed                             : None
# read2_in                                : A_R4res.fastq
# read2_out                               : read1.extracted.fastq
# read2_stdout                            : False
# reads_subset                            : None
# reconcile                               : False
# retain_umi                              : None
# short_help                              : None
# stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
# stdin                                   : <_io.TextIOWrapper name='A_R2.fastq' mode='r' encoding='UTF-8'>
# stdlog                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
# stdout                                  : <_io.TextIOWrapper name='read2.extracted.fastq' mode='w' encoding='UTF-8'>
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# tmpdir                                  : None
# whitelist                               : None
2020-07-06 20:40:08,253 INFO Starting barcode extraction
Traceback (most recent call last):
  File "/Users/ayuhutamisyarif/miniconda3/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/Users/ayuhutamisyarif/miniconda3/lib/python3.7/site-packages/umi_tools/umi_tools.py", line 61, in main
    module.main(sys.argv)
  File "/Users/ayuhutamisyarif/miniconda3/lib/python3.7/site-packages/umi_tools/extract.py", line 397, in main
    read1s, read2s, strict):
  File "/Users/ayuhutamisyarif/miniconda3/lib/python3.7/site-packages/umi_tools/umi_methods.py", line 123, in joinedFastqIterate
    (pair_id, read2.identifier.split()[0]))
ValueError: 
Read pairs do not match
NS500195:564:H7KC3BGXF:1:11101:4855:1034 != NS500195:564:H7KC3BGXF:1:11101:9273:3405`

**Comment by ayusyarif** [comment]
Hi Ian,

Thank you very much for the script.
I did exactly as you suggested.

`umi_tools extract --bc-pattern='(?P<umi_1>.{8})' --extract-method=regex -I A_R2.fastq --read2-in=A_R4res.fastq -S read2.extracted.fastq --read2-out=read1.extracted.fastq`

However, there was an error again

```
# UMI-tools version: 1.0.1
# output generated by extract --bc-pattern=(?P<umi_1>.{8}) --extract-method=regex -I A_R2.fastq --read2-in=A_R4res.fastq -S read2.extracted.fastq --read2-out=read1.extracted.fastq
# job started at Mon Jul  6 20:40:08 2020 on Ayus-Air -- 9b390585-0ff5-4ed4-bed9-aa9035da0061
# pid: 8267, system: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64
# blacklist                               : None
# compresslevel                           : 6
# either_read                             : False
# either_read_resolve                     : discard
# error_correct_cell                      : False
# extract_method                          : regex
# filter_cell_barcode                     : None
# filter_cell_barcodes                    : False
# log2stderr                              : False
# loglevel                                : 1
# pattern                                 : (?P<umi_1>.{8})
# pattern2                                : None
# prime3                                  : None
# quality_encoding                        : None
# quality_filter_mask                     : None
# quality_filter_threshold                : None
# random_seed                             : None
# read2_in                                : A_R4res.fastq
# read2_out                               : read1.extracted.fastq
# read2_stdout                            : False
# reads_subset                            : None
# reconcile                               : False
# retain_umi                              : None
# short_help                              : None
# stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
# stdin                                   : <_io.TextIOWrapper name='A_R2.fastq' mode='r' encoding='UTF-8'>
# stdlog                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
# stdout                                  : <_io.TextIOWrapper name='read2.extracted.fastq' mode='w' encoding='UTF-8'>
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# tmpdir                                  : None
# whitelist                               : None
2020-07-06 20:40:08,253 INFO Starting barcode extraction
Traceback (most recent call last):
  File "/Users/ayuhutamisyarif/miniconda3/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/Users/ayuhutamisyarif/miniconda3/lib/python3.7/site-packages/umi_tools/umi_tools.py", line 61, in main
    module.main(sys.argv)
  File "/Users/ayuhutamisyarif/miniconda3/lib/python3.7/site-packages/umi_tools/extract.py", line 397, in main
    read1s, read2s, strict):
  File "/Users/ayuhutamisyarif/miniconda3/lib/python3.7/site-packages/umi_tools/umi_methods.py", line 123, in joinedFastqIterate
    (pair_id, read2.identifier.split()[0]))
ValueError: 
Read pairs do not match
NS500195:564:H7KC3BGXF:1:11101:4855:1034 != NS500195:564:H7KC3BGXF:1:11101:9273:3405

```

do you think that my file could be corrupt?

**Comment by ayusyarif** [comment]
Hi Ian, 
Just a quick clarification.
My data is single-end reads from bulk RNA sequencing, in which read 2 only contains UMI sequence without any actual reads.

Best,

Ayu

**Comment by IanSudbery** [comment]
The the process to work properly the two files must contain reads from the same fragment in the same order.  Thus, the 1st read in ` A_R2.fastq` must contain the UMI for the 1st read in `A_R4res.fastq`, the 2nd read in ` A_R2.fastq` the UMI for the 2nd read in `A_R4res.fastq`. 

`extract` checks this by checking that the names of the reads are the same in each file. This error is happening because at some point that isn't true. The usual reason for this is that the reads have been quality filtered independently of each other, and the filtering has removed reads from one file with removing the equivalent read from the other.

**Comment by ayusyarif** [comment]
Hi Ian, 

Thanks for the explanation. In this case, how would you think the best way to solve this? previously, I run the QC using fastp and trimmed the reads. Do you think it has something to do with this error?

Best, 

Ayu

**Comment by IanSudbery** [comment]
Any processing you do on the reads, must be done in a paired mode, so that any reads that are discarded are discarded from both files.

**Comment by ayusyarif** [comment]
Hi Ian,

Thanks for the explanation. I already solved the problem by using this command 

`gzip -cd /Volumes/Backup\ Plus/MSc\ Project/FASTq\ files_untrimmed/A_R2.fastq.gz | awk 'NR % 4 == 2' > /Volumes/Backup\ Plus/MSc\ Project/FASTq\ files_untrimmed/A_umi.tsv`

and proceed to extract command

`umi_tools extract --stdin=/Volumes/Backup\ Plus/Alignment_STAR/A_R4res.fastq --bc-pattern=NNNNNNNN --whitelist=/Volumes/Backup\ Plus/MSc\ Project/FASTq\ files_untrimmed/A_umi.tsv --stdout /Volumes/Backup\ Plus/Alignment_STAR/A.umi_tagged.fastq.gz`

I hope that could as valid as your method.

Best, 

Ayu

**Comment by IanSudbery** [comment]
This is not doing what I think you think it is doing. What you have written will take the first 8 bases of each read in `A_R4res.fastq` and remove it from the read and use it as the UMI for that read. That is, you are telling UMI-tools that your UMI is the first 8nt of your A_R4 file. In the abscence of any cell barcodes, the input from `--whitelist` is ignored.

**Comment by ayusyarif** [comment]
> Any processing you do on the reads, must be done in a paired mode, so that any reads that are discarded are discarded from both files.

So, what you mean is that I should QC both read 1 and read 2? rather than only QC the read 1 as I did previously?

**Comment by IanSudbery** [comment]
Specifically, you must run both reads through fastp with the same command. 

Alternatively (and probably easier) run `extract` first, and then run fastp on the extracted `A_R4` file.

**Comment by ayusyarif** [comment]
Hi Ian, 

Thank you very much for your help. do you mean to run this command as an easier way?
`umi_tools extract --bc-pattern='(?P<umi_1>.{8})' --extract-method=regex -I read2.fastq.gz --read2-in=read1.fastq.gz -S read2.extracted.fastq --read2-out=read1.extracted.fastq`

**Comment by ayusyarif** [comment]
Hi Ian,

Thank you very much for your help

So, I did run this command:

`umi_tools extract --bc-pattern='(?P<umi_1>.{8})' --extract-method=regex -I read2.fastq.gz --read2-in=read1.fastq.gz -S read2.extracted.fastq --read2-out=read1.extracted.fastq`

But, there are two outputs:
readA2.extracted.fastq 
readA1.extracted.fastq

In order to QC the sample as the next step, should I put them as pair-end reads in fastp command?

**Comment by IanSudbery** [comment]
I think you said that your `A_R2` file contains only the UMI and nothing else? In that case the reads in the `readA2.extracted.fastq` should be empty. Check this first. If thats true then you can just discard the `readA2.extracted.fastq` and continue with only the `readA2.extracted.fastq` file.

**Comment by ayusyarif** [comment]
Hi Ian,

Yes, that's definitely true. I just double-checked that. 
Thank you very much for your help.
very appreciated!

Best,

Ayu
