### ISSUE TITLE
How to deal with different UMI length?

### ISSUE THREAD

**Issue by tzhu-bio** [CGATOxford/UMI-tools#425]
Thanks for your great tools. I have a file with four lengths UMI, what should I do with your UMI-tools.
![image](https://user-images.githubusercontent.com/54537420/88800294-81dc5e00-d1da-11ea-929a-7bd67d6254e2.png)

**Comment by IanSudbery** [comment]
UMI-tools cannot compare UMIs of different lengths as the hamming distance between UMIs of different lengths is undefined.  Here I think you have several options, depending on what you think the relationship between two UMIs that are overlapping but different lengths: e.g could 

ATTACGTCATAAGAACCTT

and 

AATACG

have come from the same molecule? If the answer is no, then I think the easiest thing would be to separate the reads into different files based on their UMI lengths, and processes them independently, merging the deduplicated reads or counts at the end. 

If the answer is yes, then I think the best thing to do is to fill the missing bases on the shorter UMI with Ns, so 

AATACG

would become

ATTACGNNNNNNNNNNNNN

**Comment by link-dot** [comment]
Hi,

I have a similar question. 
I'm using a list of variable length UMIs, either 4bp or 5bp UMIs following these patterns: XXXX-TN or XXXXX-T.
UMIs are on both reads. The read starts with the UMI.
I have a list of fastq files, some with a 4bp UMI pattern and others with a 5bp UMI pattern.

How could I use the UMI-tools to capture the true design on a list of fastq files. Ideally, I'd like to extract the UMIs (4 or 5bp) and the T and/or TN following the UMI.
I saw the whitelist option. How could I use this please?

Thanks.

**Comment by TomSmithCGAT** [comment]
If the aims is to take a list of fastqs where one doesn't know the length of the UMI beforehand, but for each fastq the UMIs are all the same length, I'd suggest parsing the first few lines from each infile to identify the UMI length.

If one _really_ wanted you could do this within UMI-tools by running with options `--bc-pattern="^(?P<umi_1>.{4})TN.*" --extract-method=regex --subset-reads=10000 --log logfile` to search the first 10000 reads for those  where the start matches XXXXTN.

In logfile this will generate lines like so:
```
2020-08-13 22:39:02,379 INFO Input Reads: 10000
2020-08-13 22:39:02,379 INFO regex matches read1: 10000
2020-08-13 22:39:02,379 INFO Reads output: 10000

```

Comparing the output with the bc-pattern for XXXXT would tell you which pattern matched the most reads, from which you could infer which UMI pattern was more probable.

However, you would need to run `umi_tools extract` 3 times for each input file though (twice first to check the format) and parse the log files before extracting the full file. So this isn't really much easier than just parsing the fastqs to match the reads to the possible patterns yourself.

**Comment by TomSmithCGAT** [comment]
@tzhu-bio - Was Ian's response to your initial issue sufficient for you to proceed?

**Comment by tzhu-bio** [comment]
Sure! Thanks a lot!

**Comment by tzhu-bio** [comment]
> @tzhu-bio - Was Ian's response to your initial issue sufficient for you to proceed?

Sure, thanks a lot!
