### ISSUE TITLE
umi_tools does not work on unaligned BAM files

### ISSUE THREAD

**Issue by dkoppstein** [CGATOxford/UMI-tools#436]
Hi, 

Due to an issue with pysam, umi_tools does not currently work on BAM files that are unaligned (for example, that are output by picard IlluminaExtractBarcodes and picard IlluminaBasecallsToSam. This functionality would be nice to have, and could be solved by adding `check_sq=False` when using pysam.Samfile. 

c.f. [here](https://github.com/pysam-developers/pysam/issues/442)

**Comment by TomSmithCGAT** [comment]
Hi @dkoppstein ,

umi_tools is explicitly designed to consider alignment coordinate alongside UMI sequence for deduplication. Perhaps I am missing something here but I don't see how this functionality can be added without re-considering the entire rationale behind the deduplication process.

Why do you want to deduplicate unaligned reads?

**Comment by dkoppstein** [comment]
There are a few experiments with UMIs but no mapping step that would be useful to deduplicate using e.g. clustering, for example SELEX. Would there be some way to use for example sequences rather than mapping position to deduplicate? I think it would be quite useful.

**Comment by TomSmithCGAT** [comment]
I think this might be a case where the best route would be to use the underlying algorithms in UMI-tools directly: https://umi-tools.readthedocs.io/en/latest/API.html

It should be pretty straightforward to run `umi_tools extract` and then parse the resultant fastq and deduplicate using the `UMIclusterer` class as outlined in the link above. 

Personally speaking, I would be a bit uncomfortable extending the functionality of UMI-tools to include alignment-free deduplication directly as I don't have any experience with the technologies this would be applied to and wouldn't be aware of the pitfalls. If a user decides to use the algorithms to do this in a bespoke manner themeselves, then they are taking the responsibility for checking the approach is appropriate.

What are your thoughts on the above @IanSudbery

**Comment by TomSmithCGAT** [comment]
I should also add that there are alignment-free UMI clustering methods. I don't have any experience using them so can't make specific recommendations, though Calib comes to mind as one available tool: https://pubmed.ncbi.nlm.nih.gov/30351359/
