### ISSUE TITLE
Compromise for errors between cell and discard

### ISSUE THREAD

**Issue by mbahin** [CGATOxford/UMI-tools#439]
Hi,

I have a read pattern which is something like that:
  1) the first cell BC part (16bp among a collection of 96)
  2) a fixed known sequence of 4bp
  3) the second cell BC part (16bp among a collection of 96)
  4) a fixed know seq of 19bp
  5) the 8bp UMI

My goal is to use the fixed sequences, that can harbor errors as well as the BCs, as anchor to find the most precisely the BC and UMI.
At first, I wrote this pattern for the whitelist command:
`(?P<cell_1>.{16})(?P<discard_2>TGAC){e<=1}(?P<cell_2>.{16})(?P<discard_4>CAACTACGCTACGGAACGA){e<=4}(?P<umi_1>.{8})`
but then all the BCs, even the corrected ones, were 16bp-long. Since indels could happen, I would have expected some of the corrected BCs to be 15bp or 17bp-long. It looks like this pattern doesn't allow this. So I wrote this new one:
`(?P<cell_1>.{15,17})(?P<discard_2>TGAC){e<=1}(?P<cell_2>.{15,17})(?P<discard_4>CAACTACGCTACGGAACGA){e<=4}(?P<umi_1>.{8})`
but what happens is that most of the first part of the BCs are 17bp. Most certainly a deletion is considered on the fixed known sequences and the BC extended of 1 bp (actually most of the 17th bp of the first part of the BC are Ts, which is the first bp of the fixed known sequence).
What would you advice in this case to collect at best the BC (especially those with 1 indel)? Maybe I should keep the "15,17" for cell parts and use "s" instead of "e" in the error for fixed sequences?

Cheers,
Mathieu

**Comment by IanSudbery** [comment]
My first instinct is that a substitution in your fixed sequences is far more likely than an indel in your barcodes. I can't quite remember where I saw it, but I think indels are about an order of magnitude less common than substitutions.

**Comment by TomSmithCGAT** [comment]
Agree that substitutions should be far more common.

From the UMI-tools paper:
```Miscalling during sequencing is by far the most prevalent error, occurring one to two orders of magnitude more frequently than indels for Illumina sequencing (Marinier et al. 2015; Schirmer et al. 2015, 2016). Recombination is common when sequencing amplicons, but much rarer with the shotgun sequencing approaches in which UMIs are utilized (Schloss et al. 2011; Waugh et al. 2015). ```

@mbahin, using 's' for the fixed sequence error will indeed only allow substitutions in the fixed sequence, which should avoid the issue you're having with 17bp cell barcodes including the first T from the fixed sequence. If you use this regex (variable cell barcode length) and compare the number of reads retained to your first regex (fixed cell barcode length), I would expect you will see only a very minor gain.

**Comment by mbahin** [comment]
Thanks @TomSmithCGAT for your answer.
As expected, using "s" for the fixed sequence error is just a bit better than the other solution.

Cheers,
Mathieu
