### ISSUE TITLE
How to extract fastq files with the cell barcode still remained?

### ISSUE THREAD

**Issue by vagabond12** [CGATOxford/UMI-tools#445]
How to extract fastq files with the cell barcode still remained?

We just do not want to lose the cell barcode information in the extracted fastq files, especially in the R1 fastq files from 10x

**Comment by IanSudbery** [comment]
Do you want the barcode in two places - both on the read header and in the read sequence?

**Comment by TomSmithCGAT** [comment]
There's already a (hidden) option to do this for UMIs (`--retain-umi`), but not cell barcodes unfortunately. I see no reason not to add the option. --retain-umi` was hidden to avoid overloading users with options but perhaps we'd be better off making them both visible in an 'extended' options part of the `-help` text. `

**Comment by TomSmithCGAT** [comment]
Hi @vagabond12. I've added an option `--retain-cell-barcode` for `extract` on the [{TS}_addRetainCBoption branch](https://github.com/CGATOxford/UMI-tools/tree/%7BTS%7D_addRetainCBoption. Note that this is currently only compatible with `--method=regex`.

Would you mind installing UMI-tools from this branch and checking that the behaviour is as you expect. I've tested it out with one of our existing test files but would appreciate a external check too.

**Comment by vagabond12** [comment]
> Do you want the barcode in two places - both on the read header and in the read sequence?

@IanSudbery   Yes, thank you, and sorry for the delay of replying you.

**Comment by vagabond12** [comment]
> Hi @vagabond12. I've added an option `--retain-cell-barcode` for `extract` on the [{TS}_addRetainCBoption branch](https://github.com/CGATOxford/UMI-tools/tree/%7BTS%7D_addRetainCBoption). Note that this is currently only compatible with `--extract-method=regex`.
> 
> Would you mind installing UMI-tools from this branch and checking that the behaviour is as you expect. I've tested it out with one of our existing test files but would appreciate a external check too.






@TomSmithCGAT    Thank you for your kindhearted help, and sorry for the delay of replying you.

I have tried the new branch, and it really works for me. Thank you very much.




Afterwards, I found that the  processing speed  is about 4-fold slower than without retaining cellbarcode and UMI. 
Considering the large fastq files, it would take many hours to finish, and it is hard to bear.

Therefore, I suggest that you can optimize the extract.py file.  

More effectively, you could make new command, and had better not make some change at extract.py file. I believe that only extracting specific reads without adding cell barcodes and UMIs to the read head would be more easier.

Furthemore effectively,  if UMI-tools could support multiple threads, that would be much more wonderful and appreciated.

Thank you very much.
