### ISSUE TITLE
about whitelist of umi_tools

### ISSUE THREAD

**Issue by caijingtao1993** [CGATOxford/UMI-tools#448]
Dear，My library structure is read1-8bp UMI-dT-cDNA-read2，
![image](https://user-images.githubusercontent.com/67781404/101567101-2ed9a980-3a0b-11eb-9f14-1b043180ddd4.png)
I use the umi_tools code as follows: umi_tools whitelist --stdin 20200709CZL1-CKO-76_clean.R1.fq.gz --bc-pattern=(?P<umi_1>.{8})T{6}.* --extract-method =regex --set-cell-number=10 --log2stderr> whitelist.txt The result shows:
![image](https://user-images.githubusercontent.com/67781404/101567059-1a95ac80-3a0b-11eb-898c-60d1013e51d7.png)
How can I solve this error, please advise and look forward to your reply！

**Comment by caijingtao1993** [comment]
![image](https://user-images.githubusercontent.com/67781404/101569443-75c99e00-3a0f-11eb-8a71-ee4fe0447677.png)

**Comment by caijingtao1993** [comment]
I just used the form NNNNNNNNTTTTTT*, the code is: umi_tools whitelist --stdin 20200709CZL1-CKO-76_clean.R1.fq.gz --bc-pattern=NNNNNNNNTTTTT* --set-cell-number=10 --log2stderr> whitelist.txt The error is as follows:
![image](https://user-images.githubusercontent.com/67781404/101569764-0d2ef100-3a10-11eb-83cc-86093252ddbb.png)

**Comment by IanSudbery** [comment]
`whitelist` is designed for use on cell barcode sequences in single cell sequencing experiments. It is not necessary for experiments that include only a UMI.
