### ISSUE TITLE
`filter-out` option no work for SE reads

### ISSUE THREAD

**Issue by yech1990** [CGATOxford/UMI-tools#453]

**Comment by timedreamer** [comment]
Hi, I'm facing this problem also. Any solutions so far?
I got the error `UnboundLocalError: local variable 'read1' referenced before assignment`

Thanks!
Ji

**Comment by IanSudbery** [comment]
Hi, I just merged the PR from @yech1990 that should fix this. If you are able to install the latest from master, it should work. Let me know if you need help with that.

**Comment by timedreamer** [comment]
Hey great! If you could help with installing from master, that would be great! I used `conda` to install before.

**Comment by IanSudbery** [comment]
Hi @timedreamer 

I don't know how long the conda release will be as @TomSmithCGAT normally rolls these once there are a few changes to bundle up. 

To install from master:
1. Activate your conda environment.
2. Download/clone the code to any location of your choice with:
`git clone https://github.com/CGATOxford/UMI-tools.git`
3. Enter the UMI-tools directory:
` cd UMI-tools`
4. Install:
`python setup.py install`

You can delete the downloaded/cloned directory if you wish at this point.
