### ISSUE TITLE
sc rna seq data

### ISSUE THREAD

**Issue by yudizhangzyd** [CGATOxford/UMI-tools#457]
Hi there, 

I am wondering if you could tell me how does this data come from, this is the data in your manual http://cf.10xgenomics.com/samples/cell-exp/1.3.0/hgmm_100/hgmm_100_fastqs.tar

Do you have a Gene Expression Omnibus reference?

Thanks!
Yudi

**Comment by TomSmithCGAT** [comment]
Hi Yudi.

It's from the 10x genomics dataset:: https://support.10xgenomics.com/single-cell-gene-expression/datasets -> 'Cell Ranger 1.3.0' -> '100 1:1 Mixture of Fresh Frozen Human (HEK293T) and Mouse (NIH3T3) Cells'

I'm not actually sure if this dataset has been included in any publication

**Comment by yudizhangzyd** [comment]
Thanks, I want to extract reads just from 1 cell, so I only keep one line in the whitelist, however, when I used the extract command, it is not working, all the reads are included, do you know why? Thanks!

**Comment by IanSudbery** [comment]
Can you please post the exact commands you are using?
