### ISSUE TITLE
Improve non-conda setup

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/UMI-tools#46]
Currently Conda installation works well, but installation via pip or downloading the tarball works much less well.

The current problems are:
- Although setuptools allows downloading and installing of dependencies, the current setup.py requires them to be installed before it has the chance to install them
- Assumes that setuptools is installed

In order to fix:
- [x] Bootstrap setuptools to install or update setuptools before importing using ez_setup.py
- [x] Remove requirements for normal dependencies and rely on install_requires to install them correctly
- [x] Distribute pre-cythonised extensions so that Cython is not required just to run setup.py
- [x] Create detailed instructions on installation.
- [x] Test on Ubuntu, CentOS and Mac OSX

**Comment by IanSudbery** [comment]
cc: @TomSmithCGAT 
requirements.txt not included in pip tarball

- [ ] Add requirements.txt to pip tarball

**Comment by IanSudbery** [comment]
setuptools claims pysam isn't installed when it is

**Comment by IanSudbery** [comment]
@TomSmithCGAT:  See the install branch

Setup is now pretty much working on Linux (or where it isn't I know the problem and why it can't be fixed). and I've written an installation guide. This all needs test on OS X. If possible, this needs to be:

*  By all three routes (Conda, pip, source)
*  On a factory fresh install (I believe that if you are on a Mac, you can run OS X VMs for this)
*  On more 10.8 and the most recent OS X.

You have a Mac right? Can you do some of these tests?

**Comment by TomSmithCGAT** [comment]
@IanSudbery Thanks for the work on the install branch. I'll test Mac later this week.

**Comment by TomSmithCGAT** [comment]
@IanSudbery I think we still need cython for setup.py. I'm testing out the installation from source with a clean python library and I get the following error when I run python setup.py install:

NameError: global name 'tempita' is not defined

It looks like this is becuase pandas needs cython though it doesn't currently error if cython is not available [#14202](https://github.com/pydata/pandas/issues/14204).

If I install cython first, setup.py install works fine.

Should we go back to throwing an error in setup.py if cython is not installed?

**Comment by TomSmithCGAT** [comment]
The issue with cython is resolved by including cython in the `setup_requires` variable - see 7bd0cedd4e9c6ac92168ce854372a76cd96ba1f6

**Comment by TomSmithCGAT** [comment]
@IanSudbery.

I've tested the following on Mac (OS X El Capitan, 10.11.6) with a clean python library: 

- pip (v0.2.3) 
- conda (latest commit on the install branch) 
- from source (latest commit on the install branch) 

I had some issues with pip when using the default python location, relating to the the new OS X feature Security Integrity Protection which prevents anyone (inc. root) from writing to particular locations - see [here](http://apple.stackexchange.com/questions/209572/how-to-use-pip-after-the-os-x-el-capitan-upgrade). I don't know whether this is really something we want to discuss in the installation guide though seen as there are a myriad of ways to deal with this. Perhaps we should just recommend that OS X user don't use the default python?

**Comment by IanSudbery** [comment]
Interesting. 

The trouble with cython in setup_requires, is that although easy_install respects setup_requires, pip doesn't. I did put in the installation guide that if you are installing from source, you need to install cython first. 

The thing with the defaul python on OS X is annoying ... its all very well to tell people they need to not use the default python, but thats going to frighten a bunch of people that don't even know what `python` is. 

I know that I skip any package that says it need `perl`, but won't accept the system default one because installing an up-to-date `perl` on our system proved such a PITA. But if thats the way it is, thats the way it is. We should probably just point people to a tutorial on using a python other than the default one.

**Comment by IanSudbery** [comment]
How clean did you test - If you are going to use `pip`, then I think you need to test if the instuctions for installing `pip` work, because I don't think that OS X comes with `pip` installed as default. Also there is no C compiler (gcc) installed by default on OS X.

**Comment by TomSmithCGAT** [comment]
Hi Ian. Agree it's a shame to have to ask the user to use a non-default python but I think the target user should be OK with this. Perhaps we could add in an example of how to do this by installing python using homebrew as per the instructions [here](http://docs.python-guide.org/en/latest/starting/install/osx/) - homebrew also installs pip and setuptools at the same time.

**Comment by TomSmithCGAT** [comment]
I installed pip using `sudo easy_install pip`. The instructions for installing pip using curl work too.

**Comment by AndreasHeger** [comment]
Hi all, @sebastian-luna-valero did a lot of this work for the CGAT script collection including installation how-tos for OSX. You could modify those.

**Comment by sebastian-luna-valero** [comment]
Hi All,

Sorry but I have just been working on the Linux installation. The OSX how-to for the CGAT code is here:
https://www.cgat.org/downloads/public/cgat/documentation/CGATInstallationOSX.html

but that was written by @AndreasHeger :-D

IMHO, there is an amazing work being done over at Bioconda:
https://bioconda.github.io/
https://github.com/bioconda/bioconda-recipes

which involves Linux and OSX installation and testing with both Python 2.7 and Python 3.5, **all automated**. I would definitely favour bioconda over homebrew for OSX deployment.

I was working with @TomSmithCGAT a little bit on Friday to help with the bioconda package, and I am happy to assist further if required.

**Comment by TomSmithCGAT** [comment]
@IanSudber I've updated the Mac installation instructions (415f03581dee395a3550d2d43c479704f5367d15) so I think we're ready to merge the install branch, right? I'm assuming you've tested out the installation on Linux ?

**Comment by IanSudbery** [comment]
@TomSmithCGAT Cheers. I have tested the linux install on fresh,  minimal installs of both CentOS and Ubuntu.

I have been working on the quick start guide (still stuff to do there) on the install branch, so we should either spin that off into a separate branch or hold off merging for now.

**Comment by TomSmithCGAT** [comment]
OK. Let's hold off until the quick start guide is ready then.

**Comment by IanSudbery** [comment]
Hey @TomSmithCGAT give the QUICK_START guide a go. We also need to think about how to distribute it - it doesn't work too bad as a markdown, and it is then displayed nicely on GitHub. The alternative would be to generate an HTML and put it somewhere.

**Comment by TomSmithCGAT** [comment]
@IanSudbery Great. I'll give it a try shortly. I'm very happy to have it as markdown to be viewed on Github for now. I guess if want to have it hosted elsewhere we might want to think about using [readthedocs](https://readthedocs.org/) to update our documentation with each commit. 

If we did build a more comprehensive website, this would also give me a chance to unveil my majestic logo..
![umi_tools_logo_darker](https://cloud.githubusercontent.com/assets/6096414/19521726/a4dea98e-960c-11e6-806a-a18ff04a391e.png)
This was only 5 minutes work so any suggestions very welcome! I'll pop it up on the top of the readme when we're happy with it

**Comment by TomSmithCGAT** [comment]
@IanSudbery Tutorial worked perfectly for me. I've added mac-specific commands for the downloads and a section about bespoke extract UMIs. See 8614595. If you're happy, I think we're ready to merge!

**Comment by TomSmithCGAT** [comment]
Logo is now on the homepage. Github appears to ignore the width directive so it's massive!

**Comment by IanSudbery** [comment]
I believe we are ready to merge. (Love the logo by the way)

**Comment by TomSmithCGAT** [comment]
Ack. Travis test is failing. I'll have a look at this first thing tomorrow.

**Comment by IanSudbery** [comment]
@TomSmithCGAT Did you sort out what was happening with travis? I'm trying to pull request a bug fix, and the travis checks are failing.

**Comment by TomSmithCGAT** [comment]
@IanSudbery. All sorted now. I'll merge back into the master and release a new version

**Comment by IanSudbery** [comment]
:thumbsup:
:+1:
