### ISSUE TITLE
Error when using --extract-method=regex

### ISSUE THREAD

**Issue by retrogenomics** [CGATOxford/UMI-tools#460]
**UMI-tools version: 1.1.1** (but I think the problem was the same on 0.5.x, I've tried to update to see if it was a bug that had been corrected), running on Linux (openSUSE 15.2).
 
This command line **does not work**
```
  umi_tools extract \
    --stdin="sample.adapt3_trim.fq.gz" \
    --extract-method=regex \
    --bc-pattern="^(.{4})G" \
    --log="sample.umiG.log" \
    --stdout "sample.umiG.fq.gz"
```
giving this error:

> Traceback (most recent call last):
>   File "/scratch/bin/RNA_Seq/UMI-tools/bin/umi_tools", line 8, in <module>
>     sys.exit(main())
>   File "/scratch/bin/RNA_Seq/UMI-tools/lib64/python3.6/site-packages/umi_tools/umi_tools.py", line 61, in main
>     module.main(sys.argv)
>   File "/scratch/bin/RNA_Seq/UMI-tools/lib64/python3.6/site-packages/umi_tools/extract.py", line 326, in main
>     extract_cell, extract_umi = U.validateExtractOptions(options)
>   File "/scratch/bin/RNA_Seq/UMI-tools/lib64/python3.6/site-packages/umi_tools/Utilities.py", line 1179, in validateExtractOptions
>     options.pattern, options.pattern2))
> TypeError: 'str' object is not callable

While this command line **works perfectly** (the only differences are the `--extract-method` and `--bc-pattern` arguments):
```
  umi_tools extract \
    --stdin="sample.adapt3_trim.fq.gz" \
    --extract-method=string \
    --bc-pattern=NNNN \
    --log="sample.umiG.log" \
    --stdout "sample.umiG.fq.gz"
```

Any idea of what could be the issue?
Thanks for your help

**Comment by IanSudbery** [comment]
There are two things going on here. The first is that you do not specify that the group in the regex is an UMI group. You do this using named capture groups like so:

```
 umi_tools extract \
    --stdin="sample.adapt3_trim.fq.gz" \
    --extract-method=regex \
    --bc-pattern="^(?P<umi_1>.{4})G" \
    --log="sample.umiG.log" \
    --stdout "sample.umiG.fq.gz"
```

The second thing that is going on is that there was a typo in the code that raise an error. That but has actaully been fixed in the latest commit on the master branch, but has not made it into a release yet.

**Comment by retrogenomics** [comment]
Thanks for your help Ian, I didn't realize that the naming was obligatory. It seems to work once the pattern has been corrected, despite the typo in the code that you mentioned. Since umi_tools is installed on our server by our IT team, I was thinking to continue using v1.1.1 to avoid bothering them with a provisional update. Do you think this may be a problem?

**Comment by IanSudbery** [comment]
I'm sure its fine. I don't think that getting the text of an error message correct is worth much in the way of hassle.

**Comment by retrogenomics** [comment]
Indeed I thought the typo was causing the error, not that the typo was _in_ the error message ! Thanks a lot.
