### ISSUE TITLE
Release notes not up to date

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/UMI-tools#472]
The last version that has release notes is 1.0.0, two versions ago. There are some options that are currently undocumented (e.g. --ignore-tlen). I'll try to get to this over the next week, but this is a marker for if I don;t/.

**Comment by TomSmithCGAT** [comment]
Done. I just tend to copy over the notes in https://github.com/CGATOxford/UMI-tools/releases and update formatting. I'll leave the issue open until I can check the Read the Docs page renders OK.

**Comment by TomSmithCGAT** [comment]
Hmm.. Took a couple of goes but all seems OK now.
