### ISSUE TITLE
Deduplicating bam files without UMIs

### ISSUE THREAD

**Issue by SPPearce** [CGATOxford/UMI-tools#475]
This might be a strange request, but is there a way to run `umi_tools dedup` on bam files that don't have UMIs in the headers? I have a few older sequencing runs that don't have UMIs, and I'd like to run them through my same pipeline that I've been using with my data with UMI data that I process with `umi_tools extract` and `umi_tools dedup`. I could hack the headers to give them all identical fake UMI, but just wondered if there was any other option that I have missed, like a simple flag combination. Or do I have to break out picard for this.

**Comment by TomSmithCGAT** [comment]
Hi Simon. No option unfortunately. As you suggest, your options are to use `picard` or add a psuedo UMI.

**Comment by IanSudbery** [comment]
There IS an `--ignore-umi` option, that was in there from the very earliest
days for debugging and benchmarking. Don't know if that would work.

**Comment by SPPearce** [comment]
Perfect, thanks Ian, I'd missed that was an option available. That lets me process these without having to swap to a different tool.

**Comment by IanSudbery** [comment]
I'm not guaranteeing that this will work, because it might try to extract the UMI and then throw it away.

**Comment by SPPearce** [comment]
It seems to work, it no longer complains that the read headers are missing the UMIs and gives me a deduplicated output.

**Comment by IanSudbery** [comment]
Great! Glad it worked. 

I'm closing this for now. Feel free to reopen if necessary.
