### ISSUE TITLE
Using group/dedup --random-seed and PYTHONHASHSEED=0

### ISSUE THREAD

**Issue by alexander-e-f-smith** [CGATOxford/UMI-tools#479]
Hi. To  keep outputs consistent for umitools group or dedup, I'm setting both PYTHONHASHSEED=0  and using the umitools --random-seed option (arbitrarily at 100). To your knowledge, would there  be any drawbacks/negatives from doing this in regular practise (production NGS pipelines), rather than just in pipeline testing/validations??

**Comment by IanSudbery** [comment]
I don't personally see any problem.
