### ISSUE TITLE
Extracting UMI into read header and removing trailing sequence

### ISSUE THREAD

**Issue by abracarambar** [CGATOxford/UMI-tools#480]
Hi, I am trying to extract UMI out of a QIAseq miRNA Library (single ended).
here is an example of read:
@A00152:427:HFNTNDRXY:1:2101:7220:1000 1:N:0:NTCACTATGT+CTACCGAATT
ANCACCGATGGAATGGCTTGGAGA**AACTGTAGGCACCATCAAT**_CGCCAGTGTAAG_
Adapter in bold, UMI in italics

 I am using the following command:

umi_tools extract  --extract-method=regex  --bc-pattern=".+(?P<discard_1>AACTGTAGGCACCATCAAT){s<=2}(?P<umi_1>.{12})(?P<discard_2>.+$)" -I sample.fastq.gz  -S sample.ed.fastq.gz

But it only manages to detect the regex for a small portion of the reads in the fastq file
2021-07-07 13:00:37,954 INFO regex does not match read1: 22298307
2021-07-07 13:00:37,954 INFO regex matches read1: 156155

The adapter AACTGTAGGCACCATCAAT is definitely detected in most reads if I use cutadapt. Is there something else that is not specified properly in my command?
Thanks for the help.

**Comment by TomSmithCGAT** [comment]
Did this work?

**Comment by abracarambar** [comment]
Thank you so much, it did! I wasn't sure if there would be trailing adapters after the UMI but that does not seem to be the case.
