### ISSUE TITLE
misleading default in help text

### ISSUE THREAD

**Issue by bernt-matthias** [CGATOxford/UMI-tools#484]
The default is actually to do no error detection: https://github.com/CGATOxford/UMI-tools/blob/7d7d67ca2cb36963dbb3e9e2f0f761f483606cdc/umi_tools/whitelist.py#L294

**Comment by IanSudbery** [comment]
This has been changed
https://github.com/CGATOxford/UMI-tools/commit/6b0d30b8df6ae207fd483545da7c7633d8107c09#diff-243a25ea5a4993fe85df9629ca85691175ebeeaada53293833ea9df15a9098d8
