### ISSUE TITLE
whitelist error :Syntax error near unexpected symbol ` ('

### ISSUE THREAD

**Issue by jehuliu** [CGATOxford/UMI-tools#491]
When use the umi_tools whitelist, I got a error: Syntax error near unexpected symbol ` ('
 Could you please help to solve this problem? The code was follows:

sample="barcode1_BDSW210000636-1A_1 barcode1_BDSW210000636-1A_2 barcode2_BDSW210000637-1A_1 barcode2_BDSW210000637-1A_2"
for s in $sample
do
umi_tools whitelist -I $s.fq.gz --method=umis --extract-method=regex -p (?P<umi_1>.{4}) -S $s.whitelist.txt
wait
done

**Comment by IanSudbery** [comment]
Did this work?

**Comment by IanSudbery** [comment]
I'm going to assume that this fixed the problem and will close the issue. Please let me know if this is not the case and I will reopen.
