### ISSUE TITLE
How is mapping coordinates for UMI group defined?

### ISSUE THREAD

**Issue by YichaoOU** [CGATOxford/UMI-tools#492]
Hello,

For single-end data, `same mapping coordinates` means `same read start`, regardless of read end?

For paired-end data, `same mapping coordinates` means what?

Thanks,
Yichao

**Comment by IanSudbery** [comment]
For single end data, "same mapping coordinate" is almost "same read start", but we also account for softclipping. So if a read has the start coordinate of "100", but two bases are softclipped from the 5' end, the coordinate we use is "98". 

For paired end, "same mapping coordinate" means the two reads have both the same start coordinate, as definted above, but also the same insert length (which we use as a proxy for the postion of read two.

**Comment by YichaoOU** [comment]
Thank you so much for the quick reply!
