### ISSUE TITLE
Will --ignore-read-pair-suffixes turn on or turn off the "ignore"?

### ISSUE THREAD

**Issue by realzhang** [CGATOxford/UMI-tools#497]
Dear developers:

I use '--ignore-read-pair-suffixes' in the command line of umi_tools, but it seems set 'has_suffix" True and run "getReadIDSuffix" instead of "getReadIDNoSuffix" in the file of "umi_methods.py".
When I use  '--ignore-read-pair-suffixes', the umi_tools errs with "ValueError: read suffix must be /1 or /2. Observed: 16". The header of my fastq file is like '@A00541:182:HLK5CDSX2:3:1101:1823:1016 1:N:0:GAGATTCC+TAATCTTA' for R1 and '@A00541:182:HLK5CDSX2:3:1101:1823:1016 2:N:0:GAGATTCC+TAATCTTA' for R2.

So now I remove '--ignore-read-pair-suffixes' from the command line, and umi_tools runs smoothly.

This seems strange, and I report it here.

Thanks for your great tools.

**Comment by realzhang** [comment]
I get it. Your reply is very clear. Thanks a lot.

**Comment by TomSmithCGAT** [comment]
Great. If you think the documentation is unclear, let me know and I'll take another look at it.

**Comment by IanSudbery** [comment]
I'm going to close this for now. @realzhang If you've got recommendations for documentation, please feel free to reopen.
