### ISSUE TITLE
PyPi doesn't have 1.1.2 release

### ISSUE THREAD

**Issue by wjdingman1** [CGATOxford/UMI-tools#499]
Just checking if this was intentional or not?

**Comment by IanSudbery** [comment]
No, definitely not. We'll see what we can do about fixing that

**Comment by wjdingman1** [comment]
great thanks!

**Comment by TomSmithCGAT** [comment]
Should be available now @wjdingman1. Do you mind checking it's all working OK.

**Comment by wjdingman1** [comment]
looks good, thank you!
