### ISSUE TITLE
Missing NH tags

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/UMI-tools#5]
dedup_umi is not very happy if the NH tag is missing from a bam entry:

```python-traceback
Traceback (most recent call last):
  File "/ifs/projects/proj028/src/dedup_umi.py", line 413, in <module>
    sys.exit(main(sys.argv))
  File "/ifs/projects/proj028/src/dedup_umi.py", line 390, in main
    soft_clip_threshold=options.soft):
  File "/ifs/projects/proj028/src/dedup_umi.py", line 288, in get_bundles
    if reads_dict[pos][key][umi]["read"].opt("NH") < read.opt("NH"):
  File "pysam/calignmentfile.pyx", line 3571, in pysam.calignmentfile.AlignedSegment.opt (pysam/calignmentfile.c:38787)
  File "pysam/calignmentfile.pyx", line 3286, in pysam.calignmentfile.AlignedSegment.get_tag (pysam/calignmentfile.c:33926)
KeyError: "tag 'NH' not present"
```

 This is an optional BAM tag, and is not added by either bowtie or BWA. On the other hand, selecting which of a selection of reads maps to the fewest unique locations is part of the read selection process.

There are three options here. 
1. wrap the NH statements in `try` statements and ignore this criteria if not present. 
2. Have specific hacks for the way BWA and bowtie specifiy multiple hits
3. Require users to edit their BAMs not make sure NH is present. 

Views?

**Comment by TomSmithCGAT** [comment]
My first impression is that we should go for option 3 and provide a tool in the repository (stripped back bam2bam.py?). Looking at the relevent code in bam2bam the tool for adding nh tags would be very small. However, we're then requiring the user to possibly generate new BAMs and this might be a slight barrier to people taking up the tool.

Perhaps the best option would be to paramaterise the multi-mapping detection to one of the following:

1. NH tag

2. MapQ
BWA and bowtie 1 use mapQ=0 for muiltimapping I think

3. XS vs AS tags
Bowtie2 gives mapping scores for the first hit in the AS tag and the second hit in the XS tag. If the mapping scores are the same (or very similar?), not uniquely mapped.

**Comment by AndreasHeger** [comment]
Hi, 

if this tool is very popular you will find that there are all sort of BAM-files that people use. It might be worth adding a method detect_bam_features() to check what kind of bam-file you have and then set
flags (such as has_nh, use_nh, has_xs, use_xs, use_mapq) and allow users to override them via command-line options.

You can pack bam2bam, but you could also just suggest to use it.

Best wishes,
Andreas

**Comment by TomSmithCGAT** [comment]
@AndreasHeger Thanks for the suggestion. That seems the most sensible way to implement my suggestion to enable detection of multimapping by different means. 

@IanSudbery Are you happy with this solution? If so I can implement it some time next week.

**Comment by TomSmithCGAT** [comment]
I've implemented a solution and pushed it. However, as soon as I did I began to wonder why we're using bam tags for multi-mapping at all?..

Current, we're not actually removing multi-mapping reads explicitly, we just select the read with the best MAPQ as the representative read at each position/orientation/umi combination. Where MAPQs are tied, we select the read with the smallest number of "best" alignments (using NH). Is it actually possible for two reads to have the same MAPQ but different number of "best" alignments? If not, we can do away with the checks on bam tags entirely and just use the MAPQ. 

On a related note, should we include a MAPQ filter (say >20)?

**Comment by IanSudbery** [comment]
I think it is possible. Consider the following situation:



Two reads have a different single basepair miss-matches to the reference
sequence at the location currently under consideration. This would give
them the same MAPQ. Its quite possible that the different miss-matches mean
that the two reads could match different numbers of other positions.



Explain futher with the MAPQ filter. Do you mean filter out reads with a
MAPQ below 20? Surely this could be done independently if the user wished.
More important would be to filter out UMIs with a low base call quality,
but for this we’d need to change the script that removed the UMIs from the
reads.



Ian





*From:* Tom Smith [mailto:notifications@github.com]
*Sent:* 17 July 2015 13:59
*To:* CGATOxford/UMI-tools
*Cc:* Ian Sudbery
*Subject:* Re: [UMI-tools] Missing NH tags (#5)



I've implemented a solution and pushed it. However, as soon as I did I
began to wonder why we're using bam tags for multi-mapping at all?..

Current, we're not actually removing multi-mapping reads explicitly, we
just select the read with the best MAPQ as the representative read at each
position/orientation/umi combination. Where MAPQs are tied, we select the
read with the smallest number of "best" alignments (using NH). Is it
actually possible for two reads to have the same MAPQ but different number
of "best" alignments? If not, we can do away with the checks on bam tags
entirely and just use the MAPQ.

On a related note, should we include a MAPQ filter (say >20)?

—
Reply to this email directly or view it on GitHub
<https://github.com/CGATOxford/UMI-tools/issues/5#issuecomment-122266892>.[image:
Image removed by sender.]

**Comment by TomSmithCGAT** [comment]
@IanSudbery Good point. I think BWA might actually take the number of mapping locations into account when calculating MAPQ but the manual page is currently unavailable so I can't confirm this.

Regarding filtering, yes this is what I was thinking. I guess we can just add it later if we want. I think we should implement umi sequence quality filtering at a later date too.

I've checked the deduping on a bam with all three tags (NH, X0, XT) and the results are identical so I'm happy the tool can use these tags. If no tag is chosen, only MAPQ is used.
