### ISSUE TITLE
How to collapse reads in bam from the result of UMI-tools group

### ISSUE THREAD

**Issue by camelest** [CGATOxford/UMI-tools#501]
Hi, first of all, thank you for the wonderful tool.

I have a question regarding UMI-tools dedup.

Is there a way to output UMI-collapsed bam files using the results from UMI-tools group, without running UMI-tools dedup again? In other word, how to dedup a bam file when UMI tags are added and read grouping are already done?

Thank you in advance for your help.

Best,

**Comment by IanSudbery** [comment]
We don't have a way to do this in UMI-tools itself I'm afraid, you would need to write the code yourself.

**Comment by camelest** [comment]
I see, thank you for your prompt reply.
Best,
