### ISSUE TITLE
AssertionError: not all umis are the same length(!):  6 - 7

### ISSUE THREAD

**Issue by MatthiasSchmitz93** [CGATOxford/UMI-tools#507]
Hi, I'm completely new to bioinformatical analysis, so I hope this is enough information to diagnose my problem.

I got the following error after running `umi_tools dedup -I input.bam --output-stats=deduplicated -S output.bam`
```
2022-01-22 18:22:11,452 INFO total_umis 8084052
2022-01-22 18:22:11,452 INFO #umis 6586011
Traceback (most recent call last):
  File "/home/matt/anaconda3/envs/umitools/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/home/matt/anaconda3/envs/umitools/lib/python3.7/site-packages/umi_tools/umi_tools.py", line 61, in main
    module.main(sys.argv)
  File "/home/matt/anaconda3/envs/umitools/lib/python3.7/site-packages/umi_tools/dedup.py", line 331, in main
    threshold=options.threshold)
  File "/home/matt/anaconda3/envs/umitools/lib/python3.7/site-packages/umi_tools/network.py", line 419, in __call__
    clusters = self.UMIClusterer(counts, threshold)
  File "/home/matt/anaconda3/envs/umitools/lib/python3.7/site-packages/umi_tools/network.py", line 369, in __call__
    min(len_umis), max(len_umis)))
AssertionError: not all umis are the same length(!):  6 - 7
```

Head of BAM file (`samtools view input.bam | head -n 6`):
```
6073959 0       1       3125394 3       28M     *       0       0       AACAACAACAACAACAACAACGTATCTA    *       nM:i:2  MD:Z:25A1G0     NH:i:2
5614728 0       1       3567528 255     31M     *       0       0       TCTCCCCCCCCCCCCGTTAAAAAATTTATGT *       nM:i:7  MD:Z:18T0T0T2T3G1T0C0   NH:i:1
4404284 272     1       3717890 3       22M     *       0       0       TTTGAATTGATCATGGTAGTTG  *       nM:i:5  MD:Z:0C0C0C0T1C16       NH:i:2
623104  0       1       3741776 255     24M     *       0       0       AGTGGTGGCCATGTTTTTTTAAGG        *       nM:i:4  MD:Z:16G1G1C2A0 NH:i:1
3557856 0       1       3743254 255     46M     *       0       0       AGTGGTTGGTTTTTTTTTATTTTTTTGTTTTTGGTTATGTTGAAAA  *       nM:i:9  MD:Z:23G2C1C4C0C0C1G1G4G1       NH:i:1
3947152 0       1       3819739 255     25M     *       0       0       TATGAGAGAGATAGAGAGGGAAAGA       *       nM:i:3  MD:Z:0A0T0A22   NH:i:1
```
Head of fastq file:
```
@NB500937:552:HKNVMAFX2:1:11101:17965:1104_ACGGCC 1:N:0:GATCACAT+NTGGCGGT
CATCAACTTCCCACTGTACACCACCACATCAATCAAATTCTCCTTCATTATTAGCCTCTTAC
+
EEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEE
@NB500937:552:HKNVMAFX2:1:11101:11576:1104_ATGGAA 1:N:0:GATCACAT+NTGGCGGT
CGCGGTTCTATTTTGTTGGTTTTCGGAACTGAGGCCATGATTAAGAGGGACGGCCGGGGGCATTCGTATTGCGCCGCTAGAGGTGAAATTCTTGGACCGGCGCAAGACG
+
EEEEEEEEEEEEEEEEEEE/EEEEEEEEEEEEEEEEEEEEAEEEEAEEE<EEA/A/EE<A/AEE/EEAEEEE/EEEEEEEE/EAAAEEEE<AEEE//AAE<EEAEE<AE
@NB500937:552:HKNVMAFX2:1:11101:7931:1105_AAGAAC 1:N:0:GATCACAT+NTGGCGGT
GAAAGATGAGTGAGGCTGCAGCCAAATGGTCTGCCTTTTATGAAGAACAGACTAAGACTGCACAAAGTTTCTCACTACAAGAAATCCA
```
Here my UMIs are ACGGCC, ATGGAA, and AAGAAC. I put the first 100 000 lines of the fastq file in a text document and couldn't find any UMIs of length 7. I also don't understand how UMIs are stored in BAM files.

**Comment by TomSmithCGAT** [comment]
Hi Matthius.

Thanks for the nicely detailed issue 😄 

UMI-tools `dedup` command extracts the UMI from the query name (first field). The aligner should use the name from the fastq as the query name, e.g `@NB500937:552:HKNVMAFX2:1:11101:17965:1104_ACGGCC` for your first read in the fastq above. However, you seem to have numerical query names, e.g `6073959` in the first record in the BAM above. 

What aligner did you use and were there any other steps inbetween alignment and `dedup`?

**Comment by MatthiasSchmitz93** [comment]
Hi Tom,

Thank you for your quick reply!
I used the STAR aligner. Here are the steps I took:

I used a tools called GEDI (https://github.com/erhard-lab/gedi) to prepare the mouse genome for indexing (and the spike-in control (ERCC)).

I created the STAR index:
 `nohup STAR --runMode genomeGenerate --runThreadN 8 --genomeDir mus_ERCC_index --genomeFastaFiles /home/matt/data/test/mus_musculus.101.fasta /home/matt/data/test/ERCC92.fa --sjdbGTFfile mus_ERCC.gtf &`

I created a pipeline for the mapping using GEDI and then ran the bash file that GEDI created which contains the following command:
`STAR --runMode alignReads --runThreadN 8   --genomeDir /home/matt/data/mus_ERCC_index  --limitBAMsortRAM 8000000000 --outFilterMismatchNmax 20 --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesIn C01__1_IR.fastq --outSAMmode NoQS --outSAMtype BAM SortedByCoordinate --alignEndsType EndToEnd --outSAMattributes nM MD NH`

**Comment by TomSmithCGAT** [comment]
I can't see any STAR command there that should remove the query name. Are there other commands in the script after STAR? Assuming there is nothing confidential in there, you can share the whole bash script here

**Comment by TomSmithCGAT** [comment]
Looks like the issue may be pre-STAR.

I've not come across `gedi` before, but it sounds like their pipeline requires the read queries to be integers:
https://github.com/erhard-lab/price/issues/3

I'm not at all proficient in Java, but it from the source code, it appears the `FastqFilter` tool 'reindexes reads', but can also extract UMIs (`-umi`) and append these to the read names. If so, you will need to use `gedi` to perform the UMI extraction in order for the resultant BAMs to be compatible with `umi_tools dedup`
https://github.com/erhard-lab/gedi/blob/cb99bb6622bb14be24dfa229409fd67d74d83657/GediPreprocess/src/executables/FastqFilter.java#L80

I can't find any documentation to confirm this though. Perhaps raise an issue here https://github.com/erhard-lab/gedi and link to this one.

**Comment by MatthiasSchmitz93** [comment]
Thank you very much!
