### ISSUE TITLE
extract.py : problem with Xs bases reattachment to the read

### ISSUE THREAD

**Issue by AlexandraBomane** [CGATOxford/UMI-tools#51]
Hello,

I'm using the latest version of UMI-tools (Master branch) and I noted an unexpected output with the extract.py script.

Here my command line : 
python extract.py --bc-pattern=NNNTTGTNN -L extract.log -I input.fastq -S output.fastq

Here the original read (from the input) : 
@NS500801:5:H7YMFBGXX:1:11101:12845:1158 1:N:0:0
**CAA**TTGT**CG**GCCGCCGGTGAAATACCNNNNNNNNNNNNNGGAAGAGCGGTTCAGCAGGAATGGCGAGACCGATCTCGTAT
+
AAAAAF<F<FFFFFF..FFFFFFFFF#############FF<AFFFFFFFFFFF77.F<F7FAFAFF<FAFAF<AAAA.<

Here the output read : 
@NS500801:5:H7YMFBGXX:1:11101:12845:1158_CAACG 1:N:0:0
GCCGCCGGTGAAATACCNNNNNNNNNNNNNGGAAGAGCGGTTCAGCAGGAATGGCGAGACCGATCTCGTAT
+
FFFFFF..FFFFFFFFF#############FF<AFFFFFFFFFFF77.F<F7FAFAFF<FAFAF<AAAA.<

We can see that the random bases were extracted from the read and add to the ID, but the remaining bases (normally **TTGT**) were not added to the beginning of the read (i.e my pattern were just trimmed from this original read).

Can you explain me why this happened and how I can fix this, please ?

Best regards,
Alexandra

**Comment by IanSudbery** [comment]
Hi,

At the moment we only reattach bases that are labeled in the pattern as X's.

I.e. if your `--bc-pattern` was NNNXXXXNN would the barcode bases be reattached.
