### ISSUE TITLE
What does the "Found xxxxxxx total reads matching the selected cell barcodes" in whitelist logfile mean

### ISSUE THREAD

**Issue by RuiyuRayWang** [CGATOxford/UMI-tools#513]
Hi, thanks for developing this nice tool!

My question is:
In the output of `umi_tools whitelist` logfile, I see this line:
```
Found xxxxx total reads matching the selected cell barcodes
```

What does it mean exactly? What are the selected cell barcodes?

Thanks!
Ray

**Comment by TomSmithCGAT** [comment]
Sorry for the delayed response.

The 'selected' cell barcodes are the barcodes in the whitelist. So this line is stating how many reads have a cell barcode in the whitelist.

**Comment by RuiyuRayWang** [comment]
Thanks for the clarification!
