### ISSUE TITLE
Changing the word "stdin" to "stdout" in the doc

### ISSUE THREAD

**Issue by k3yavi** [CGATOxford/UMI-tools#521]
https://github.com/CGATOxford/UMI-tools/blob/5c2dd0fd208df3a8f93399c99b1d164aef8094be/umi_tools/extract.py#L25

A minor issue with the doc where it mentions that the output of the tool goes to `stdin`, I believe it was meant as `stdout`.

**Comment by TomSmithCGAT** [comment]
Hey Avi! Hope you're doing well.

Thanks for picking this up. Recified: [ea58ec5](https://github.com/CGATOxford/UMI-tools/commit/ea58ec52be05e9d25c2911206e344a70e2f39caf)

**Comment by k3yavi** [comment]
Hey Tom, I am doing great ! I hope you are well too.

Thanks for merging the PR .
