### ISSUE TITLE
Counting issue: failed to map segment from shared object

### ISSUE THREAD

**Issue by CWYuan08** [CGATOxford/UMI-tools#524]
Hi, 

I was trying to run umi_tools count --per-gene --gene-tag=XT -I assigned_sorted.bam -S counts.tsv.gz for my file, 
but I keep getting the  ImportError: miniconda3/envs/squire/lib/python2.7/site-packages/scipy/optimize/_cobyla.so: failed to map segment from shared object

Could you please help me on this? 

Thank you!

Best regards,
CW

**Comment by TomSmithCGAT** [comment]
Hi. It looks like you're using python 2.7. Unfortunately, we no longer support python 2. Could you try updating to python 3 please.

**Comment by CWYuan08** [comment]
Thank you I updated to python 3, but for any umitools command, I keep getting :" Segmentation fault"

Do you know why this is?

Thank you very much!

**Comment by TomSmithCGAT** [comment]
Have you re-installed umi_tools? Are you using a package manager, e.g conda/mamba?
