### ISSUE TITLE
umi-tools extract

### ISSUE THREAD

**Issue by wangjiawen2013** [CGATOxford/UMI-tools#527]
Hi
This is my output of umi-tools extract:
![1649989047](https://user-images.githubusercontent.com/29703450/163508265-de13d7ef-d1dc-47ee-a7fb-4b684dd177a2.png)

The input reads eqaul "regex matches read1", while "Reads output" are less than them and "Filtered cell barcode" is less than "Reads output", could you explain the differecne among "regex matches read1", "Reads output" and "Filtered cell barcode" ?

**Comment by wangjiawen2013** [comment]
umi_tools extract --stdin in.fq --stdout out.fq --extract-method=regex \
 --bc-pattern='^(?P<cell_1>.{8})(?P<cell_2>.{8})(?P<umi_1>.{4}).{40}(?P<umi_2>.{4})(?P<discard_1>.+)' \
 --log2stderr --whitelist=whitelist.txt 2> {log}

My fastq structure:
8bp(barcode1)+8bp(barcode2)+4bp(umi1)+40bp(target sequence)+4bp(umi2)+others

**Comment by TomSmithCGAT** [comment]
Ah, if you need to discard bases after `umi2`, you will need to use a regex after all. Currently the string extraction method doesn't support discarding bases.

Did the above explanations all make sense?

**Comment by wangjiawen2013** [comment]
Yes, thank you!
