### ISSUE TITLE
Cannot solve the '--no-pg' issue

### ISSUE THREAD

**Issue by lkw159159** [CGATOxford/UMI-tools#528]
Dear team,

Hello, 
When I tried to dedup step with example.bam file, I stlll got --no-pg error.

I already read your issue reply and updated pysam, samtools, umi-tools.

BTW, when I checked conda packages list, I saw that there are 2 umi-tools packages in my conda list.

![image](https://user-images.githubusercontent.com/80821527/163926450-03403fd3-dbce-4cd0-98f2-29473c8d25e8.png)

why I have two different versions of UMI=tools? 

If it is the cause, how can I solve it?

Thanks.

**Comment by lkw159159** [comment]
![image](https://user-images.githubusercontent.com/80821527/163949117-5d4b54e6-1213-4047-b259-c4d228294185.png)
Here's my error message

**Comment by TomSmithCGAT** [comment]
Hmmm... looks like you've used both `pip` and `conda` for the installation. From the above, it looks like the pypi version is first on you `$PATH`.

The error is actually due to the version of samtools being used though. What do you get with the following `which samtools` and `samtools --version`.

**Comment by lkw159159** [comment]
Dear Tom,

![image](https://user-images.githubusercontent.com/80821527/163959567-dfd936e9-3f67-4de9-b09d-e69f49298686.png)
I also use samtools with conda environment & it's version is 1.3.1

**Comment by TomSmithCGAT** [comment]
Ah, 1.3.1 is ~ 6 years old. Looks like the --no-PG option was introduced in 1.10 https://github.com/samtools/samtools/releases/tag/1.10

**Comment by lkw159159** [comment]
Oh I see! maybe it is 
I will try it. I appreciate.
