### ISSUE TITLE
umitools extract command ignores provided whitelist file

### ISSUE THREAD

**Issue by Aintzane99** [CGATOxford/UMI-tools#531]
Hello,

I have a problem related to the "extract" command from umi-tools. Previous to the extract step, I generated a whitelist with the option "--set-cell-number=96" and thus the whitelist.txt output file has only 96 accepted barcodes. Then, when I run the extract command providing the whitelist.txt file from the previous step and count the number of cell barcodes found in the R2 extracted file, there are 35288 barcodes instead of 96.  I runned the extract command whithout providing any whitelist file and the number of barcodes in the extracted R2 file is 35288. So, I think the issue is that umi-tools is ignoring the provided whitelist.txt file.  I am running umi-tools on python 3.9.12.

Here is the code that I'm using:

#1. WHITELIST
umi_tools whitelist --stdin ../*78_1.fastq.gz --bc-pattern=CCCCCCCCNNNN --set-cell-number=96 --log2stderr > 78_SAMPLE_4_cols_whitelist.txt

#2. EXTRACT
umi_tools extract --extract-method=string --bc-pattern=CCCCCCCCNNNN --stdin ../../*78_1.fastq.gz --stdout R1_78_SAMPLE_extracted.fastq.gz --read2-in ../../*78_2.fastq.gz --read2-out=R2_78_SAMPLE_extracted.fastq.gz --whitelist=78_SAMPLE_4_cols_whitelist.txt

The extracted R2 file looks like this:

@SRR3472978.1_TGCATNGA_GGGG 1 length=32
TGAGCATGCAGNNNNNNNNNNNNNNNNNNNNN
+
<AAAAFFFFFF#####################
@SRR3472978.2_GAATCNTC_TGGT 2 length=76
CACCTCCCTTTTTTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
+
AAAAAFFFFFFFFF##############################################################
@SRR3472978.3_CGGATNTC_TCTT 3 length=76
GAACTCCATGACGCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

And here is the command I am using to count the number of cell barcodes in the extracted R2 file:
zcat R2_78_SAMPLE_extracted.fastq.gz | grep "^@SRR" | awk -F'_' '{print $2}' | sort | uniq | wc -l

Sincerely, Aintzane

**Comment by IanSudbery** [comment]
Hi Aintzane,

Can you let us know the output of `umi_tools --version`. In older versions of UMI-tools it was neccessary to specify `--filter-cell-barcode`, but this shouldn't be necessary in recent versions. 

Ian

**Comment by IanSudbery** [comment]
Hi Aintzane,

In 1.0.1 you must use the `--filter-cell-barcode` option to enable filtering, so either do that, or update to 1.1.2. 

Ian
