### ISSUE TITLE
Filtering cell barcodes not in the whitelist

### ISSUE THREAD

**Issue by chrarnold** [CGATOxford/UMI-tools#541]
I figured it out now, but the `whitelist` parameter in the `extract` tool and the filtering of cell barcodes not in the whitelist is described and documented in a confusing manner IMHO. Just `whitelist` alone is not sufficient to filter and basically doesnt do anything really without additional arguments. This is not clear from the Docs at all. I found the undocumented parameter `--filter-cell-barcode` from the command line help and provided it and then filtering did work as expected. However, the log file is a bit confusing when providing it in addition, indicating the existence of a `filter_cell_barcodes ` option that doesnt exist actually:

```
# filter_cell_barcode                     : True
# filter_cell_barcodes                    : False
```
I think it would be good to clarify this in the Docs and mention `--filter-cell-barcode` explicitly and add a note for the `whitelist` parameter.

**Comment by IanSudbery** [comment]
This shouldn't be the case, and certainly didn't used to be. Let me see if I can find out what is going on.

**Comment by IanSudbery** [comment]
Hi, Can I just check what version of UMI-tools you are using? Older versions of UMI-tools required the user to specify whether they wished to filter non-whitelisted CBs or error correct them. This is no longer the case (filtering is default, correcting still needs to be specified), and the documentation was updated to reflect this.

**Comment by chrarnold** [comment]
Hi, thanks for the reply! We are using UMI_tools/0.5.4 here, I didnt realize this might be an outdated version issue.

**Comment by chrarnold** [comment]
Ok will do, this was available on our cluster system, good point, I didnt realize it is that old. Is is worth rerunning my pipelines with a newer version, any major bugs that were fixed in between?
The issue can be closed then, thanks a lot!

**Comment by IanSudbery** [comment]
I don't think there have been any major bugs since then, but plenty of minor ones. I realized that 0.5.4 was the last release to support python 2, so that might be something to do with why your system is still using it.
