### ISSUE TITLE
all zero expression genes

### ISSUE THREAD

**Issue by wangjiawen2013** [CGATOxford/UMI-tools#545]
Hi,
The count table is shroter than my gtf gene list sometimes, I doubt that umi-tools will discard genes that don't express in any cells. How to keep the all zero expression genes ? If so, the count table among different experiments can be concatenated easily, especially when there are thoudsands of count tables generated over a long time period.

**Comment by TomSmithCGAT** [comment]
Hi.

`umi_tools count` only has access the the aligned reads in the BAM, not the GTF/GFF, so if no reads are aligned to a gene in any cell, that gene will not be in the count table. 

If you need to merge the counts table from multiple experiments, you can use an outer join. E.g 

- R: `merge(counts_x, counts_y, all=TRUE)`
- python: `pandas.merge(counts_x, counts_y, how='outer')`
