### ISSUE TITLE
--multimapping-detection-method Options documentation 

### ISSUE THREAD

**Issue by gavin-peng** [CGATOxford/UMI-tools#556]
Hi, the documentation states the options are NH/X0/XT, but could you explain which tag represents which option?
I know the options are lowest number of mapping coordinates and highest mapping quality, but which one is which?

**Comment by IanSudbery** [comment]
NH, X0 and XT are all different ways of identifying the number of locations to which a read maps, used by different mappers. If you use any of these three tags, reads will be prioritised on the number of locations a read maps to (lower is better). If you do not set this option, then mapping quality is used.
