### ISSUE TITLE
Does concatenating fastq files cause any issues

### ISSUE THREAD

**Issue by Joseph-Waldron** [CGATOxford/UMI-tools#565]
Hi there

I have just started using this tool and am finding it very useful so thanks very much.

I just wanted to check one thing before I proceed. I have some data where I have sequenced my samples across 3 different runs, which I am then concatenating the fastq files using the following example command

$ cat sample1a.fastq sample1b.fastq sample1c.fastq > sample1.fastq

Will this concatenated fastq file be OK as input into this pipeline, or will there be an issue with the header lines being slightly different depending on which run those reads came from and if so is there a solution to this

Many thanks in advance
Joe

**Comment by TomSmithCGAT** [comment]
No problem with that. It's common to merge samples from e.g muliple lanes of sequencing, in which case the fastq header lines differ with respect to the part indicating the lane the read originiated from. Ultimately, the fastq header line information (machine, lane, flowcell coordinate) is a unique identifier for the read and there's no requirement for any part to be consistently the same in the downstream tools (at least the ones I've used to date).

You also be able to use process substitution, e.g ` umi_tools extract --stdin= <( cat sample1a.fastq sample1b.fastq sample1c.fastq )` to avoid creating the intermediate concatented fastq file.

**Comment by Joseph-Waldron** [comment]
OK that's great and a very useful suggestion. Thanks for getting back to me so soon
