### ISSUE TITLE
Total number of times UMI is observed across all positions increases post UMI deduplication—why?

### ISSUE THREAD

**Issue by kalavattam** [CGATOxford/UMI-tools#573]
I am working through the documentation to learn about the program. Apologies if this question is answered elsewhere and I've missed it: Looking at the results of a `.dedu-adjusted.stats_per_umi.tsv`, I want to ask why it is that, for certain UMIs, the total total number of times that UMI is observed across all positions increases post UMI deduplication? For example, see line 1 (UMI `AAAAAAAA`) and line 4 (UMI `AAAAAAAT`) below:

```txt
> head(metrics_per_umi)
# A tibble: 6 × 7
  UMI      median_counts_pre times_observed_pre total_counts_pre median_counts_post times_observed_post total_counts_post
  <chr>                <dbl>              <dbl>            <dbl>              <dbl>               <dbl>             <dbl>
1 AAAAAAAA                 1                884             1537                  1                 845              6166
2 AAAAAAAC                 1                362              446                  1                 352               426
3 AAAAAAAG                 1                348              388                  1                 337               385
4 AAAAAAAT                 1                488              542                  1                 483               548
5 AAAAAACA                 1                388              531                  1                 377               461
6 AAAAAACC                 1                276              337                  1                 267               319
```

If the question is addressed elsewhere, do you mind pointing me in the right direction?

Thank you,
Kris

**Comment by kalavattam** [comment]
And apologies if this is not the proper forum to ask this question—again, please point me in the right direction. Thanks.

**Comment by IanSudbery** [comment]
Hi Kris,

The reason that  you sometimes see more reads in the counts_post than the counts_pre is that the UMI associated with other UMIs can be corrected to that UMI. 

So, but examples if at one location I have:

```
UMI     count
AAAAA    10
AAAAT    1
```

The reads with the UMI `AAAAT` will have their UMI corrected to `AAAAA`, so the post count for `AAAAA` will be 11. All these reads will then be collapsed onto a single read, so only one deduplicated read for all 11 unduplicated reads will be output.

**Comment by kalavattam** [comment]
I understand, thank you. Closing the issue now.
