### ISSUE TITLE
umi added to readname with bcl2fastq, can I still use umi-tools dedup?

### ISSUE THREAD

**Issue by mattgeorge28** [CGATOxford/UMI-tools#58]
Hello,
My UMIs were added to read names using bcl2fastq and aligned with STAR. Therefore, each read has the UMI added to the end of the read name by ":NNNNNNNNNN" instead of "_NNNNNNNNNN". Is there a way to use umi-tools with this configuration?  
Thank you!
Best,
Matt

**Comment by TomSmithCGAT** [comment]
@mattgeorge28. It should be very easy to add this functionality to UMI-tools. I'll try and get this done this week.

**Comment by TomSmithCGAT** [comment]
@mattgeorge28 I've added a "--umi-separator" option on the separator_option branch. I'd like to keep this option out of the master branch until we're happy it's working as expected. I've done a quick test here and it all seems to be OK. 

Are you happy installing umi_tools from the separator_option branch and testing this option out with your BAM?

**Comment by mattgeorge28** [comment]
Thank you very much! I am working with it right now to see how things go.

**Comment by TomSmithCGAT** [comment]
@mattgeorge28 Did the new _--umi-separator_ option work as expected?

**Comment by mattgeorge28** [comment]
Hello!
Thank you very much for your assistance. I have been running UMI-tools with
the --umi-separator=":" option and it has worked without error. However, I
have tried a few configurations, and I am getting a very large reduction
(80-90%) in deduped reads that I don't see when just running deduplication
with the STAR alignment package (without UMI). I would assume that using
the UMI would retain more reads than just looking at read location and
CIGAR, but I am still trying to understand this. These reads are all on
eCLIP data (cross linked and IP'd RNA bound to a protein), so the umi-tools
result could very well be more correct. I'll check back soon when I have
compared the results more thoroughly.
Best,
Matt

**Comment by mattgeorge28** [comment]
Just to check, if my readname was this:

NB501415:61:HLFTYBGXY:4:23409:16637:11038:AAGATTCCGT


Am I correct in assuming    --umi-separator=":"       would read in from
the right until it hits the first ":" to identify the UMI?


In looking closer, it seems that my data do have a LOT of PCR duplicates.
So the massive reduction in reads after umi-tools dedup is likely correct.


Thanks again,

Matt

**Comment by TomSmithCGAT** [comment]
@mattgeorge28  You're right about how the `--umi-separator` option works. You can leave out the quotation marks, e.g just  `--umi-separator=:` but it works fine with quotation marks too.

I've not used STAR for reduplication but, as you say, I'd be very surprised if it underestimates the true duplication rate when it's not taking UMIs into account. Could you please copy in the exact command you used.

Also, would you be able to run Picard MarkDuplicates on the same BAM and see what duplication rate it reports as this should be the maximum possible duplication rate you could get using umi_tools.

**Comment by TomSmithCGAT** [comment]
@mattgeorge28  You're right about how the `--umi-separator` option works. You can leave out the quotation marks, e.g just  `--umi-separator=:` but it works fine with quotation marks too.

I've not used STAR for reduplication but, as you say, I'd be very surprised if it underestimates the true duplication rate when it's not taking UMIs into account. Could you please copy in the exact command you used.

Also, would you be able to run Picard MarkDuplicates on the same BAM and see what duplication rate it reports as this should be the maximum possible duplication rate you could get using umi_tools.

**Comment by IanSudbery** [comment]
Those sorts of duplication rates would be completely normal from my
experience of iCLIP.

**Comment by TomSmithCGAT** [comment]
@IanSudbery. Agreed the duplication rates would be OK for iCLIP. However, eCLIP uses much less amplification and should reduce duplication rates: [eCLIP](http://www.nature.com/nmeth/journal/v13/n6/full/nmeth.3810.html).

**Comment by IanSudbery** [comment]
Thats nit been my experience of reanalysing eCLIP datasets.

Sent from my iPad

On 1 Dec 2016, at 08:15, Tom Smith <notifications@github.com> wrote:

@IanSudbery <https://github.com/IanSudbery>. Agreed the duplication rates
would be OK for iCLIP. However, eCLIP uses much less amplification and
should reduce duplication rates: eCLIP
<http://www.nature.com/nmeth/journal/v13/n6/full/nmeth.3810.html>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CGATOxford/UMI-tools/issues/58#issuecomment-264106327>,
or mute the thread

**Comment by TomSmithCGAT** [comment]
Ah OK. Let's work on the assumption that a 90% duplication rate could be correct then and check that the UMIs are reducing the apparent duplication rate as expected.

**Comment by TomSmithCGAT** [comment]
@mattgeorge28 Did you compare the duplication rate from Picard MarkDuplicates and UMI-Tools?

**Comment by mattgeorge28** [comment]
Hi Tom,
Sorry for no reply. I've been having some issues with our server and my
data recently. Will let you know as soon as I know. However, after looking
at the results from UMI-tools, I doubt Picard could possibly detect more
true positives.
Matt

**Comment by TomSmithCGAT** [comment]
Hi @mattgeorge28. I'm going to assume it's OK to close this issue now? Feel free to reopen it if you need to continue the discussion.
