### ISSUE TITLE
speedup with pigz

### ISSUE THREAD

**Issue by wangjiawen2013** [CGATOxford/UMI-tools#590]
UMI-tools is a litte slowly. TrimGalore uses pigz (parallel gzip) to speedup (https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/Trim_Galore_User_Guide.md). Could UMI-tools adopt that strategy ?

**Comment by TomSmithCGAT** [comment]
It's a good idea. And one we have considered before a while back (https://github.com/CGATOxford/UMI-tools/pull/162#issuecomment-323286938). Our issue previously was how to handle multiple output files. 

If there's a well-supported python library for writing with `pigz`, that would be great. I've seen https://github.com/nix7drummer88/pigz-python, but that hasn't had a closed issue or code update for 2 years, so I suspect it's not being supported.

**Comment by IanSudbery** [comment]
I'm assuming you are reffering to `extract` being slow. 

I believe you can emulate the advatages of pigz (to an extent) by writing uncompressed output from `extract` and piping it to the pigz binary.
