### ISSUE TITLE
umi_tools not working

### ISSUE THREAD

**Issue by gevro** [CGATOxford/UMI-tools#594]
Hi, I tried installing with pip and also from the ZIP release.
Both give me this error:

$ umi_tools dedup
'dedup' is not a UMI-tools command. See 'umi_tools -h'.

Also, the help is not showing:
$ umi_tools dedup --help
UMI-Tools: Version 1.1.4

Note: this is happening for every tool command.

I think something is broken in the current version.

**Comment by TomSmithCGAT** [comment]
OK, the error (`'dedup' is not a UMI-tools command. See 'umi_tools -h'`) is odd and I cannot reproduce. E.g the following setup works fine after downloading ZIP release

```
conda create -n umi_tools_sandbox python=3.10
conda activate umi_tools_sandbox
pip install ~/Downloads/UMI-tools-1.1.4.zip
umi_tools dedup
```

The issue with the help text has been caught and is waiting on #586. Sorry about that one. For now, you'll need to refer to the [online documentation](https://umi-tools.readthedocs.io/en/latest/).

**Comment by gevro** [comment]
Ok thanks. I managed to run umi_tools find on a different computing cluster. Not sure how the other error is happening.
