### ISSUE TITLE
Extra UMI present only in R1 of read pair?

### ISSUE THREAD

**Issue by kmshort** [CGATOxford/UMI-tools#595]
Hi all
I have read pairs which have a 6b UMI only on R1. Is there a way to put in a read pair and have it only work on R1?
If I treat R1 as a single ended read, the names between R1 and R2 pairs will no longer match and I assume all sorts of fun problems will ensue down the line.
Is there a switch where I can just "magic" it away?
Or should I just duplicate the UMI onto the R2 and then do umi_tools extract ?
regards

**Comment by IanSudbery** [comment]
The UMI being present only in read 1 is the standard situation. If you specify the position of the UMI in read 1, and then feed both reads to `extract`, then the UMI will extracted from read1 and added to the read name of both read 1 and read 2. 

e.g.

```
$ umi_tools extract --stdin=read1.fastq.gz --stdout=read1.processed.fastq.gz --read2-in=read2.fastq.gz --read2-out=read2.processed.fastq.gz --bc-pattern=NNNNNN -L log.log
```

will take the first 6nt of read1 and add it to the name of both read1 and read2, ensuring that both reads in the pair have the same name.
