### ISSUE TITLE
Question about Obtaining Barcode Pattern from Sequencing Data

### ISSUE THREAD

**Issue by cheng-xiaoxiaoo** [CGATOxford/UMI-tools#597]
As a newcomer to this field,  I would like to inquire whether it is feasible to extract the barcode pattern information from the FASTQ files themselves or it is essential to consult the documentation or metadata associated with the sequencing files to obtain the barcode pattern information.
Thank you for your attention to this matter, and I eagerly look forward to any insights or recommendations you can provide.

**Comment by IanSudbery** [comment]
While one can imagine a tool that would extract the barcode pattern information from a FASTQ file, I've never heard of a tool that actaully does this, certainly umi-tools doesn't. It would be much better to get this data from the knowledge of the experiment, either from the metadata, the standards for the protocol that generated the data, or from the person who did the experiment.

**Comment by cheng-xiaoxiaoo** [comment]
Thank you very much.
