### ISSUE TITLE
prepare-for-rsem no longer works

### ISSUE THREAD

**Issue by anoronh4** [CGATOxford/UMI-tools#607]
seems as though the `prepare-for-rsem` tool no longer works, as of version 1.1.3. has it been deprecated or replaced by something else? if the latter, can you elaborate on the new usage to achieve the same output?

**Comment by IanSudbery** [comment]
It should work,  it's not been deprecated.  Let me investigate.

**Comment by TomSmithCGAT** [comment]
This should be solved now. See #609
