### ISSUE TITLE
Is newer version of UMI-tools compatible with dedup_umi.py in this repo?

### ISSUE THREAD

**Issue by kvn95ss** [CGATOxford/UMI-tools#622]
Hello,

I'm trying to run the scripts in this repository - https://github.com/eyay/smallseq

The repo includes two scripts from UMI-tools, however they belong to an unknown, older version of the software, and there is no mention of the version number in the protocol paper nor in the scripts themselves. 

On glance, the newer dedup_umi.py does look different (at least to my python naive eyes) and do not rely on CGAT scripts (required for the UMI-tools script from the other repository).

I was wondering if I can just use the latest version of UMI-tools in place of the older scripts, or if the outputs might differ due to version changes.

Thanks!

**Comment by IanSudbery** [comment]
Wowzers, that is old! Like, before we did our first release old (hence no version number). I think the algorithmn at the heart should be the same. There will, enviatably, have been tweaks over the years that might mean that the results are not identical, but in generally, they should be approximately the same.

**Comment by kvn95ss** [comment]
Thanks! I guess I’ll use the latest version then.
