### ISSUE TITLE
umi_tools extract: UMI on 5' read 1 and 3' read 2

### ISSUE THREAD

**Issue by lzt5269** [CGATOxford/UMI-tools#623]
Hi,

I'm working on paired-end data. Read 1 has 10 UMI at the beginning and read 2 has 10 UMI which is reverse complement to UMI on read 1 at the end. How should I extract UMI and remove them from both reads?

Thanks.

**Comment by TomSmithCGAT** [comment]
@lzt5269 - Did the above work?
