### ISSUE TITLE
UMI_tools whitelist function not taking set-cell-number into account

### ISSUE THREAD

**Issue by Victoria-01** [CGATOxford/UMI-tools#636]
Good morning, 

I am trying to create a whitelist for my scRNA seq data. The threshold obtained from the kneeplot is way lower then what it should be (considering the visual appearance of the kneeplot and the fact that the data has 100 M reads): only 146 real cell barcodes are detected.
I would like to set the threshold manually but the set-cell-number option does not seem to be working (when I compare the whitelist obtained after not using set-cell-number and after unsing set-cell-number = 10 000, they are the same). Would you have an idea why and what I could do to solve it?

Here is my command and the result I get: 

umi_tools whitelist --bc-pattern=CCCCCCCCCCGAGTGATTGCTTGTGACGCCTTCCCCCCCCNNNNNN --extract-method=string --subset-reads=1000000 --error-correct-threshold=2 -I /home/18032024/SRR_big/test/SRR19360476_2.fastq -S whitelist.txt -- set-cell-number=10000 --methods=umis --ed-above-threshold=correct
# UMI-tools version: 1.0.1
# output generated by whitelist --bc-pattern=CCCCCCCCCCGAGTGATTGCTTGTGACGCCTTCCCCCCCCNNNNNN --extract-method=string --subset-reads=1000000 --error-correct-threshold=2 -I /home/18032024/SRR_big/test/SRR19360476_2.fastq -S whitelist.txt -- set-cell-number=1000 --methods=umis --ed-above-threshold=correct
# job started at Thu Mar 21 11:21:35 2024 on lbc-bigbi -- 81188b43-b3c8-488f-b306-260c5c5deef6
# pid: 100405, system: Linux 5.4.0-173-generic #191-Ubuntu SMP Fri Feb 2 13:55:07 UTC 2024 x86_64
# allow_threshold_error                   : False
# blacklist_tsv                           : None
# cell_number                             : False
# compresslevel                           : 6
# ed_above_threshold                      : None
# error_correct_threshold                 : 2
# expect_cells                            : False
# extract_method                          : string
# filter_cell_barcodes                    : False
# knee_method                             : distance
# log2stderr                              : False
# loglevel                                : 1
# method                                  : reads
# pattern                                 : CCCCCCCCCCGAGTGATTGCTTGTGACGCCTTCCCCCCCCNNNNNN
# pattern2                                : None
# plot_prefix                             : None
# prime3                                  : None
# random_seed                             : None
# read2_in                                : None
# short_help                              : None
# stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
# stdin                                   : <_io.TextIOWrapper name='/home/18032024/SRR_big/test/SRR19360476_2.fastq' mode='r' encoding='UTF-8'>
# stdlog                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
# stdout                                  : <_io.TextIOWrapper name='whitelist.txt' mode='w' encoding='UTF-8'>
# subset_reads                            : 1000000
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# tmpdir                                  : None
# whitelist_tsv                           : None
2024-03-21 11:21:35,140 INFO Starting barcode extraction
2024-03-21 11:21:35,140 INFO Parsed 0 reads
2024-03-21 11:21:35,781 INFO Parsed 100000 reads
2024-03-21 11:21:36,423 INFO Parsed 200000 reads
2024-03-21 11:21:37,065 INFO Parsed 300000 reads
2024-03-21 11:21:37,710 INFO Parsed 400000 reads
2024-03-21 11:21:38,359 INFO Parsed 500000 reads
2024-03-21 11:21:39,003 INFO Parsed 600000 reads
2024-03-21 11:21:39,649 INFO Parsed 700000 reads
2024-03-21 11:21:40,299 INFO Parsed 800000 reads
2024-03-21 11:21:40,949 INFO Parsed 900000 reads
2024-03-21 11:21:41,597 INFO Parsed 1000000 reads
2024-03-21 11:21:41,597 INFO Starting - whitelist determination
2024-03-21 11:21:41,885 INFO Finished - whitelist determination
2024-03-21 11:21:41,886 INFO Starting - finding putative error cell barcodes
2024-03-21 11:21:47,201 INFO Finished - finding putative error cell barcodes
2024-03-21 11:21:47,201 INFO Top 146 cell barcodes passed the selected threshold
2024-03-21 11:21:47,201 INFO Writing out whitelist
2024-03-21 11:21:47,206 INFO Parsed 1000001 reads
2024-03-21 11:21:47,206 INFO 1000001 reads matched the barcode pattern
2024-03-21 11:21:47,206 INFO Found 269489 unique cell barcodes
2024-03-21 11:21:47,206 INFO Found 125622 total reads matching the selected cell barcodes
2024-03-21 11:21:47,206 INFO Found 21504 total reads which can be error corrected to the selected cell barcodes
# job finished in 12 seconds at Thu Mar 21 11:21:47 2024 -- 12.66  0.13  0.00  0.00 -- 81188b43-b3c8-488f-b306-260c5c5deef6

Thank you in advance!

**Comment by Victoria-01** [comment]
Here it is!
![SRR_cell_barcode_counts](https://github.com/CGATOxford/UMI-tools/assets/164336556/057d5b7d-92a8-41f6-9b1b-e1c14867b88c)

**Comment by Victoria-01** [comment]
I have tried various set-cell-number values to see, none of them works.

**Comment by Victoria-01** [comment]
My bad, I finally found the answer: I put a space between -- and set-cell-number.

**Comment by TomSmithCGAT** [comment]
Ah, yes, hadn't spotted that. The knee plot also looks quite 'flat'. It might help to increase to `--subset-reads=10000000` just in case that's partly due to under-sampling

**Comment by Victoria-01** [comment]
Ok, thanks for the advice!
