### ISSUE TITLE
samtools error in umi-tools dedup

### ISSUE THREAD

**Issue by rfreeman7** [CGATOxford/UMI-tools#638]
Hello! 

I have been having an issue running umi_tools dedup. I'm using umi-tools version 1.1.0.

I aligned my paired-end reads using STAR, converted the sam files to bam, sorted and indexed and then tried to run deduplication using the following code: 

umi_tools dedup -I LepKODP123_map.bam --paired -S deduplicated_LepKODP123_map.bam --chimeric-pairs=discard --unpaired-reads=discard

I added the chimeric-pairs and unpaired-reads arguments due to suggestions in the error messages I received from the program. Now however, I'm getting samtools errors (see attached). 
I updated my python to 3.10.13 from 3.6.10, but this did not resolve the issue. Do you have any thoughts on what could be causing this error?

Thank you!
[umi-tools_deduperror.pdf](https://github.com/CGATOxford/UMI-tools/files/14887090/umi-tools_deduperror.pdf)

**Comment by IanSudbery** [comment]
This is caused by having a (very) old version of samtools installed. If you
were to force the installation of more recent version of UMI-tools (1.1.0
is now over 4 years old), that would fix this. Otherwise, trying bumping
the version of pysam to above 0.16 or samtools to 1.1.

**Comment by TomSmithCGAT** [comment]
@rfreeman7 - Has this issue been resolved?
