### ISSUE TITLE
Filter for low read-depth UMIs?

### ISSUE THREAD

**Issue by gdlampe** [CGATOxford/UMI-tools#649]
Hi! 

I'm trying to filter for UMI<>alignment events that may be artifactual due to PCR template switching during sample prep. Currently, i filter alignments that only have 1 read at the specific site, but after UMI deduplication I cannot really do that (since one UMI does not mean one read). is there any way to do that either during the "dedup" command, or by pulling some metadata when looking at the deduplicated BAM file?

**Comment by IanSudbery** [comment]
No, there currently isn't any way to do this. However, if you use `group` rather than `dedup` you'll get a file with the meta data you would need to do this, and in addition, you could probably use the BX tag in the resulting BAM file to do this from the output.
