### ISSUE TITLE
Output of `umi_tools extract` not compatible with `umi_tools count_tab`

### ISSUE THREAD

**Issue by eachanjohnson** [CGATOxford/UMI-tools#651]
The command `umi_tools extract` results in read names being suffixed with the pattern `_[cell barcode]_[UMI]`. See [the docs here for an example](https://umi-tools.readthedocs.io/en/latest/regex.html#example-extracting-barcodes-and-umis).

However, `umi_tools count_tab` expects read names suffixed with the pattern `_[UMI]_[cell barcode]`.  See [the docs here](https://umi-tools.readthedocs.io/en/latest/reference/count_tab.html#purpose).

As a result, pipelines naively expecting to use the output of `umi_tools extract` for `umi_tools count_tab` (after e.g. a `cut | sort` manipulation) will have incorrect output. 

This does not seem to be simply a documentation error. On [this line](https://github.com/CGATOxford/UMI-tools/blob/10c6495ab4411d05a4c3139603507f79294417b7/umi_tools/count_tab.py#L136), `umi_tools count_tab` counts the barcodes using `sam_methods.get_gene_count_tab()`, which by default uses the `sam_methods.get_cell_umi_read_string()` function, [returning the tuple](https://github.com/CGATOxford/UMI-tools/blob/10c6495ab4411d05a4c3139603507f79294417b7/umi_tools/sam_methods.py#L100) `(read_id.split(sep)[-1].encode('utf-8'), read_id.split(sep)[-2].encode('utf-8'))`. For the output read names from `extract`, this corresponds to `(UMI, cell barcode)`. But then this output is unpacked [here](https://github.com/CGATOxford/UMI-tools/blob/10c6495ab4411d05a4c3139603507f79294417b7/umi_tools/sam_methods.py#L557) as `cell, umi = bc_getter(read_id)`. So the cell barcode and UMI are swapped around.

Apologies if I've missed a step, and this behaviour is intended. I thought I should point it out to save others some trouble in future.

**Comment by IanSudbery** [comment]
Thanks for this, it does indeed seem that you are correct. @TomSmithCGAT - any thoughts? Did we swtich the order at somepoint and forget to propogate through to `count_tab`?

**Comment by IanSudbery** [comment]
Since #654 has been merged, can we close this issue?
