### ISSUE TITLE
umi tools 1.1.5 not available on pypi

### ISSUE THREAD

**Issue by johandahlberg** [CGATOxford/UMI-tools#652]
**Describe the bug**

It seems umi tools 1.1.5 is not available on pypi, only in conda. It would be useful to be able to install the same versions from pypi as from conda.

See:
 - https://pypi.org/project/umi-tools/#history
 - https://anaconda.org/bioconda/umi_tools/files

**To Reproduce**

```pip install umi_tools==1.1.5```

**Expected behavior**

1.1.5 is installable from pypi.

**Comment by TomSmithCGAT** [comment]
Apologies for the delay putting 1.1.5 on pypi. Now rectified.

**Comment by johandahlberg** [comment]
Thank you for fixing it!
