### ISSUE TITLE
UMI tools with paired end

### ISSUE THREAD

**Issue by LioLenr** [CGATOxford/UMI-tools#653]
Hello,

BD Rhapsody enhanced 3' beads is a paired-end technique for which only R1 contains the barcode. I would like to know if it's ok to create a whitelist of barcode with umi_tools whitelist using only R1 and then extract the barcode with umi_tools extract specifiying R1 and R2 or should mention R2 when creating the whitelist ?

Thanks 

Lionel

**Comment by IanSudbery** [comment]
There is no need to give whitelist the R2.
