### ISSUE TITLE
AssertionError: not all umis are the same length(!):  48 - 49 

### ISSUE THREAD

**Issue by ChrisSteel-bio** [CGATOxford/UMI-tools#659]
Hello all,

I'm can't seem to get umi_tools dedup to run. Despite what I understand to be the correct command configuration, I think the tool is recognizing the full read name as the umi. If anyone could shed some light on this It would be much appreciated 

My command:
         umi_tools dedup --stdin={input.bam} --log={log} 
        --umi-separator=":" --paired > {output.dedup_bam}  

Few lines from my bam file: 
```
LH00417:58:2237YTLT1:1:1258:15701:25386:TTTTAAACG       81      chr1    9998    0       53S98M  chr5    10850   0       CGTGAATGTGGTTAGAATTTTGACTGTGGCTGGGGTGAGGGCTTGGGCTCTGACGA
TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC --99----99-99-9--99--9I--9-9--9-------99-I---9-I9II-II--II-IIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII NM:i:0  MD:Z:98 MC:Z:95M56S     AS:i:98 XS:i:95 RG:Z:BLLW_PDX_hg38                                      
LH00417:58:2237YTLT1:1:1243:17319:20916:GACTTGACA       177     chr1    10000   0       68S83M  =       167845557       167835577       TCATGGCACGGGTAATAGTCGGGGCACTGATTTGAACACG
GATGTGAATAAGAATACGGACATGAATCATAACCCTAAAACTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC --99---99999-I9--99-9I-99I--999----9---9--------99--99-9---9----
-------I-99III---IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII NM:i:2  MD:Z:10C0C71    MC:Z:49S102M    AS:i:73 XS:i:72 RG:Z:BLLW_PDX_hg38              
LH00417:58:2237YTLT1:1:2106:42367:24681:GTCGAAACA       97      chr1    10086   0       61M90S  chr18   10485   0       AACCCTAACCATAACCCTAACCCAACCCTAACCCTAAACCTAACCCTAAACCTAAC
CCTAAACATAACCATAACCTAAACCTAACCCAAAATCCAAAAACAAGCCCCACACCAAAACAAAAAAAAAACCAAAAACCAAAACATGAACGAAA II9IIIIIII-IIIIIIIII9IIIIIIIIIIIII9I---I9I-II-III9-9III-III9I-9-9I----I----999-9
-99---I-9-----99---999---9-9--9-9-9--9999---999-9---------9-----99--9-- NM:i:3  MD:Z:10C26C11C11        MC:Z:107S39M5S  AS:i:46 XS:i:46 RG:Z:BLLW_PDX_hg38                      
```

**Comment by IanSudbery** [comment]
The error message would to be me suggest that the whole read name is being taken as the UMI, which suggests that ':' is not being used as the separator. You can check this in the log file.

Just to check - the command in your post has a new line in it, meaning that the important `--umi-separator` is not on the same line as the call to dedup. Is that just how you have pasted it here, or is that how it is in your script/pipeline?

**Comment by ChrisSteel-bio** [comment]
Silly mistake on my part, the command is part of a snakemake pipeline and I was indeed missing some quotes needed to specify a new line. Thank you!
