### ISSUE TITLE
Output order is not consistent between py2 and py3

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/UMI-tools#66]
The output from the group and dedup commands is inconsistent between py2 and py3. I thought this was due to the python dictionary hash in py3 - quoting from the documentation '[hash] values of str, bytes and datetime are “salted” with an unpredictable random value. Although they remain constant within an individual Python process, they are not predictable between repeated invocations of Python . Hash randomization is intended to provide protection against a denial-of-service'. However, setting the environmental variable PYTHONHASHSEED=0 for both py2 and py3 so they both use the same hash for the dictionaries doesn't ensure consistency between them.

I'm not sure what the difference is between py2 and py3 which is causing this?

See the Py3.5-testing branch for code which is fulling Py3.5 compatible.

**Comment by Acribbs** [comment]
Hi Tom, I had issues with python 3 tests passing because of setting the seed. You correct that there is currently no way of setting the seed so the output remains the same following repeated invocations of python. The fix that was used for our problem was to use sorted for the output of the dict.

**Comment by TomSmithCGAT** [comment]
@Acribbs. Thanks for your input. I can get the same output order for py3 with repeated invocations by setting the environmental variable `PYTHONHASHSEED=0`. The issue is that I can't get the same output order for py2 **and** py3. I've tried ordering the dictionary keys using `sorted()` but I still get different output for py2 & 3. Think it might be time to call it quits and come back another day with a fresh head!

**Comment by Acribbs** [comment]
Ah ok, when I tested I had to write two tests, one for py2 and one for py3. In the test.yam l file I used:
downsample_paired_py2:
    skip_python: 3
    stdin: paired.bam
    outputs: [stdout]
    references: [downsample_paired.bam]
    options: --method=downsample-paired --downsample=3000 --random-seed=1 -L out.log

downsample_paired_py3:
    skip_python: 2
    stdin: paired.bam
    outputs: [stdout]
    references: [downsample_paired_py3.bam]
    options: --method=downsample-paired --downsample=3000 --random-seed=1 -L out.log

Dont know if this helps?

**Comment by TomSmithCGAT** [comment]
That might very well help. How does the skip_python directive work? Does it just detect the python version and skip tests these tests? If so, this would work perfectly, aside from doubling the number of test files for comparison of course

**Comment by Acribbs** [comment]
Thats how I understand its working. Yes I know, but it worked for me.

**Comment by TomSmithCGAT** [comment]
Great. I'll give this a try

**Comment by TomSmithCGAT** [comment]
Ok so this works to get tests passing on py2.7 and py3.5 . The issue now is that the tests fail for 3.4 (bioconda asks for 3.4 & 3.5) when the py3 reference files are generated using 3.4. 

@IanSudbery For the time being are you happy if we just run tests for py2.7 and py3.5 and I'll hunt down the difference between 3.4 and 3.5 later?

**Comment by IanSudbery** [comment]
Fine by me
