### ISSUE TITLE
--per-cell behavior with multiple read_id barcodes

### ISSUE THREAD

**Issue by peterpdu** [CGATOxford/UMI-tools#666]
Hi,

Thanks for developing this suite of tools! I am using umi-tools for a custom application where multiple barcodes are attached to the read name. My understanding is that the last field of the read name is considered the UMI used for deduplication. If I run `dedup` with `--per-cell`, will the first field or second field (or both) be considered the cell barcode?

```
LH00416:189:22NCMJLT3:5:1101:2304:1016_CTCGTCAAGGAATTAC_GTAACGTGCTTT_GAGCTGACTT
```

**Comment by IanSudbery** [comment]
The cell barcode will be the second to last field will be the cell barcode,
so in this case GTAACGTGCTTT.
