### ISSUE TITLE
Cell Barcode

### ISSUE THREAD

**Issue by inakicm** [CGATOxford/UMI-tools#68]
Hi,

I miss an important point, sorry for that ...
Does one BAM file have all the reads for only one Cell Barcode?
Otherwise, where do you put the cell barcode information in the BAM file?

Thanks a lot,
Iñaki

**Comment by IanSudbery** [comment]
The way we have used it in the past is to have a seperate BAM for each cell barcode.

An alternative would be to combine the cell barcode and UMI into one sequence, dedup on that, and then separate out the cell barcode again.

**Comment by inakicm** [comment]
Good idea to combine the cell barcode and the UMI, thank you for pointing that out.
