### ISSUE TITLE
Bad value in flatfile describing the read groups

### ISSUE THREAD

**Issue by Poshi** [CGATOxford/UMI-tools#72]
In a test run with real data, I've got things like:
```
M01660:68:000000000-AMT35:1:1107:14665:23414_TTTTATGTGGTA	chr1	11291633	TTTTATGTGGTA	3	TTTTATGTGGTA	4	231
M01660:68:000000000-AMT35:1:1111:17174:11107_TTTTATGTGGTA	chr1	11291633	TTTTATGTGGTA	3	TTTTATGTGGTA	4	231
M01660:68:000000000-AMT35:1:1119:12490:6844_TTTTATGTGGTA	chr1	11291633	TTTTATGTGGTA	3	TTTTATGTGGTA	4	231
M01660:68:000000000-AMT35:1:2109:18893:17840_TTTTATTTGGTA	chr1	11291633	TTTTATTTGGTA	3	TTTTATGTGGTA	4	231
```
If I don't interpret the data incorrectly (I'm new to this tool), the last line should say that there is 1 UMI that has been joined to the group 231 of 4 equal UMIs in total. But instead of a "1", I see a "3". That's incorrect, right?

**Comment by TomSmithCGAT** [comment]
@Poshi The output is indeed incorrect, though not in the way you describe. Reading from the relevant section of the documentation (copied below), column 5 should contain the count for the UMI on the read and column 7 should contain the total count for the group. Thus, the final line about should be: 

```
M01660:68:000000000-AMT35:1:2109:18893:17840_TTTTATTTGGTA	chr1	11291633	TTTTATTTGGTA	1	TTTTATGTGGTA	4	231
```

I'll update the code to correct this at the same time as adding the subset command #74 

--- Documentation ---

To generate the flatfile describing the read groups, include the
--group-out=<filename> option. The columns of the read groups file are
below. The first five columns relate to the read. The final 3 columns
relate to the group.
  - read_id
    read identifier
  - contig
    alignment contig
  - position
    Alignment position. Note that this position is not the start
    position of the read in the BAM file but the start of the read
    taking into account the read strand and cigar
  - umi
    The read UMI
  - umi_count
    The number of times this UMI is observed for reads at the same
    position
  - final_umi
    The inferred true UMI for the group
  - final_umi_count
    The total number of reads within the group
  - unique_id
    The unique id for the group

**Comment by Poshi** [comment]
Maybe I expressed myself incorrectly, but I was refering just to what you said :+1:

**Comment by TomSmithCGAT** [comment]
Ah, great. Well spotted! I've made all the required changes so I just need to wait for tests to pass then I can release a new version. Should be done within the next hour.

**Comment by TomSmithCGAT** [comment]
This has now been resolved in the latest version 0.3.6 which is available through github, pypi and conda.

**Comment by Poshi** [comment]
Wow! That was fast!
In the meantime I managed to clone the code and install it locally with develop command, so I should be able to easily try new code and add mine.
Thanks!

**Comment by TomSmithCGAT** [comment]
Great. Let me know how you get on.
