### ISSUE TITLE
Read UMI from tag

### ISSUE THREAD

**Issue by Poshi** [CGATOxford/UMI-tools#73]
In this tool, you are assuming that the UMI will be found in the ID, but there can be cases where the UMI is in other places. In our case, the UMI is located in a tag. Specifically in the RX tag (but others use the BC/BX).
Also, when assigning the UMI, the tags are competing (you use FU, Picard uses MI).

* It would be nice to be able to specify the tags to be used for all of these operations.
* And it would be nice to be able to read the UMI from the given tag, not only from the ReadID.

**Comment by IanSudbery** [comment]
Hi,

Reading using UMIs specified in different locations is on our to do list for the next release. 

Ian
