### ISSUE TITLE
--subset option not recognized

### ISSUE THREAD

**Issue by Poshi** [CGATOxford/UMI-tools#74]
By running:
```
$ umi_tools group -I in.bam -L out.log -S out.bam --output-bam --paired --group-out=out.group --subset
```
I get The usage instructions and an error in the last line:
```group: error: no such option: --subset```
But the own help text claims that this is a valid option:
```
--subset
      Only consider a fraction of the reads, chosen at random. This is useful
      for doing saturation analyses.
```

**Comment by IanSudbery** [comment]
Hi Jordi, 

Looks like someone copied accross the documentation from dedup when group was implemented, but didn't actaully implement subset.

@TomSmithCGAT Any reason why subset isn't implemented in `group`?

**Comment by TomSmithCGAT** [comment]
@IanSudbery Nope. I'll do this now. 

@Poshi How are you installing UMI_tools (Github, conda, pip) ?

**Comment by Poshi** [comment]
Asking my sysadmins. No idea what they had done. I can ask if you really need the answer.

**Comment by TomSmithCGAT** [comment]
@Poshi. I only ask because I can make the changes directly in Github and make it available immediately. Pip and Conda will take very slightly longer.

**Comment by Poshi** [comment]
@TomSmithCGAT I will try to install it in my user space from github, but I think I will have to fight some library problems :-(

**Comment by TomSmithCGAT** [comment]
This has now been resolved in the latest version 0.3.6 which is available through github, pypi and conda.

**Comment by TomSmithCGAT** [comment]
@Poshi Can I just confirm this is working in your hands now?

**Comment by Poshi** [comment]
Sure!
It works now, but the behavior is not clear. --subset has a parameter, a fraction. I understand that this should be a value in (0..1). I tried with 0.1 and got what I expected, 90% discarded:
```
2017-02-03 11:32:50,707 INFO Reads: Input Reads: 957741, Paired Reads: 957741, Randomly excluded: 861674, Read 2 unmapped: 6076, Read 1 unmapped: 5586
2017-02-03 11:32:50,707 INFO Number of reads out: 84405, Number of groups: 22339
```
But then I tried with 10, like trying to say 10%. Nothing got discarded, and no error message was issued about the parameter being out of range:
```
2017-02-03 11:41:31,958 INFO Reads: Input Reads: 957741, Paired Reads: 957741, Read 2 unmapped: 60921, Read 1 unmapped: 55142
2017-02-03 11:41:31,958 INFO Number of reads out: 841678, Number of groups: 27385
```
I feel like the parameter is working, but a better documentation and some parameter checking would be good.

**Comment by TomSmithCGAT** [comment]
Good point. I'll add this to this TODO list for the next release.
