### ISSUE TITLE
Add option to consider read length when identifying duplicates

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/UMI-tools#8]
For sRNA-Seq, it's possible for two reads to have the same start position but different read lengths and therefore to have originated from different molecules (assuming no quality trimming has been performed). dedup_umi.py should have an option to consider read length along with the start position.

I propose adding the read length to the reads_dict key (defaulting to no value when read length not required).

Any thoughts before I go ahead?

**Comment by IanSudbery** [comment]
I think this makes sense for sRNA – cloning protocols for sRNAs can clone a
range of sizes, all of which are quite likely to be shorter than the length
of the read, and thus you will get genuine (not quality related) variation
in read length that represents genuinely different read lengths.



Adding a read length to the reads_dict key should solve this problem. Make
sure this is off by default though … it would be wrong in most cases.



Ian



*From:* Tom Smith [mailto:notifications@github.com]
*Sent:* 23 November 2015 08:39
*To:* CGATOxford/UMI-tools
*Subject:* [UMI-tools] Add option to consider read length when identifying
duplicates (#8)



For sRNA-Seq, it's possible for two reads to have the same start position
but different read lengths and therefore to have originated from different
molecules (assuming no quality trimming has been performed). dedup_umi.py
should have an option to consider read length along with the start position.

I propose adding the read length to the reads_dict key (defaulting to no
value when read length not required).

Any thoughts before I go ahead?

—
Reply to this email directly or view it on GitHub
<https://github.com/CGATOxford/UMI-tools/issues/8>.[image: Image removed by
sender.]

**Comment by TomSmithCGAT** [comment]
Fixed - ba55ddf6d031d153219d0abd3b0149be2b880833
