### ISSUE TITLE
same read in two different UIDs

### ISSUE THREAD

**Issue by vang42** [CGATOxford/UMI-tools#81]
I have discovered that whenI use umi-tools group, I get a small number of reads in more than one UID group. This happens in directional mode but nor in cluster or unique mode

This is my command:
umi_tools group -I input.bam --group-out=out.grouped --method=directional

example from out.grouped:

`
NB501001:62:HLWYHBGXX:1:11101:21260:7952_TGGGTG chr2    33141308        TGGGTG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:1343:4008_TGCTTC  chr2    33141308        TGCTTC  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:10035:1936_GTTGCG chr2    33141308        GTTGCG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:12509:6910_GGCTTT chr2    33141308        GGCTTT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:11269:1804_TGCGTT chr2    33141308        TGCGTT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:26772:3662_GGCGGA chr2    33141308        GGCGGA  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:19538:7351_GGTGAA chr2    33141308        GGTGAA  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:4771:8135_CCTGTT  chr2    33141308        CCTGTT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:15529:1778_CCTGAT chr2    33141308        CCTGAT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:6030:4996_GGGATG  chr2    33141308        GGGATG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:23689:4353_TTGGTG chr2    33141308        TTGGTG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:4319:7718_CAGGTG  chr2    33141308        CAGGTG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:4441:7220_GGTTCG  chr2    33141308        GGTTCG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:6939:5282_GCTGAT  chr2    33141308        GCTGAT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:2419:2205_TGGTTG  chr2    33141308        TGGTTG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:1499:2094_GGGGTG  chr2    33141308        GGGGTG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:6499:5070_TAAGTT  chr2    33141308        TAAGTT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:19874:5670_GGGTTG chr2    33141308        GGGTTG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:18506:2912_AGCTTT chr2    33141308        AGCTTT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:15357:1866_TGGTTT chr2    33141308        TGGTTT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:9107:7901_TAGGTG  chr2    33141308        TAGGTG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:19838:6076_GGGGTT chr2    33141308        GGGGTT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:11668:4187_CGGGAA chr2    33141308        CGGGAA  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:13119:1708_GTTGTA chr2    33141308        GTTGTA  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:9091:1768_GGCGCA  chr2    33141308        GGCGCA  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:15084:3827_TATTTT chr2    33141308        TATTTT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:4298:7359_GAAGTT  chr2    33141308        GAAGTT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:22013:2113_GGTGCA chr2    33141308        GGTGCA  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:24364:8057_TACTTT chr2    33141308        TACTTT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:16537:1522_GGTGCG chr2    33141308        GGTGCG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:26214:6434_CGTCAT chr2    33141308        CGTCAT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:1387:3045_GTGGTA  chr2    33141308        GTGGTA  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:16298:5581_GGCGAG chr2    33141308        GGCGAG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:20904:4618_TGGGTT chr2    33141308        TGGGTT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:25472:3713_GGGAAG chr2    33141308        GGGAAG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:11785:7420_TGTGTG chr2    33141308        TGTGTG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:3156:3139_GTTGTT  chr2    33141308        GTTGTT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:17089:6638_GGAGTT chr2    33141308        GGAGTT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:12124:6267_GGTGAT chr2    33141308        GGTGAT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:10542:1558_GGATTT chr2    33141308        GGATTT  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:5476:8280_CGTGAA  chr2    33141308        CGTGAA  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:22765:5504_CGTGTG chr2    33141308        CGTGTG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:5151:5165_GGTGAG  chr2    33141308        GGTGAG  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:11960:2794_TTGGTC chr2    33141308        TTGGTC  1       TGCTTT  51      1045
NB501001:62:HLWYHBGXX:1:11101:8660:2510_TTGTTG  chr2    33141308        TTGTTG  2       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:6318:5064_TTGTTG  chr2    33141308        TTGTTG  2       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:5567:5351_CCTCAT  chr2    33141308        CCTCAT  1       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:16618:7354_ATGTTG chr2    33141308        ATGTTG  1       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:6483:3903_CGGTTT  chr2    33141308        CGGTTT  1       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:21087:6157_GTTTCG chr2    33141308        GTTTCG  1       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:2974:7822_GGTGTG  chr2    33141308        GGTGTG  1       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:25965:1875_CTTGTT chr2    33141308        CTTGTT  1       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:21260:7952_TGGGTG chr2    33141308        TGGGTG  1       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:10035:1936_GTTGCG chr2    33141308        GTTGCG  1       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:12509:6910_GGCTTT chr2    33141308        GGCTTT  1       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:11269:1804_TGCGTT chr2    33141308        TGCGTT  1       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:26772:3662_GGCGGA chr2    33141308        GGCGGA  1       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:1166:6044_ATGTGG  chr2    33141308        ATGTGG  1       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:19538:7351_GGTGAA chr2    33141308        GGTGAA  1       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:4771:8135_CCTGTT  chr2    33141308        CCTGTT  1       TTGTTG  53      1046
NB501001:62:HLWYHBGXX:1:11101:12711:6210_AGGGGG chr2    33141308        AGGGGG  1       TTGTTG  53      1046
`

The read appearing two times is "NB501001:62:HLWYHBGXX:1:11101:10035:1936_GTTGCG". Do you know why this happens? I would be happy to give you a small test set to reproduce this if needed.

In my set of 10000 sequences, I see 46 reads in more than one UID group.

**Comment by TomSmithCGAT** [comment]
Hi @vang42. That's odd, and definitely not the intended output. If you could share some test data that would be great.

**Comment by vang42** [comment]
Thanks! I have send you an email with the data.

**Comment by TomSmithCGAT** [comment]
Thank vang.

I've pushed the changes required to fix the _group_ command with directional, and also enabled adjacency with _group_. 

If you need the update urgently, you can install UMI-tools from the {TS}-FixGroup branch (Let me know if you need instructions for how to do this).  Otherwise, these changes will be included in the next release (0.3.7) which should be available by the end of next week (3rd Feb)

**Comment by vang42** [comment]
Thanks a lt! It is working nicely.
