### ISSUE TITLE
umi_tools extract - fastq files missing header lines

### ISSUE THREAD

**Issue by simiii123** [CGATOxford/UMI-tools#92]
Hello,

I have encountered an issue during the extraction step. The resulting fastq files are randomly missing lines.

**command**:
_umi_tools extract --read2-in=$fastq2 --read2-out=$out2 --quality-encoding=phred33 --quality-filter-threshold=20 --random-seed=1 -I $fastq1 --bc-pattern NNNNNNNNNN -S $out1 -E $umi_err_

In almost all resulting fastq files, I see either missing header lines for some reads, or randomly inserted quality score lines. Not many in total, just very few of these per fastq file. After rerunning the command, the errors in the output files change, they end up affecting a different set of reads.

I also checked all of my input fastq files, they are ok.

I didn't have any issues installing umi_tools, and during execution there are not errors either. No complains at all. 
Did anyone else have this issue or is it most likely a problem with the installation on my server?

One more thing I just noticed: 
If I leave out the "-E $umi_err" in the command, the program seems to work fine...

All advice appreciated! Thanks a lot in advance.

**Comment by TomSmithCGAT** [comment]
Hi @simiii123. This is odd. I'm not able to replicate this. Would you mind sharing your input fastq? Ideally, small input file which always gives unexpected output (it doesn't need to give the same unexpected output each time)

I notice that you have paired reads but you've not supplied the `--split-barcode` option. This means the UMI will only be extracted from the first read. Is this the output you want?

**Comment by TomSmithCGAT** [comment]
Hi @simiii123. Are you still getting incorrect output with _extract_?

**Comment by TomSmithCGAT** [comment]
@simiii123 I'm going to close this issue. Please re-open if you still need assistance on this.
